### PR TITLE
PG: skip all leading whitespace in SQL statements.

### PR DESCRIPTION
**Pull request by direvus**
Previously the logic to skip leading whitespace only skipped over the
space character (0x20), but for SQL all leading whitespace characters
can be skipped.  Use the built-in std::isspace function to test for
this, rather than testing for the space character specifically.

The previous logic led to differences in the behaviour of queries,
because the logic to detect a 'SELECT' statement failed to detect valid
SELECT queries that began with whitespace other than 0x20.

Refs #4301

## What does this PR do?

Skip all leading whitespace, instead of just spaces, in SQL statements for the PostgreSQL driver.

## What are related issues/pull requests?

Related to #4301.

## Tasklist

 - [x] Build and test locally
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: MacOS 11.6
* Compiler: Xcode

### CODE REVIEW

**Comment by lnicola** [comment]
Adding an `#include <cctype>` might fix the Windows build on AppVeyor.

**Comment by rcoup** [comment]
Should we be skipping SQL comments too? 

```
-- my query
SELECT ...
```

**Comment by direvus** [comment]
> 
> Should we be skipping SQL comments too?
> 

I don't dislike that idea, but it's certainly a lot more effort.  There's double-dash comments and also slash-star comments to worry about. I might have a tinker with it and see how I go.

**Comment by jratike80** [comment]
Comments are skipped already if SQL statements are saved into file.

```
gdaltest.sql
============
-- my query
SELECT * from states limit 1

ogrinfo PG:"host=localhost port=5432 dbname=db user=user password=pw" -sql @gdaltest.sql

INFO: Open of ...
      using driver `PostgreSQL' successful.

Layer name: sql_statement
Geometry (wkb_geometry): Unknown (any)
Geometry (geom2): Unknown (any)
Feature Count: 1
```

There seems to be something to improve also in the @file syntax with the statement ending ";"

```
gdaltest.sql
============
-- my query
SELECT * from states limit 1;

ERROR 1: ERROR:  syntax error at or near ";"
LINE 1: SELECT count(*) FROM (SELECT * from states limit 1; ) AS ogr...

```

**Comment by direvus** [comment]
> 
> There seems to be something to improve also in the @file syntax with the statement ending ";"
> 
> ```
> gdaltest.sql
> ============
> -- my query
> SELECT * from states limit 1;
> 
> ERROR 1: ERROR:  syntax error at or near ";"
> LINE 1: SELECT count(*) FROM (SELECT * from states limit 1; ) AS ogr...
> ```

@jratike80  that does look like a bug to me, but I don't think it's much related to this PR.  Can I recommend that you raise a fresh issue for that?  I'm interesting in trying to fix it, feel free to mention me on the issue.

**Comment by direvus** [comment]
> 
> 
> Adding an `#include <cctype>` might fix the Windows build on AppVeyor.

Thanks for the tip, I've pushed a commit with that change.

**Pull request merged**
