### PR TITLE
SFCGAL: Use WKB instead of WKT

### PR DESCRIPTION
**Pull request by lbartoletti**
## What does this PR do?

This PR adds support for WKB (Well-Known Binary) instead of WKT (Well-Known Text) for SFCGAL versions greater than or equal to 1.5.2.

It is noted that SFCGAL introduced support for WKB in version 1.5.1, but full binary support is available starting from version 1.5.2. Therefore, this update ensures that WKB is utilized for SFCGAL versions 1.5.2 and above.

Additionally, the PR includes a check for the SFCGAL version using a configure_file to generate the ogr_sfcgal.h file, and modifications are made to the CMakeLists.txt to handle this versioning logic properly.

This PR is currently opened as a draft because I still need to verify some parts of the GDAL code to ensure everything is properly implemented and handled as expected.

## Tasklist

 - [x] Build with SFCGAL <= and >= 1.5.2
 - [X] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [x] Add test case(s)
 - [ ] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: Locally on FreeBSD 14 with SFCGAL 2.0.0 + GDAL CI
* Compiler: Clang + GDAL CI

### CODE REVIEW

**Review by rouault — COMMENTED** [review]
I see alpine:edge has sfcgdal 1.5.2, so we should get some CI testing for the new code path

**Comment by rouault** [comment]
@lbartoletti looks good to me. anything left on our side?

**Comment by lbartoletti** [comment]
> @lbartoletti looks good to me. anything left on our side?

Yes, I have to add tests

**Comment by rouault** [comment]
> Yes, I have to add tests

I haven't look in details, but there are SFCGAL related tests in autotest/ogr/ogr_geom.py . To be checked if they cover your added code paths.

**Comment by lbartoletti** [comment]
Dear Stale Bot,

I know I haven't been very responsive lately, but it's the end of the year and everyone's asking for things to be done, finalizing training sessions, end of budget, etc.

I promise I'll be a good developer and finalize my tests and checks before Christmas, so you too can enjoy your holiday season and rest far away from this PR.

Best regards

**Comment by lbartoletti** [comment]
> > Yes, I have to add tests
> 
> I haven't look in details, but there are SFCGAL related tests in autotest/ogr/ogr_geom.py . To be checked if they cover your added code paths.

I added a tiny missing test to ensure a good OGR<->SFCGAL conversion. I think, it's OK for now. I plan to add more tests ; and maybe SFCGAL's function if it's ok for GDAL

**Pull request merged**
