### PR TITLE
Allow flexible X/Y dimension ordering for NASA HDF data products using OpenOptions.

### PR DESCRIPTION
**Pull request by hyoklee**
## What does this PR do?

This PR utilizes OpenOptions to allow user to specify the correct X,Y,Band dimension and to handle 4/5 dimension dataset correctly.

In HDF4/HDF5, X and Y dimension can be arbitrary.  For example, both data[3=band][180=y][360=X] are data[360=x][3=band][180=y] are valid. 

## What are related issues/pull requests?

See the gdal-dev mailing list [discussion](https://lists.osgeo.org/pipermail/gdal-dev/2016-September/045201.html)  in 2016.

## Tasklist

 - [ ] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [X ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: CentOS 7
* Compiler: gcc/g++

### CODE REVIEW

**Comment by rouault** [comment]
Probably of interest: https://lists.osgeo.org/pipermail/gdal-dev/2019-May/050283.html

**Comment by rouault** [comment]
I'm wondering if that change is still needed now that RFC75 has passed : https://gdal.org/development/rfc/rfc75_multidimensional_arrays.html ? I'm currently working on implementing it for the HDF4 driver (the netCDF and HDF5 ones are already available in master)

**Comment by hyoklee** [comment]
@rouault, great to see that you've checked in the HDF5 driver code! I can't wait to see new HDF4 code for multi-dimensional handling. I'll review and test your HDF5 driver code. If it works well, my pull request can be ignored.

**Comment by rouault** [comment]
Is this PR still needed ?

**Comment by hyoklee** [comment]
No.

**Pull request closed without merging**
