### PR TITLE
Add NOGCP option to the GEORASTER format support.

### PR DESCRIPTION
**Pull request by fechen123**
## What does this PR do?
Add NOGCP option in converting to GEORASTER format. 

## What are related issues/pull requests?
There is no related issue. This is an enhancement.

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by IvanLucena** [comment]
I just wondering if that should be implemented as a gdal_translate (and API) option, like -norat.

**Comment by rouault** [comment]
> I just wondering if that should be implemented as a gdal_translate (and API) option, like -norat.

Agreed

**Comment by fechen123** [comment]
That is ok. When do I expect this be done? ( I am not familiar with GDAL enough to do this)

**Comment by rouault** [comment]
> When do I expect this be done? ( I am not familiar with GDAL enough to do this)
When someone with enough interest does it :-)

Closing this PR as it is a dead end

**Pull request closed without merging**
