### PR TITLE
Bindings: OGR: SRS: add C-wrappers and SWIG bindings for `{Set,Get}Extension` functions

### PR DESCRIPTION
**Pull request by and-marsh**
### Summary
Add C-wrappers and SWIG bindings for `{Set,Get}Extension` functions.

I didn't found C-wrappers for these functions and decided to create them by my own. I hope it will be helpful for users. 

I'd like to get your review, please, tell me if there is something to improve in this PR.

### CODE REVIEW

**Comment by rouault** [comment]
Why do you need that ? I'd perfer not encouraging those non-standard EXTENSION nodes. They should be hopefully no longer, or very rarely used, with GDAL 3 / WKT 2

**Comment by and-marsh** [comment]
Hmm, I need to be able to use vertical geoids during transformation from `EPSG:4979` to any other CRS. So i wanted to add geoid file as extension, and use `ExportToProjString()` that returns proj string with `+geoidgrids=[geoidFileName]` to force using any available geoid. Otherwise most of geoids don't work if source CRS is `EPSG:4979`.

But if you suppose, that is a bad idea, i will close PR and find another way

**Comment by rouault** [comment]
I'm currently looking at improvements on PROJ side regarding geoid grids. Not sure how it will translate to GDAL OGRSpatialReference. But in the meantime, you could propably just export the CRS as projstring, manually add +geoidgrids, and reimport that.

**Comment by and-marsh** [comment]
Ok, thank you

**Pull request closed without merging**
