### PR TITLE
MIraMonVector fixes (2) tests improvements (+10)

### PR DESCRIPTION
**Pull request by AbelPau**
## What does this PR do?
**Fixes**

- Delete of unused function (MMInitHeader)
- Use of CPLError() in some explicit return errors

**Test improvements**

- last_version added in -lco Version
- more corrupted files tested
- unexisting coordinates or unexpected polygon construction tested datefield added in tests
- code simplification
- multipolygon Z added in tests
- multigeometry added in tests
- ANSI DBFEncoding test added
 
## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [x] Add test case(s)
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by rouault** [comment]
why did you close the PR ?

**Comment by AbelPau** [comment]
I just updated from main to my branch. I am passing actions in my branch and later I'll PR again.

**Comment by rouault** [comment]
> continuous-integration/appveyor/pr — AppVeyor was unable to build non-mergeable pull request

unrelated to your work. We also have this in other PRs. I believe this is related to the current github incident: https://www.githubstatus.com/

I believe you can just re-open this PR

**Comment by AbelPau** [comment]
> > continuous-integration/appveyor/pr — AppVeyor was unable to build non-mergeable pull request
> 
> unrelated to your work. We also have this in other PRs. I believe this is related to the current github incident: https://www.githubstatus.com/
> 
> I believe you can just re-open this PR

I can't do it cause I did somehting more to my branch. I start from  in another PR.

**Pull request closed without merging**
