### PR TITLE
PDS4: add support for reading and writing Oblique Cylindrical

### PR DESCRIPTION
**Pull request by rouault**
[redacted]

### CODE REVIEW

**Comment by rouault** [comment]
Answering to myself: no, this is not correct, while comparing with the result of the PDS driver. I have to take into account PositiveWest longitudes and the geotransform rotation due to map_projection_rotation = 90

**Comment by thareUSGS** [comment]
I am ready to review when you get updates. For the Cassini labels (and most use cases for this projection), map_projection_rotation will always be set to 90.

**Comment by rouault** [comment]
Things seem to be in order now:

- with old PDS driver,
```
$ gdalinfo BIEQH14N063_D285_T126S04_V02.IMG
Driver: PDS/NASA Planetary Data System
Files: BIEQH14N063_D285_T126S04_V02.IMG
Size is 1024, 3840
Coordinate System is:
PROJCRS["OBLIQUE_CYLINDRICAL TITAN",
    BASEGEOGCRS["GCS_TITAN",
        DATUM["D_TITAN",
            ELLIPSOID["TITAN",2575000,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Reference_Meridian",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["unknown",
        METHOD["PROJ ob_tran o_proj=eqc"],
        PARAMETER["o_lon_p",-158.352054,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        PARAMETER["o_lat_p",191.769776,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        PARAMETER["lon_0",-163.331591,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
    REMARK["PROJ CRS string: +proj=ob_tran +R=2575000 +o_proj=eqc +o_lon_p=-158.352054 +o_lat_p=191.769776 +lon_0=-163.331591 +wktext +no_defs"]]
Data axis to CRS axis mapping: 1,2
GeoTransform =
  -3190898.22208, 0, 351.11116
  -764017.88416, 351.11116, 0
Metadata:
  BANDWIDTH=
  CENTER_FILTER_WAVELENGTH=
  DATA_SET_ID="CO-SSA-RADAR-5-BIDR-V1.0"
  FILTER_NAME=
  INSTRUMENT_ID=RADAR
  INSTRUMENT_NAME="CASSINI RADAR"
  MISSION_NAME="CASSINI-HUYGENS"
  NOTE=
  PRODUCER_INSTITUTION_NAME="JET PROPULSION LABORATORY"
  PRODUCT_CREATION_TIME=2017-228T23:02:54.000
  PRODUCT_ID=BIEQH14N063_D285_T126S04_V02
  PRODUCT_TYPE=
  SPACECRAFT_NAME=
  START_TIME=2017-112T06:01:09.523
  STOP_TIME=2017-112T06:03:06.509
  TARGET_NAME=TITAN
Corner Coordinates:
Upper Left  (-3190898.222, -764017.884) ( 56d 9'26.98"W,  0d56'20.11"N)
Lower Left  (-1842631.368, -764017.884) ( 60d17'57.83"W, 29d19'34.18"N)
Upper Right (-3190898.222, -404480.056) ( 63d58'53.45"W,  0d43'52.28"S)
Lower Right (-1842631.368, -404480.056) ( 69d22'52.70"W, 28d26' 7.62"N)
Center      (-2516764.795, -584248.970) ( 62d45'22.17"W, 14d28'25.91"N)
Band 1 Block=1024x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-3.40282265508890445e+38
```

- with PDS4 driver, read-support:
```
$ gdalinfo BIEQH14N063_D285_T126S04_V02.xml 
Driver: PDS4/NASA Planetary Data System 4
Files: BIEQH14N063_D285_T126S04_V02.xml
       BIEQH14N063_D285_T126S04_V02.IMG
Size is 1024, 3840
Coordinate System is:
PROJCRS["Oblique Cylindrical TITAN",
    BASEGEOGCRS["GCS_TITAN",
        DATUM["D_TITAN",
            ELLIPSOID["TITAN",2575000,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Reference_Meridian",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["unknown",
        METHOD["PROJ ob_tran o_proj=eqc"],
        PARAMETER["o_lon_p",-158.352054,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        PARAMETER["o_lat_p",191.769776,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        PARAMETER["lon_0",-163.331591,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["Metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["Metre",1]],
    REMARK["PROJ CRS string: +proj=ob_tran +R=2575000 +o_proj=eqc +o_lon_p=-158.352054 +o_lat_p=191.769776 +lon_0=-163.331591 +wktext +no_defs"]]
Data axis to CRS axis mapping: 1,2
GeoTransform =
  -3190898.22208, 0, 351.11116
  -764017.88416, 351.11116, 0
Corner Coordinates:
Upper Left  (-3190898.222, -764017.884) ( 56d 9'26.98"W,  0d56'20.11"N)
Lower Left  (-1842631.368, -764017.884) ( 60d17'57.83"W, 29d19'34.18"N)
Upper Right (-3190898.222, -404480.056) ( 63d58'53.45"W,  0d43'52.28"S)
Lower Right (-1842631.368, -404480.056) ( 69d22'52.70"W, 28d26' 7.62"N)
Center      (-2516764.795, -584248.970) ( 62d45'22.17"W, 14d28'25.91"N)
Band 1 Block=1024x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-inf
```

- with PDS4 driver, write-support:
```
$ gdal_translate -of PDS4 -co CREATE_LABEL_ONLY=YES -co TEMPLATE=BIEQH14N063_D285_T126S04_V02.xml  BIEQH14N063_D285_T126S04_V02.IMG out.xml
$ gdalinfo out.xml
Driver: PDS4/NASA Planetary Data System 4
Files: out.xml
       BIEQH14N063_D285_T126S04_V02.IMG
Size is 1024, 3840
Coordinate System is:
PROJCRS["Oblique Cylindrical TITAN",
    BASEGEOGCRS["GCS_TITAN",
        DATUM["D_TITAN",
            ELLIPSOID["TITAN",2575000,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Reference_Meridian",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["unknown",
        METHOD["PROJ ob_tran o_proj=eqc"],
        PARAMETER["o_lon_p",-158.352054,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        PARAMETER["o_lat_p",191.769776,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        PARAMETER["lon_0",-163.331591,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["Metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["Metre",1]],
    REMARK["PROJ CRS string: +proj=ob_tran +R=2575000 +o_proj=eqc +o_lon_p=-158.352054 +o_lat_p=191.769776 +lon_0=-163.331591 +wktext +no_defs"]]
Data axis to CRS axis mapping: 1,2
GeoTransform =
  -3190898.22208, 0, 351.11116
  -764017.88416, 351.11116, 0
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-3190898.222, -764017.884) ( 56d 9'26.98"W,  0d56'20.11"N)
Lower Left  (-1842631.368, -764017.884) ( 60d17'57.83"W, 29d19'34.18"N)
Upper Right (-3190898.222, -404480.056) ( 63d58'53.45"W,  0d43'52.28"S)
Lower Right (-1842631.368, -404480.056) ( 69d22'52.70"W, 28d26' 7.62"N)
Center      (-2516764.795, -584248.970) ( 62d45'22.17"W, 14d28'25.91"N)
Band 1 Block=1024x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-3.40282265508890445e+38
```

**Comment by thareUSGS** [comment]
I agree - looks like the mapping is correct now.

**Pull request merged**
