### PR TITLE
gdal_rasterize: ignore features whose Z attribute is null/unset (fixes #7241)

### LINKED ISSUE #7241: IDW Error: Null value considered as 0
Null values are considered as 0 in IDW GDAL interpolation

I´m having the same bug with GDAL IDW interpolation in QGIS (3.16 & . 3.28)
Example:
We consider 5 points where 4 of them at the extremes always have a value of 10 and the central point with three assumptions:

All values -> All points with a value of 10.
0_Value -> Centre point value of 0
Null_Value-> Centre point value of Null
Result:

The resulting interpolated layer behaves:

In assumption 1 constant raster layer with value of 10.
Assumptions 2 and 3. The resulting raster layer shows a central depression with a value of 0.
I understand that the result in assumption 1 should be a constant layer with value equal to 10 and not the result that results in the resulting layer giving a value of 0 at the point with null value.
(I have taken into account a very wide search radius value to avoid problems in "locating points")

Versions
(Also tested in 3.16.16 with the same bug)

Versión de QGIS
3.28.3-Firenze
Revisión del código de QGIS
https://github.com/qgis/QGIS/commit/c12bcb2f76c9a77fd4d3f9579e0c3f863237eb2f
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.2
Versión de PROJ
9.1.1
Versión del registro de base de datos EPSG
v10.076 (2022-08-31)
Versión de GEOS
3.11.1-CAPI-1.17.1
Versión de SQLite
3.39.4
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
Cadastral_Divisions-main
1.2
ClipMultipleLayers
3.2.0
contour
2.0.12
dataexplorer
3.1.1
DataPlotly
3.9.2
kmltools
3.1.27
latlontools
3.6.8
magic_map_loader
1.0
mmqgis
2021.9.10
PlanCreator-3
0.1
PluginLoadTimes
3.0.1
pointsamplingtool
0.5.4
polystrip
3.0.1
processing_saga_nextgen
0.0.7
profiletool
4.2.2
project_report
1.2

Qgis2threejs
2.7.1
qgis2web
3.16.0
QGISSortAndNumber-master
1.0
quick_map_services
0.19.33
refFunctions
1.6
rvt-qgis
0.9.4.1
searchlayers
3.0.12
Serval
3.10.5
Smart_Map
1.2
Spanish_Inspire_Catastral_Downloader
1.1
SpreadsheetLayers
2.1.0-alpha1
StreetView
3.2
Submission
0.7
ThreePointMethod
0.1
valuetool
3.0.15
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
-->

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

[IDW_GDAL_ERROR.zip](https://github.com/OSGeo/gdal/files/10722188/IDW_GDAL_ERROR.zip)

a651-e97d05a4ef13.jpg)

[IDW_GDAL_ERROR.zip](https://github.com/OSGeo/gdal/files/10722198/IDW_GDAL_ERROR.zip)

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
The backport to `release/3.6` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 682f876aed... gdal_rasterize: ignore features whose Z attribute is null/unset (fixes #7241)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/utilities/test_gdal_grid_lib.py
CONFLICT (content): Merge conflict in autotest/utilities/test_gdal_grid_lib.py

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.6 release/3.6
# Navigate to the new working tree
cd .worktrees/backport-release/3.6
# Create a new branch
git switch --create backport-7244-to-release/3.6
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 682f876aed74227cc929db46ad1a446c8641d41b
# Push it to GitHub
git push --set-upstream origin backport-7244-to-release/3.6
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.6
```
Then, create a pull request where the `base` branch is `release/3.6` and the `compare`/`head` branch is `backport-7244-to-release/3.6`.

**Comment by rouault** [comment]
manually cherry-picked to 3.6 per 2a6ea1b2174369453d61d238ccf5d07cbe3bfb10

**Comment by cesarcorreo** [comment]
Dear Rouault,
I opened the issue in QGIS. I'm not familiar wuth the process about fix bugs in QGIS and / or gdal. 
I updated the QGIS vertion to 3.30 but it seems that the problem is still there.
I am not able to interpret whether the problem has been solved in GDAL or persists. 
Thank you

**Comment by rouault** [comment]
The fix will go in GDAL 3.6.3, that should be released in the next days

**Comment by cesarcorreo** [comment]
Thanks a lot.
(But, I imagine that it will be necessary to wait for a new QGIS update to
incorporate the fix, right?)
*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*

**Comment by rouault** [comment]
> (But, I imagine that it will be necessary to wait for a new QGIS update to incorporate the fix, right?)

yes. Well that depends on how you get QGIS. But if it is through the Windows OSGeo4W installer, this will have to wait for GDAL 3.6.3 to be integrated. So probably for QGIS 3.30.1, but that's not under then control from GDAL

**Comment by cesarcorreo** [comment]
Thanks again.
Best
*________________*


*César Herrera Lindo <http://www.cesarpagina.com>*

**Pull request merged**
