### PR TITLE
GDALCreateGenImgProjTransformer2(): deal with discontinuity of GCPs around antimeridian (fixes #8371)

### LINKED ISSUE #8371: warp: for GCPs, finding the narrower "longitude range" across the anti-meridian
`AutoCreateWarpedVRT` on this anti-meridian-crossing swath generates a bad extent. 

```python
from osgeo import gdal

## convert raster properties to extent
def gt_dim_ex(gt, dim):
  ## xmin, xmax, ymin, ymax
  return [gt[0], gt[0] + dim[0] * gt[1], gt[3] + dim[1] * gt[5], gt[3]]


## tiff with GCPs
dsn = "/vsizip//vsicurl/https://github.com/rasterio/rasterio/files/12454591/iw-vv_small.tiff.zip"
ds = gdal.Open(dsn)

aw = gdal.AutoCreateWarpedVRT(ds, ds.GetGCPSpatialRef().ExportToWkt(), '+proj=laea +lon_0=180 +lat_0=61')
aw.GetGeoTransform()
# (-3309145.0388993337, 2063.668889186528, 0.0, 6133107.204230469, 0.0, -2063.668889186528)
gt_dim_ex(aw.GetGeoTransform(), [aw.RasterXSize, aw.RasterYSize])
# [-3309145.0388993337, 3156329.590922058, 6074.272235667333, 6133107.204230469]

```

Because the range of the X values in the GCPs is `[-179.9847  179.9921]` but should be considered as `[-184.6827 -179.3333]` (or `[175.3173 180.6667]`) to unwrap where the range is considered locally. 

A more reasonable geotransform in this case would be

```
-253571.00000      96.56933       0.00000  218510.00000       0.00000     -97.65609 
```
similarly, if we go with the default heuristic we get an unhelpful range in longlat: 

```python
swo = gdal.SuggestedWarpOutput(ds, ())
## this doesn't even encompass the data range in [-180, 180]
gt_dim_ex(swo.geotransform, [swo.width, swo.height])
#[-97.99753203291411, 226.16286236161127, 60.94616122521394, 62.88491956489412]

```

I feel like a detection on when the numeric range of longitude is very much wider than the unwrapped longitude range the heuristic could pick the narrower one. I have had this in mind to explore in the long term, it comes up in warping with geolocation arrays and GCPs and causes a bit of churn in downstream software. 

I'll expand on examples that give similar behaviours.    

this from a rasterio discussion: https://github.com/rasterio/rasterio/issues/2892#issuecomment-1695653740

### PR DESCRIPTION
**Pull request by rouault**
@mdsumner Any opinion on the GCP_ANTIMERIDIAN_UNWARPING option naming ?

### CODE REVIEW

**Comment by mdsumner** [comment]
why "unwarping" specifically?  I think of it as unwrapping

I appreciate the addition of an option - won't be able to try this out immediately

**Comment by rouault** [comment]
> I think of it as unwrapping

ah yes, I mean that. Always mixing them together :-)

**Comment by mdsumner** [comment]
it's very unfortunate,  near syntax for concepts very closely linked!

the naming is good, I suspect there's similar issues for geolocation arrays and some related stuff in suggested warp output, glad to see this clarified 👌

**Comment by mdsumner** [comment]
still need two "p"s : wrapping, vs wrap

maybe stick with "unwrap" i e. 

GCP_ANTIMERIDIAN_UNWRAP and avoid the pp completely 🙏

I can't really review deeply rn sorry but I will

**Comment by rouault** [comment]
> maybe stick with "unwrap" i e. GCP_ANTIMERIDIAN_UNWRAP and avoid the pp completely 🙏

done

**Comment by mdsumner** [comment]
all good in terms of consistency of naming in the code  👌

Looks great!

**Pull request merged**
