### PR TITLE
[pgeo][doc] Remove outdated instructions regarding MDBTools and DSN setup requirements

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs discussion at https://github.com/OSGeo/gdal/pull/2854#issuecomment-673335197

### CODE REVIEW

**Comment by rouault** [comment]
CC @sebastic FYI, I see in https://salsa.debian.org/debian/mdbtools/-/blob/master/debian/watch, Debian follows https://github.com/brianb/mdbtools whose last commit was in 2017 whereas @nyalldawson suggests to follow https://github.com/evanmiller/mdbtools which has lately received a lot of fixes from what I can see

**Comment by mloskot** [comment]
Thanks @nyalldawson !

**Comment by sebastic** [comment]
I've forwarded the the suggestion to use the fork in [Debian Bug #968384](https://bugs.debian.org/968384).

**Comment by sebastic** [comment]
From [Debian Bug #968384](https://bugs.debian.org/968384):
> Evan Miller just got write access to the original repository [1] that Debian is following.
> There now is a redirection from https://github.com/brianb/mdbtools to https://github.com/mdbtools/mdbtools on the Microsoft side.
> He's planning to merge everything there [2] soon.
> Debian urls should be updated.
> 
> [1] https://github.com/brianb/mdbtools
> [2] https://github.com/mdbtools/mdbtools/pull/162

**Pull request merged**
