### PR TITLE
/vsicurl/: when CPL_CURL_VERBOSE is enabled, log as CPLDebug() message…

### PR DESCRIPTION
**Pull request by rouault**
the error message from the server ... if there's one when checking the file size. Typically, servers
don't return an error message for the HEAD request. So one may have to
set CPL_VSIL_CURL_USE_HEAD=NO to force a GET request, which can return
an error message in the HTTP response.

### CODE REVIEW

**Comment by DFEvans** [comment]
Thanks Even. Going by your commit message, does this only report messages that are returned when initially opening a file and getting the file size, or did you mention that simply because that's the only case of using HEAD rather than GET?

In the case I'm having trouble with and trying to debug, the problem is that Reads (or equally Writes, I guess) start failing after the file handle has been open for some time (likely a credentials expiry issue, but solving that is unrelated to this PR!).

**Comment by rouault** [comment]
> does this only report messages that are returned when initially opening a file and getting the file size,

yes. I could also potentially add a commit for  range requests.
If your issue is with /vsis3/, then you should get more details when enabling CPL_DEBUG=ON

**Comment by DFEvans** [comment]
It is /vsis3/ - I'll give CPL_DEBUG a go tomorrow and see whether that gives the extra details that help pinning this down, thanks.

**Comment by DFEvans** [comment]
Coming back much later than "tomorrow", I can confirm that CPL_DEBUG does include explanatory messages with the sort of info I was after:
```
CPLE_None in S3: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>a-very-very-fake-s3-bucket</BucketName><RequestId>8H2EPKT16ST2KQFH</RequestId><HostId>49HqtO7MwHapjD0TY1XvIcPyRKMjQ2wlyW7fh2DpelJ5BpkyJehzwXwn55x/YGi1a4jv/uQjtuM=</HostId></Error>
```

(These logs were being suppressed by some quirks and bugs in the logging setup on my end, hence my confusion; I think the CPL_CURL_VERBOSE messages get emitted on a separate stream, or `rasterio` captures them differently)

**Comment by rouault** [comment]
> CPL_CURL_VERBOSE messages get emitted on a separate stream,

yes, it is emitted directly be curl on the standard error stream, so rasterio can't capture it. But I see https://curl.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html could be a way for GDAL to capture it and emit it through its debug/log infrastructure

**Review by nyalldawson — APPROVED** [review]

**Comment by rouault** [comment]
I've added a new commit: "CPLHTTPSetOptions(): if CPL_DEBUG is set, emit CPL_CURL_VERBOSE messages through CPLDebug() infrastructure"

Demo:
```
$ gdalinfo /vsicurl/https://a-very-very-fake-s3-bucket.s3.amazonaws.com/example.tif --debug on --config CPL_CURL_VERBOSE YES

HTTP: libcurl/7.68.0 GnuTLS/3.6.13 zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
CURL_INFO_TEXT: Couldn't find host a-very-very-fake-s3-bucket.s3.amazonaws.com in the .netrc file; using defaults
CURL_INFO_TEXT:   Trying 52.217.18.196:443...
CURL_INFO_TEXT: TCP_NODELAY set
CURL_INFO_TEXT: Connected to a-very-very-fake-s3-bucket.s3.amazonaws.com (52.217.18.196) port 443 (#0)
CURL_INFO_TEXT: found 385 certificates in /etc/ssl/certs
CURL_INFO_TEXT: ALPN, offering h2
CURL_INFO_TEXT: ALPN, offering http/1.1
CURL_INFO_TEXT: SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
CURL_INFO_TEXT: 	 server certificate verification OK
CURL_INFO_TEXT: 	 server certificate status verification SKIPPED
CURL_INFO_TEXT: 	 common name: *.s3.amazonaws.com (matched)
CURL_INFO_TEXT: 	 server certificate expiration date OK
CURL_INFO_TEXT: 	 server certificate activation date OK
CURL_INFO_TEXT: 	 certificate public key: RSA
CURL_INFO_TEXT: 	 certificate version: #3
CURL_INFO_TEXT: 	 subject: CN=*.s3.amazonaws.com
CURL_INFO_TEXT: 	 start date: Wed, 15 Dec 2021 00:00:00 GMT
CURL_INFO_TEXT: 	 expire date: Sat, 03 Dec 2022 23:59:59 GMT
CURL_INFO_TEXT: 	 issuer: C=US,O=Amazon,OU=Server CA 1B,CN=Amazon
CURL_INFO_TEXT: ALPN, server did not agree to a protocol
CURL_INFO_HEADER_OUT: HEAD /example.tif HTTP/1.1
Host: a-very-very-fake-s3-bucket.s3.amazonaws.com
Accept: */*

CURL_INFO_TEXT: Mark bundle as not supporting multiuse
CURL_INFO_HEADER_IN: HTTP/1.1 404 Not Found
CURL_INFO_HEADER_IN: x-amz-request-id: BHYCRVF613TDMBWQ
CURL_INFO_HEADER_IN: x-amz-id-2: yKeCXrMOiocWj+1LL/dmotB7SNBAo+bC2x8gYJdNHwIr7HvV0h5mY0lrnv/dyPiIZdN/W0AI0qE=
CURL_INFO_HEADER_IN: Content-Type: application/xml
CURL_INFO_HEADER_IN: Date: Wed, 13 Jul 2022 10:12:14 GMT
CURL_INFO_HEADER_IN: Server: AmazonS3
CURL_INFO_HEADER_IN: 
CURL_INFO_TEXT: Connection #0 to host a-very-very-fake-s3-bucket.s3.amazonaws.com left intact
VSICURL: GetFileSize(https://a-very-very-fake-s3-bucket.s3.amazonaws.com/example.tif): response_code=404, server error msg=HTTP/1.1 404 Not Found
x-amz-request-id: BHYCRVF613TDMBWQ
x-amz-id-2: yKeCXrMOiocWj+1LL/dmotB7SNBAo+bC2x8gYJdNHwIr7HvV0h5mY0lrnv/dyPiIZdN/W0AI0qE=
Content-Type: application/xml
Date: Wed, 13 Jul 2022 10:12:14 GMT
Server: AmazonS3


VSICURL: GetFileList(/vsicurl/https://a-very-very-fake-s3-bucket.s3.amazonaws.com)
CURL_INFO_TEXT: Couldn't find host a-very-very-fake-s3-bucket.s3.amazonaws.com in the .netrc file; using defaults
CURL_INFO_TEXT: Found bundle for host a-very-very-fake-s3-bucket.s3.amazonaws.com: 0x5568808bb980 [serially]
CURL_INFO_TEXT: Can not multiplex, even if we wanted to!
CURL_INFO_TEXT: Re-using existing connection! (#0) with host a-very-very-fake-s3-bucket.s3.amazonaws.com
CURL_INFO_TEXT: Connected to a-very-very-fake-s3-bucket.s3.amazonaws.com (52.217.18.196) port 443 (#0)
CURL_INFO_HEADER_OUT: GET / HTTP/1.1
Host: a-very-very-fake-s3-bucket.s3.amazonaws.com
Accept: */*

CURL_INFO_TEXT: Mark bundle as not supporting multiuse
CURL_INFO_HEADER_IN: HTTP/1.1 404 Not Found
CURL_INFO_HEADER_IN: x-amz-request-id: BHY4H1GF2AG4JP6R
CURL_INFO_HEADER_IN: x-amz-id-2: 97ecsCGnXbO+KODS2gdz2jbDvbcd2e8bjurbif9lLK+DVQcOXa7C0nBdyzjE5FA5tM1FwK5jwsQ=
CURL_INFO_HEADER_IN: Content-Type: application/xml
CURL_INFO_HEADER_IN: Transfer-Encoding: chunked
CURL_INFO_HEADER_IN: Date: Wed, 13 Jul 2022 10:12:15 GMT
CURL_INFO_HEADER_IN: Server: AmazonS3
CURL_INFO_HEADER_IN: 
CURL_INFO_TEXT: Connection #0 to host a-very-very-fake-s3-bucket.s3.amazonaws.com left intact
ERROR 11: HTTP response code: 404
gdalinfo failed - unable to open '/vsicurl/https://a-very-very-fake-s3-bucket.s3.amazonaws.com/example.tif'.
```

**Pull request merged**
