### PR TITLE
Generate gcore/gdal_version.h from git date and sha for a dev version (Unix builds only)

### PR DESCRIPTION
**Pull request by rouault**
If gcore/gdal_version.h.in contains 'dev' in GDAL_RELEASE_NAME then include
the sha of the latest commit in it. And replace GDAL_RELEASE_DATE with the
date of the commit.

On Windows, or if git not available, just copy gcore/gdal_version.h.in unmodified.

### CODE REVIEW

**Comment by NathanW2** [comment]
Nice. I was going to make a patch for this at some stage as well.

**Comment by rouault** [comment]
> I was going to make a patch for this at some stage as well.

If you are interested on the Windows/nmake side, the equivalent of this would be welcome

**Comment by NathanW2** [comment]
Sure.  Looks like most of the work is already there just the logic to get the sha etc right?

**Comment by rouault** [comment]
@NathanW2 Instead of the `copy gdal_version.h.in gdal_version.h` at https://github.com/OSGeo/gdal/blob/master/gdal/gcore/makefile.vc#L42 , there should be a call to a generate_gdal_version_h.bat that would do the same as https://github.com/OSGeo/gdal/blob/master/gdal/gcore/generate_gdal_version_h.sh

**Comment by NathanW2** [comment]
@rouault sweet no worries. I'll see what I can do.

**Pull request merged**
