### PR TITLE
FlatGeobuf: fix build error when new Abseil headers are present (fixes #7894)

### LINKED ISSUE #7894: Build error: flatgeobuf using incompatible absl/strings/string_view.h
## Expected behavior and actual behavior.

From https://github.com/microsoft/vcpkg/issues/31804: 
On some machines, buidling gdal 3.7.0 may fail like this:
~~~
In file included from /usr/include/absl/base/config.h:86,
                 from /usr/include/absl/base/attributes.h:37,
                 from /usr/include/absl/strings/string_view.h:39,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h:237,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/array.h:20,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flatbuffers.h:22,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/header_generated.h:6,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h:36,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp:29:
/usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^~~~~
~~~

## Steps to reproduce the problem.

`vcpkg install gdal` on an affected system.

## Operating system

Manjaro Linux 22.1.0 Talos

## GDAL version and provenance

3.7.0, building via vcpkg.

## More information

The flatgeobuf driver uses a vendored copy of flatbuffer. That version may use abseil's string view if it is available:
https://github.com/OSGeo/gdal/blob/ab9cb1a1d4928cdcf2877d8e0c6ad9fc2c79fbc9/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h#L236-L237

Newer versions of flatbuffers add more conditions to guard the use of abseil's string_view:
https://github.com/google/flatbuffers/blob/72b56fd0810c9a6cd38ea1c8f40feaa1bb4916b1/include/flatbuffers/base.h#L237-L239

This probably fixes the problem.

FTR vcpkg has packages for abseil and flatbuffers.
But there is no configuration hook to use them during them during the build.
gdal should avoid picking up abseil without control.

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by dg0yt** [comment]
One problem remains: This makes the gdal build rely on abseil in an uncontrolled way. I cannot turn the dependency on or off. I cannot say which prefix should provide abseil.

**Comment by rouault** [comment]
> I cannot turn the dependency on or off. I cannot say which prefix should provide abseil.

Well, this comes from upstream flatbuffers.

Top CMakeLists.txt has a ``set(CMAKE_CXX_STANDARD 11)`` (if CMAKE_CXX_STANDARD is not explicitly specified) whose effect seems to cause -std=gnu++11 with gcc, so the ``__cplusplus >= 201411`` check will be false. Looking at https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170, it should also be the case with MSVC that is stuck at __cplusplus = 199711L . So I don't think Abseil headers can be used

**Review by dg0yt — APPROVED** [review]
Okay, it is following upstream.
... even if it is a complicate way to never use abseil at this spot.

**Comment by rouault** [comment]
The backport to `release/3.7` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply c31bffd963... FlatGeobuf: fix build error when new Abseil headers are present (fixes #7894)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging scripts/clang-format.sh
CONFLICT (content): Merge conflict in scripts/clang-format.sh

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.7 release/3.7
# Navigate to the new working tree
cd .worktrees/backport-release/3.7
# Create a new branch
git switch --create backport-7896-to-release/3.7
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick c31bffd963e9e9c69335196089d779b1cf465d75
# Push it to GitHub
git push --set-upstream origin backport-7896-to-release/3.7
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.7
```
Then, create a pull request where the `base` branch is `release/3.7` and the `compare`/`head` branch is `backport-7896-to-release/3.7`.

**Comment by rouault** [comment]
backported to 3.7 per e6e07b058d9c01d4d6c6208fcf5c21314e7ac09c

**Pull request merged**
