### PR TITLE
Python code: Remove more bare exceptions

### PR DESCRIPTION
**Pull request by bje-**
## What does this PR do?

Continues to remove bare exceptions, replacing them with a more appropriate `except` statement. Still picking off the easiest ones. About 800 to go!

### CODE REVIEW

**Comment by rouault** [comment]
```
autotest/gcore/hfa_write.py:194: undefined name 'os'
autotest/osr/osr_ct_proj.py:72: undefined name 'proj_lib'
```

```
Traceback (most recent call last):
  File "pymod/gdaltest_python3.py", line 44, in run_func
    result = func()
  File "./ecw.py", line 2489, in ecw_cleanup
    fname = gdaltest.ecw_38_fname
AttributeError: 'module' object has no attribute 'ecw_38_fname'
```

```
 ------------ Failures ------------
Script: gcore/hfa_write.py
  TEST: hfa_clean_external_overviews ... fail (blowup)
 ----------------------------------
```

**Comment by rouault** [comment]
Still an issue with
```
  TEST: ecw_cleanup ... fail (blowup)
Traceback (most recent call last):
  File "pymod/gdaltest_python2.py", line 43, in run_func
    result = func()
  File "./ecw.py", line 2489, in ecw_cleanup
    fname = gdaltest.ecw_38_fname
```

**Comment by bje-** [comment]
Oh, sorry, I didn't get this second error in the mail message.

**Comment by rouault** [comment]
Still not correct. The use of gdaltest.ecw_38_fname is needed since it is used in a _cleanup() function which is not the same as where fname is defined.
```
autotest/gdrivers/ecw.py:2488: undefined name 'fname'
autotest/gdrivers/ecw.py:2492: undefined name 'fname'
```

**Comment by rouault** [comment]
Branch continued, rebased and squashed + ecw fix in https://github.com/rouault/gdal/tree/more-bare-exceptions-rebased . https://travis-ci.org/rouault/gdal/builds/367540884

**Comment by rouault** [comment]
https://github.com/rouault/gdal/tree/more-bare-exceptions-rebased merged

**Pull request closed without merging**
