### PR TITLE
add test for default tiff ovrview blocksize (#1611)

### PR DESCRIPTION
**Pull request by tbonfort**
test never added for #1611, doing this now. fails locally, awaiting ci tests.

### CODE REVIEW

**Comment by rouault** [comment]
@tbonfort Any idea why it fails locally for you ? I can only think to GDAL_TIFF_OVR_BLOCKSIZE being defined in your environment

**Comment by tbonfort** [comment]
it's not the only test to fail, I have 15% failures on tiff_write, not only related to blocksize. It might be because I have a minimal build, but strange nonetheless.

**Comment by tbonfort** [comment]
For the record, tests where picking up the system version of gdal/python instead of the one I compiled in a non standard directory. When compiling gdal with `--prefix=$foo` the tests should be ran with `PYTHONPATH=$foo/lib/python3/dist-packages LD_LIBRARY_PATH=$foo/lib` . I couldn't find this documented anywhere, should it be?

**Comment by rouault** [comment]
> When compiling gdal with `--prefix=$foo` the tests should be ran with `PYTHONPATH=$foo/lib/python3/dist-packages LD_LIBRARY_PATH=$foo/lib` . I couldn't find this documented anywhere, should it be?

doc/source/contributing/developer.rst suggests to use ``. scripts/setdevenv.sh`` (it might pick the wrong python version if you have both python and python3 in your path though), which avoids to run "make install" when developing.

**Pull request merged**
