### PR TITLE
Adds HTTP Basic authentication support 9917

### PR DESCRIPTION
**Pull request by kristopolous**
Uses the CURLOPT_USERNAME and CURLOPT_PASSWORD options. Includes updating of the documentation accordingly.
This is in reference to #9917 

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by rouault** [comment]
Isn't that a bit redundant with the exiting GDAL_HTTP_USERPWD ? And that you can include in the URL in the standard way ``/vsicurl/https://my_user:my_passwd@example.com/...`

**Comment by kristopolous** [comment]
That failed to work for me which is why I wrote this. 

Maybe it's a libcurl difference. I'll be happy to investigate that further

**Comment by rouault** [comment]
There are a few code formatting issues:
```
 pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
```

See also https://gdal.org/development/dev_practices.html#commit-hooks

**Comment by kristopolous** [comment]
Thanks very much.  I want to find out whether this is genuinely needed or just an oversight on my part. If I can build a reproducible case then I will gladly go through the process. 

I don't want to waste your time or add in unnecessary code.

**Pull request closed without merging**
