### PR TITLE
Add -stats and -approx_stats options to gdal_edit.py

### PR DESCRIPTION
**Pull request by mwtoews**
See https://trac.osgeo.org/gdal/ticket/5805

### CODE REVIEW

**Comment by rouault** [comment]
The added test should return 'skip' if from osgeo import gdal_array returns an exception, as it depends on numpy and this is an optional component of the python bindings

**Comment by mwtoews** [comment]
I think this is ready to merge. Also note that I don't add any tests for `-approx_stats`, since I'm uncertain on what values will be approximated from such small raster. If one uses both flags, the later is effectively used.

**Comment by rouault** [comment]
Please rebase on latest head. This does not cleanly apply

**Comment by mwtoews** [comment]
It's ready to be merged to trunk.

I also just found a bug with `-unsetstats`, so expect another PR after this one.

**Comment by rouault** [comment]
For reasons I do not understand, likely due to git-svn oddities, I still don't manage to merge your changes neither with "git pull https://github.com/mwtoews/gdal stats" nor with "git am 46.patch" or "git apply 46.patch"... It appears that the 46.patch (got from https://github.com/OSGeo/gdal/pull/46.patch) does not contain the recently added unsetmd option.
Could you do a rebase on an updated trunk instead of a merge, or provide a patch against svn ?

**Comment by mwtoews** [comment]
There's a great deal of git that I don't understand either. I'll pass a patch for SVN on Trac.

**Comment by rouault** [comment]
I think I know what might go wrong. I should likely apply your changes ontop of the git-svn'ed local copy that is pushed to OSGeo/gdal, but as this is updated regularly by a cron job I don't want to mess it up. Instead I've another git-svn'ed repository that follows the same update process rules, but I can update manually. The issue seems to be that the git commit numbers are not be the same even if the content is identical... But yes a svn patch will better work

**Comment by mwtoews** [comment]
Patched from SVN https://trac.osgeo.org/gdal/ticket/5805

**Pull request closed without merging**
