### PR TITLE
Vagrant: fix geos mingw package dependency problem

### LINKED ISSUE #1058: gdalinfo crash on vagrant box
## Expected behavior and actual behavior.

On a newly provisioned clean vagrant box, gdalinfo crashes with some of the test data, causing some tests to fail.

```
vagrant@gdal-vagrant:/vagrant/autotest$ gdalinfo gcore/data/byte.tif
Driver: GTiff/GeoTIFF
Files: gcore/data/byte.tif
Size is 20, 20
Coordinate System is:
PROJCS["NAD27 / UTM zone 11N",
    GEOGCS["NAD27",
        DATUM["North_American_Datum_1927",
            SPHEROID["Clarke 1866",6378206.4,294.9786982138982,
                AUTHORITY["EPSG","7008"]],
            AUTHORITY["EPSG","6267"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4267"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-117],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","26711"]]
Origin = (440720.000000000000000,3751320.000000000000000)
Pixel Size = (60.000000000000000,-60.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  440720.000, 3751320.000) (117d38'28.21"W, 33d54' 8.47"N)
Lower Left  (  440720.000, 3750120.000) (117d38'27.92"W, 33d53'29.51"N)
Upper Right (  441920.000, 3751320.000) (117d37'41.48"W, 33d54' 8.71"N)
Lower Right (  441920.000, 3750120.000) (117d37'41.20"W, 33d53'29.75"N)
Center      (  441320.000, 3750720.000) (117d38' 4.70"W, 33d53'49.11"N)
*** Error in `gdalinfo': free(): invalid pointer: 0x0000000001d37170 ***
Aborted (core dumped)
```

gdb gives this trace:

```
(gdb) bt
#0  0x00007ffff52c4c37 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff52c8028 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff53012a4 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff530d82e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007fffe31611f3 in pj_free () from /usr/lib/x86_64-linux-gnu/libproj.so
#5  0x00007ffff74aab78 in OGRProj4CT::~OGRProj4CT (this=0x6e2210, __in_chrg=<optimized out>) at ogrct.cpp:594
#6  0x00007ffff74aacc4 in OGRProj4CT::~OGRProj4CT (this=0x6e2210, __in_chrg=<optimized out>) at ogrct.cpp:620
#7  0x00007ffff74aa778 in OCTDestroyCoordinateTransformation (hCT=0x6e2210) at ogrct.cpp:443
#8  0x00007ffff6db978e in GDALInfo (hDataset=0x6ddec0, psOptions=0x6db630) at gdalinfo_lib.cpp:703
#9  0x000000000040178a in main (argc=2, argv=0x6db560) at gdalinfo_bin.cpp:213
```

## Steps to reproduce the problem.

* `vagrant up`
* `cd /vagrant/autotest/ ; gdalinfo gcore/data/byte.tif`

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

master @ 03663aa9cc098380fe5420faa4f424c3dac45a08

### PR DESCRIPTION
**Pull request by miurahr**
## What does this PR do?

resolve all the problem related to ubuntu PPA
Fix #1058 by removing root cause for dependency 
breakage of packages.

Signed-off-by: Hiroshi Miura <miurahr@linux.com>

## What is a root cause?
Ubuntugis-unstable PPA has a geos 3.5.0 package for trusty.
There are dependency chain for libgeos related to rasterlite. librasterlite depends on opensceangraph, which depends on gdal1h, that depends on libgeos 3.4.2.
Ubuntu Trusty has a geos 3.4.2 in standard release.

Similar things are happen on proj4 package. Multiple proj4 library versions causes crash, that is reported in #1058 

https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

This patch removes ubuntugis-unstable PPA from apt repository, in order not to install geos 3.5.0.

## What are related issues/pull requests?

#1058 

## Tasklist

 - [ ] Fix test errors
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Vagrant

### CODE REVIEW

**Comment by miurahr** [comment]
with this setup of vagrant environment, autotest resulted
```
.Results (873.10s):
    5505 passed
      10 failed
         - ogr/ogr_csv.py:1036 test_ogr_csv_29
         - ogr/ogr_gft.py:64 test_ogr_gft_read
         - ogr/ogr_gpkg.py:1218 test_ogr_gpkg_18
         - gcore/tiff_srs.py:106 test_tiff_srs_weird_mercator_2sp
         - gcore/tiff_srs.py:437 test_tiff_srs[2066-0]
         - gcore/tiff_srs.py:437 test_tiff_srs[2057-0]
         - gcore/tiff_srs.py:437 test_tiff_srs[2056-0]
         - gcore/tiff_srs.py:437 test_tiff_srs[3994-0]
         - gcore/tiff_write.py:3039 test_tiff_write_87
         - gdrivers/loslas.py:40 test_loslas_online_1
       4 xfailed
     832 skipped
```

**Comment by rouault** [comment]
Are those test failures new with your changes ?

**Comment by miurahr** [comment]
> Are those test failures new with your changes ?

Yes, all test are passed in previous Vagrant configuration that use ubuntugis-unstable PPA (incl. geos-3.5).
I'd like to investigate it to know a root cause of issues.

**Comment by miurahr** [comment]
I found these fails are not new after an investigation. I'd like to ask to merge it.

**Pull request merged**
