### PR TITLE
Docs: Fix typos on virtual_file_systems.rst

### PR DESCRIPTION
**Pull request by jomey**
Fix typos in `virtual_file_systems.rst` listing Google Cloud Storage authentication options.

### CODE REVIEW

**Comment by mloskot** [comment]
Thank you for the fix!

**Comment by jomey** [comment]
I need to tell my OS X dictionary that GDAL is an actual word ;-)

**Comment by mloskot** [comment]
@jomey In fact, I can edit the commit message myself with squash. Sorry to bother you.

**Comment by mloskot** [comment]
Thank you

**Pull request merged**
