### PR TITLE
Implement /vsiwebhdfs for WebHDFS REST API

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
@jamesmcclain This might be of interest for you. 
I've tested this against a Docker image at https://github.com/sequenceiq/hadoop-docker . I've not implemented authentication with Kerberos SPNEGO as this is not enabled in this image and I've no idea how to setup that. If you've pointers how to test such setup, I'd be interested.

**Comment by jamesmcclain** [comment]
> I've not implemented authentication with Kerberos SPNEGO as this is not enabled in this image and I've no idea how to setup that.

I have no specific  experience with that, but one good resource might be [geodocker](https://github.com/geodocker).  I have opened up a discussion about this question in their [gitter room](https://gitter.im/geodocker/geodocker).

**Comment by rouault** [comment]
OK, thanks for the hint.

**Comment by jamesmcclain** [comment]
I see that the PR is already in, but for future reference, it looks like the [Cloudera image](https://www.cloudera.com/documentation/enterprise/5-5-x/topics/quickstart_docker_container.html) might have the necessary bits.  There is a little bit more context in the Gitter chat regarding getting it setup.

**Pull request merged**
