### PR TITLE
Adding tests for mira mon vector driver

### PR DESCRIPTION
**Pull request by AbelPau**
## What does this PR do?
MiraMonVector: fix wrong use of number of records in string lists for field values
MiraMonVector: fix wrong word Lower instead of Lowest in metadata OpenOptionList
MiraMonVector: add new writing tests and improves the existing ones

## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [x] Add test case(s)
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by rouault** [comment]
@abelpau I'm closing that one again. The git history is completely messed up. Probably by uses of git merge instead of git rebase. I've redone it in https://github.com/OSGeo/gdal/pull/9734 by checking out your branch, saving modified & added files, and reapplying them on top of a branch based on master. Please check I've not messed up things. I've also slightly modified test_ogr_miramon_corrupted_files() to use more idiomatic pytest.raises()

**Comment by AbelPau** [comment]
> @AbelPau I'm closing that one again. The git history is completely messed up. Probably by uses of git merge instead of git rebase. I've redone it in #9734 by checking out your branch, saving modified & added files, and reapplying them on top of a branch based on master. Please check I've not messed up things. I've also slightly modified test_ogr_miramon_corrupted_files() to use more idiomatic pytest.raises()

All seems correct but tests fails because of "Exception: Attempting to run tests for GDAL 3.10.0 but library version is 3.9.0beta1. Do you need to run setdevenv.sh ?"

There is something I've done wrong?

**Comment by rouault** [comment]
> There is something I've done wrong?

you probably need to do a full rebuild as you may have a build whose parts have been built on the 3.9 branch and other parts on master

**Comment by AbelPau** [comment]
> > There is something I've done wrong?
> 
> you probably need to do a full rebuild as you may have a build whose parts have been built on the 3.9 branch and other parts on master

But I am talking about the tests in actions. But I am building again, also necessary

**Comment by rouault** [comment]
> But I am talking about the tests in actions.

ah, in those pull requests that I've closed ? Well, as they have picked up some commits changing the version numbers, potentially only partially, they are in a messed up state. https://github.com/OSGeo/gdal/pull/9734 should be fine

**Pull request closed without merging**
