### PR TITLE
Sentinel2 additional metadata

### PR DESCRIPTION
**Pull request by tombieli**
## What does this PR do?
Adds ability for sentinel2 driver to read band relevant metadata:
- `RADIO_ADD_OFFSET` for Level 1C
- `BOA_ADD_OFFSET` for Level 2A

Those metadata parameters were added for processing baselines 4.0 and later. Mentioned offsets are important for calculating TOA/BOA reflectance.

## What are related issues/pull requests?
This PR partially satisfies issue #5169.

## Tasklist

 - [x] Add test case(s)
 - [ ] Add documentation
 - N/A Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
  * WSL Ubuntu 20.04.3 LTS
  * Docker image: ghcr.io/osgeo/gdal-deps:ubuntu20.04-master
* Compiler: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0

### CODE REVIEW

**Comment by rouault** [comment]
Hi. Thank you for your contribution. My main concern is related to the size of the test datasets. The size of this pull request as a patch (https://github.com/OSGeo/gdal/pull/8379.patch) is 44 MB, whereas the existing gdalautotest suite in its whole is 68 MB. I remember having spent a significant time during the initial development of the driver to reduce the test datasets by removing files unused by the driver, removing unused content in files used by the driver, replacing the JPEG2000 content by sparse GeoTIFF files (typically can be done with "gdal_create -if source.jp2 out.tif -co sparse_ok=yes"), etc.  Can a similar effort be made here?
QI_DATA, AUX_DATA, HTML are obvious candidates for removal / strong content removal.
Or couldn't manually adding the new metadata in existing test files be a solution (or perhaps taking the existing datasets as the source to derive datasets with the changes of baseline 4.0 ?)

**Comment by rouault** [comment]
some formatting issues. See https://gdal.org/development/dev_practices.html#commit-hooks how to set-up the automatic linters & code-reformatting

**Comment by tombieli** [comment]
@rouault :
I've fixed code formatting, so linking tests should pass.

I have also stripped fake data using your recommendations. The major volume of those data were the xml files that contained some constellation/satellite specific data about its whole operation. I deleted those files. 

Probably, raster data could be shrinked more using JPEG2000 driver. I achieved this for level 1C rasters. If this is necessary, I can try to reproduce the shrinking process on level 2A data.

**Comment by rouault** [comment]
> @rouault : I've fixed code formatting, so linking tests should pass.
> 
> I have also stripped fake data using your recommendations. The major volume of those data were the xml files that contained some constellation/satellite specific data about its whole operation. I deleted those files.
> 
> Probably, raster data could be shrinked more using JPEG2000 driver. I achieved this for level 1C rasters. If this is necessary, I can try to reproduce the shrinking process on level 2A data.

I've added a further commit to do that and further reduce L1C GeoTIFF by making them single blocks (using -co BLOCKYSIZE=100000). I've also removed the content of <Tile_Angles> from fake_l1c_processing_baseline_5_09/S2B_MSIL1C_20230823T095559_N0509_R122_T34UCF_20230823T120234.SAFE/GRANULE/L1C_T34UCF_A033753_20230823T095553/MTD_TL.xml

**Pull request merged**
