### PR TITLE
A few minor changes to the updation of libpng - added makefile.vc and libpng_gdal.patch, removed test files used by standalone png

### PR DESCRIPTION
**Pull request by foowhiz**

### CODE REVIEW

**Comment by rouault** [comment]
It doesn't look like the arm/ subdirectory is needed.
And the libpng_gdal.patch file should be applied to the libpng, with changes, since at first sight, there have been changes. See the line in the previous README (that should be kept) :
"GDAL changes (stored in libpng_gdal.patch)
------------

* Make screwy MSPaint "zero chunks" only a warning, not error. See r18808 and #3416
"
Should be tested with the PNG file attached in the ticket.

**Comment by Raeburn1687** [comment]
The readme said that the arm folder has optimised code for the arm architecture. I do not know much about this, but I'm guessing that GDAL is not used much on arm? Even so, there have been queries regarding running GDAL on Raspberry Pi, which is arm based.[http://gis.stackexchange.com/questions/116320/how-to-install-gdal-and-qgis-on-a-raspberry-pi](url)

About libpng_gdal.patch : 
I will make the necessary changes for "invalid chunk type", but so far I haven't been able to locate the code for "unknown critical chunk". The statement has changed most probably, so I will have another go at it. I'll test with the PNG file specified in the ticket.

**Comment by rouault** [comment]
I meant the arm/ subfolder might be nice to have, but currently the code in it isn't referenced by any makefile, unless I missed something, so it is useless. And it would probably be a pain to build it due to the presence of assembly.

**Comment by Raeburn1687** [comment]
I see. So should I remove it completely?

**Comment by rouault** [comment]
Yes, no need to let uncompiled code

**Comment by Raeburn1687** [comment]
Got it, I'll remove it.

**Comment by Raeburn1687** [comment]
I tried to read the PNG image in the trac ticket using GDAL-2.0.2 as well as GDAL trunk version, but I am still getting the error : "Invalid chunk type", even though the file pngrutil.c has set this as a warning, not error.
I am unable to figure out what might be causing this. Do you know of any possible reasons?

**Comment by rouault** [comment]
Are you sure your GDAL is compiled with internal libpng ? With my trunk build :
```
$ gdalinfo fme_l_blue_twitter_3.png
Warning 1: libpng: [00][00][00][00]: invalid chunk type
Warning 1: libpng: [00][00][00][00]: unknown critical chunk
Driver: PNG/Portable Network Graphics
Files: fme_l_blue_twitter_3.png
Size is 1562, 1160
Coordinate System is `'
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 1160.0)
Upper Right ( 1562.0,    0.0)
Lower Right ( 1562.0, 1160.0)
Center      (  781.0,  580.0)
Band 1 Block=1562x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=1562x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=1562x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=1562x1 Type=Byte, ColorInterp=Alpha
```

**Comment by Raeburn1687** [comment]
@rouault Okay, so finally I have been able to change the error to warning and compile the code properly(Some problem with my computer).
Also, I added pngdebug.h because it was called by pngpriv.h.
Finally, I have changed the file libpng_gdal.patch to show the error to warning changes for version 1.6.21, which can be used for future updates.

**Pull request closed without merging**
