### PR TITLE
SXF: Expose 'config options' to 'open options list' for convenience

### PR DESCRIPTION
**Pull request by drons**

### CODE REVIEW

**Comment by rouault** [comment]
Test fails on gcc52_stdcpp14_sanitize Travis CI configuration: https://api.travis-ci.com/v3/job/203431592/log.txt
```

=================================== FAILURES ===================================
________________________________ test_ogr_sxf_4 ________________________________

    def test_ogr_sxf_4():
    
        lyr_names = ['Ð¡Ð˜Ð¡Ð¢Ð•ÐœÐÐ«Ð™',
                     'Ð’ÐžÐ”ÐÐ«Ð• ÐžÐ‘ÐªÐ•ÐšÐ¢Ð«',
                     'ÐÐÐ¡Ð•Ð›Ð•ÐÐÐ«Ð• ÐŸÐ£ÐÐšÐ¢Ð«',
                     'Ð˜ÐÐ¤Ð ÐÐ¡Ð¢Ð Ð£ÐšÐ¢Ð£Ð Ð',
                     'Ð—Ð•ÐœÐ›Ð•ÐŸÐžÐ›Ð¬Ð—ÐžÐ’ÐÐÐ˜Ð•',
                     'Ð Ð•Ð›Ð¬Ð•Ð¤ Ð¡Ð£Ð¨Ð˜',
                     'Ð“Ð˜Ð”Ð ÐžÐ“Ð ÐÐ¤Ð˜Ð¯ (Ð Ð•Ð›Ð¬Ð•Ð¤)',
                     'ÐœÐÐ¢Ð•ÐœÐÐ¢Ð˜Ð§Ð•Ð¡ÐšÐÐ¯ ÐžÐ¡ÐÐžÐ’Ð',
                     'Not_Classified']
        sxf_name = 'data/100_test.sxf'
        sxf_ds = gdal.OpenEx(sxf_name, gdal.OF_VECTOR, open_options=['SXF_LAYER_FULLNAME=YES'])
    
        assert sxf_ds is not None
        for layer_n in range(sxf_ds.GetLayerCount()):
            lyr = sxf_ds.GetLayer(layer_n)
>           assert lyr_names[layer_n] == lyr.GetName()
E           AssertionError: assert '\xd0\xa1\xd0...0\xab\xd0\x99' == '\xc3\x91\xc3\...3\x9b\xc3\x89'
E             - \xd0\xa1\xd0\x98\xd0\xa1\xd0\xa2\xd0\x95\xd0\x9c\xd0\x9d\xd0\xab\xd0\x99
E             + \xc3\x91\xc3\x88\xc3\x91\xc3\x92\xc3\x85\xc3\x8c\xc3\x8d\xc3\x9b\xc3\x89

ogr_sxf.py:106: AssertionError
----------------------------- Captured stderr call -----------------------------
```

**Comment by drons** [comment]
@rouault  I think that it is necessary to add function `TestUtf8Capability()` as it is done in Mitab driver (`IMapInfoFile::TestUtf8Capability()`) and check it in the test.

**Comment by drons** [comment]
@rouault
Maybe move `OGRSXFLayer::CanRecode` to the main library (cpl_recode.cpp)? It is required in several drivers (mitab, shape, sxf).

**Comment by rouault** [comment]
> Maybe move `OGRSXFLayer::CanRecode` to the main library (cpl_recode.cpp)?

yes that would make sense

**Comment by drons** [comment]
I think it's done. Any suggestions?

**Comment by rouault** [comment]
To simplify history a bit, could you possibly fold the 'SXF: Added more debug output to test ' and 'SXF: Fix test run with python3' commits in the original commit where the test was added  ?

**Comment by drons** [comment]
Thanks!

**Pull request merged**
