### PR TITLE
configure.ac: Configure proj dependencies before proj (master)

### PR DESCRIPTION
**Pull request by david-sinuela-pix4d**
## What does this PR do?

Change the order of checks in configure.ac so that by the time the checks for proj are performed the dependencies of proj are already in LIBS. With this approach it is sure that the libraries provided to configure through the `--with-*` flags are also used in the attempt to link with proj.

I am aware of `--with-proj-extra-lib-for-test` in 3.1 but I thought that this approach would lead to less repetition in the call to `configure` and be more consistent.

## What are related issues/pull requests?

Addresses #2511.

## Tasklist

 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

Evidently I have not tested all possible combinations, does the CI cover enough cases to be confident about the change?

## Environment

Same as described in #2511.

## Other notes

There is a similar PR for master in https://github.com/OSGeo/gdal/pull/2513

### CODE REVIEW

**Comment by rouault** [comment]
Would you mind running "autoconf" and commit the modified ``configure`` as well ?

**Comment by david-sinuela-pix4d** [comment]
> Would you mind running "autoconf" and commit the modified `configure` as well ?

Done.

It also updated aclocal.m4 but there are some suspicious version changes in the diff:

```
diff --git a/gdal/aclocal.m4 b/gdal/aclocal.m4
index be5bff6b0f..ca7743bb04 100644
--- a/gdal/aclocal.m4
+++ b/gdal/aclocal.m4
@@ -1,6 +1,6 @@
-# generated automatically by aclocal 1.16.1 -*- Autoconf -*-
+# generated automatically by aclocal 1.16.2 -*- Autoconf -*-

-# Copyright (C) 1996-2018 Free Software Foundation, Inc.
+# Copyright (C) 1996-2020 Free Software Foundation, Inc.

 # This file is free software; the Free Software Foundation
 # gives unlimited permission to copy and/or distribute it,
@@ -12,46 +12,8 @@
 # PARTICULAR PURPOSE.

 m4_ifndef([AC_CONFIG_MACRO_DIRS], [m4_defun([_AM_CONFIG_MACRO_DIRS], [])m4_defun([AC_CONFIG_MACRO_DIRS], [_AM_CONFIG_MACRO_DIRS($@)])])
-# ===========================================================================
-#    https://www.gnu.org/software/autoconf-archive/ax_require_defined.html
-# ===========================================================================
-#
-# SYNOPSIS
-#
-#   AX_REQUIRE_DEFINED(MACRO)
-#
-# DESCRIPTION
-#
-#   AX_REQUIRE_DEFINED is a simple helper for making sure other macros have
-#   been defined and thus are available for use.  This avoids random issues
-#   where a macro isn't expanded.  Instead the configure script emits a
-#   non-fatal:
-#
-#     ./configure: line 1673: AX_CFLAGS_WARN_ALL: command not found
-#
-#   It's like AC_REQUIRE except it doesn't expand the required macro.
-#
-#   Here's an example:
-#
-#     AX_REQUIRE_DEFINED([AX_CHECK_LINK_FLAG])
-#
-# LICENSE
-#
-#   Copyright (c) 2014 Mike Frysinger <vapier@gentoo.org>
-#
-#   Copying and distribution of this file, with or without modification, are
-#   permitted in any medium without royalty provided the copyright notice
-#   and this notice are preserved. This file is offered as-is, without any
-#   warranty.
-
-#serial 2
-
-AC_DEFUN([AX_REQUIRE_DEFINED], [dnl
-  m4_ifndef([$1], [m4_fatal([macro ]$1[ is not defined; is a m4 file missing?])])
-])dnl AX_REQUIRE_DEFINED
-
-# pkg.m4 - Macros to locate and utilize pkg-config.   -*- Autoconf -*-
-# serial 12 (pkg-config-0.29.2)
+# pkg.m4 - Macros to locate and utilise pkg-config.   -*- Autoconf -*-
+# serial 11 (pkg-config-0.29.1)

 dnl Copyright © 2004 Scott James Remnant <scott@netsplit.com>.
 dnl Copyright © 2012-2015 Dan Nicholson <dbn.lists@gmail.com>
@@ -93,7 +55,7 @@ dnl
 dnl See the "Since" comment for each macro you use to see what version
 dnl of the macros you require.
 m4_defun([PKG_PREREQ],
-[m4_define([PKG_MACROS_VERSION], [0.29.2])
+[m4_define([PKG_MACROS_VERSION], [0.29.1])
 m4_if(m4_version_compare(PKG_MACROS_VERSION, [$1]), -1,
     [m4_fatal([pkg.m4 version $1 or higher is required but ]PKG_MACROS_VERSION[ found])])
 ])dnl PKG_PREREQ
```

Should I upload it too?

**Comment by rouault** [comment]
> Should I upload it too?

no that shouldn't be necessary

**Comment by david-sinuela-pix4d** [comment]
The CI shows that some tests fail on some configurations:

* test_ogr_mvt_write_mbtiles
* test_ogr_mvt_write_limitations_max_size
* test_ogr_mvt_write_polygon_repaired
* test_ogr_mvt_write_conflicting_innner_ring
* test_ogr_mvt_write_limitations_max_size_polygon
* test_ogr_mvt_write_limitations_max_features

I will check but I am not sure if I will be able to debug this without deep knowledge on the library. I would appreciate any hint.

Some interesting messages from the log:

```
ogr/ogr_mvt.py::test_ogr_mvt_write_mbtiles ERROR 1: Cannot guess driver for /vsimem/out.mbtiles
FAILED
ogr/ogr_mvt.py::test_ogr_mvt_write_limitations_max_size ERROR 1: Cannot guess driver for /vsimem/out.mbtiles
FAILED
ogr/ogr_mvt.py::test_ogr_mvt_write_polygon_repaired ERROR 1: Cannot guess driver for /vsimem/out.mbtiles
FAILED
ogr/ogr_mvt.py::test_ogr_mvt_write_conflicting_innner_ring ERROR 1: Cannot guess driver for /vsimem/out.mbtiles
FAILED
ogr/ogr_mvt.py::test_ogr_mvt_write_limitations_max_size_polygon ERROR 1: Cannot guess driver for /vsimem/out.mbtiles
FAILED
```

**Comment by rouault** [comment]
> fail on some configurations:

Those failures are due to the MBTiles driver not being available. This driver is normally enabled if AC_DEFUN([SQLITE_FORMATS],[rasterlite mbtiles])dnl
In the log I can also that the rasterlite tests are skipped. As well as the gpkg ones related to AC_DEFUN([SQLITE_DRIVERS],[gpkg vfk osm])dnl

**Comment by david-sinuela-pix4d** [comment]
I pushed a fix for the tests, this is ready for review.

**Pull request merged**
