### PR TITLE
Yell when people use unsupported build systems

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by mloskot** [comment]
Because? (i.e. reference to any issues, for those curious :-))

**Comment by rouault** [comment]
> Because? (i.e. reference to any issues, for those curious :-))

I don't want to pinpoint at anyone, but following latest discussions on the mailing list should give a hint :-)

**Comment by mloskot** [comment]
That is a good reference :-)

**Comment by schwehr** [comment]
I love using bazel...

**Comment by rouault** [comment]
Dropping that...

**Pull request closed without merging**
