### PR TITLE
Support for writable Spatialite Views

### PR DESCRIPTION
**Pull request by mj10777**
Should now be getting near to an acceptable form.

### CODE REVIEW

**Comment by rouault** [comment]
I would like to comment inline in ogrsqliteeditablelayer.cpp but that doesn't seem possible.

*  As I said already I think, the OGRSQLiteEditableLayer::TestCapability() should be implemented in OGRSQLiteTableLayer() and OGRSQLiteViewLayer() separately. The if (IsViewLayer()) is ugly
*  For clarity, all the methods related to field creation/deletion/etc.. should likely be in OGRSQLiteTableLayer only
* RunDeferredCreationIfNecessary() and CreateSpatialIndexIfNecessary() too. That would save the if (!IsTableLayer()) test

**Comment by mj10777** [comment]
Try going into, maybe there it is possible:

https://github.com/OSGeo/gdal/compare/trunk...mj10777:trunk

--
>> For clarity, all the methods related to field creation/deletion/etc.. should likely be in OGRSQLiteTableLayer only

which would mean that the code would have to be repeated in OGRSQLiteViewLayer
* the goal was to get rid of the common code being done twice

--
RunDeferredCreationIfNecessary() and CreateSpatialIndexIfNecessary() too. That would save the if (!IsTableLayer()) test

and all the functions that call it would have to be repeated in OGRSQLiteViewLayer
* again, the goal was to get rid of the common code being done twice

I tried your very first suggestion, which was based on this idea
* with the result that 90% of everything had to be repeated
   * and then it never worked correctly

This solution works
* I have been using it for that last year

**Comment by rouault** [comment]
> the goal was to get rid of the common code being done twice
This is not common code... since it is only used by the TableLayer. So it should be there. This should be just a matter of moving the method declaration and definition in the TableLayer class and not defining them at all in the EditableLayer

**Comment by mj10777** [comment]
But RunDeferredCreationIfNecessary is being called 6 time
* all of those functions must the also be repeated
   * and sometime they call other functions
      * that then also be ...

that was the problem.

**Comment by rouault** [comment]
> But RunDeferredCreationIfNecessary is being called 6 time

Why not make it a virtual method in the EditableLayer class with an empty implementation and put the real implementation in TableLayer ?

**Comment by mj10777** [comment]
When a SpatialView is full editable
* it is the same as SpatialTable
   * often portion even have to call the real table

The problem was, once inside OGRSQLiteTableLayer or OGRSQLiteViewLayer
* it was hard to get it back to OGRSQLiteEditableLayer

-- break --
just reread the message again
* yes that could be done for the functions that have
    if (!IsTableLayer())
     return OGRERR_NONE;

But for the portions using
* if ((IsViewLayer()) && (!bTrigger*)) 
   * which means: when **read** only: abort
* GetGeometryTable()
   * which, where needed, replaces the view-name with the underline table-name

should remain as is.

**Comment by mj10777** [comment]
But splitting that up into OGRSQLiteTableLayer
* would be splitting just 3 functions to another files/class
   * for maintaining, that would be cumbersome

To keep everything centralized in one file
* might be wiser

**Comment by mj10777** [comment]
The 3 Table specific have been made into virtual functions
* and implemented only in OGRSQLiteTableLayer
   * with the `(!IsTableLayer())` removed

    // Table specific functions
    virtual void        CreateSpatialIndexIfNecessary() {return;};
    virtual int         CreateSpatialIndex(CPL_UNUSED int iGeomCol) {return OGRERR_NONE;};
    virtual OGRErr      RunDeferredCreationIfNecessary() {return OGRERR_NONE;};

---
In the beginning, I placed more checks that were really needed
* to insure that things only ran under certain conditions

When working on `OGRSQLiteEditableLayer::Initialize`
* the goal was that it would receive and check the validity of the LayerType
   * returning `CE_Failure` if **not** valid
(I have added a fuller explanation of this in the function-header comment)

So the extra check inside `IsViewLayer()`
* are **not** needed
   * replacing it with 
      * `virtual int  IsViewLayer() { return TRUE; };`

---
Just ran the `ogr_sqlite.py` script
* and am receiving a lot of errors
   * so will be looking into that today

**Pull request closed without merging**
