### PR TITLE
OSRPJContextHolder: call pthread_atfork() once for the process

### PR DESCRIPTION
**Pull request by rouault**
Cf https://lists.osgeo.org/pipermail/gdal-dev/2023-December/058058.html

### CODE REVIEW

**Comment by carsten-schultz-pix4d** [comment]
Thank you for this. Do you also plan to re-enable this for Macs?

Regarding the second point that I had brought up in my email, I agree that it is probably not of practical relevance. It wasn't specifically about having multiple threads though but about having multiple instances of `OSRPJContextHolder` in any way. If the only instances are the thread_local ones defined here and if we assume that no-one is foolish enough to mix threads and forks, then it will be okay. Nevertheless I would have preferred to not have a bool flag but just a counter that is increased and that could be handled in the same way as the pid in the `!defines(HAVE_PTHREAD_ATFORK)` code.

So, thanks again.

**Comment by rouault** [comment]
> Do you also plan to re-enable this for Macs?

I'm not sure this was the root cause of https://github.com/OSGeo/gdal/issues/8497 . As I can't test it directly to check, I prefer to not change that.

**Comment by carsten-schultz-pix4d** [comment]
> I'm not sure this was the root cause of #8497 . As I can't test it directly to check, I prefer to not change that.

That makes sense. If I can figure out how to use the Python bindings then I will test that. Given that I see the number 164 in the report and that the limit for calls to `pthread_atfork` on x86_64 is 170, I am quite confident that it is at least related. Unfortunately the limit is higher on ARM, which will make it harder to test. (And I will *not* try to get an x86_64 Python running on my machine ;) )

**Comment by rouault** [comment]
@emlys Would you be willing to test this pull request, somewhat related to #8497 you created some time ago, and disable the ``#undef HAVE_PTHREAD_ATFORK`` at line 43 of ogr_proj_p.cpp ( https://github.com/OSGeo/gdal/pull/8909/files#diff-c516e8cff204f7f45759b9972d20b8ae8113468623a1c0c594d339e7bcf9055aR43  ) on top of this to PR ? Cf above comment https://github.com/OSGeo/gdal/pull/8909#issuecomment-1839196582 that explains it is likely that the fix of this PR obsoletes the ``#undef HAVE_PTHREAD_ATFORK``  trick added in https://github.com/OSGeo/gdal/pull/8524

**Comment by carsten-schultz-pix4d** [comment]
Okay, this is what I tested.

I started at v3.6.4, because that's where I happen to still be. I built with Python bindings, set all of the necessary paths....
I tested `test.py` from https://github.com/OSGeo/gdal/issues/8497. As expected, on my machine the number of iterations for which it started to fail was a bit below `16 * 1024 // 24`. (Indeed at `-7`, with the kind of failure depending on the exact value, segfault, bus error, not producing the final output.)

I then cherry-picked the commit from this PR, and tested the same. Works, problem fixed.

**Pull request merged**
