### PR TITLE
STACTA: use STAC Raster extension to get number of bands, their data type, nodata value, scale/offset, units, and avoid fetching a metatile

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by thomas-maschler** [comment]
It would be good to consider band-related changes in the upcoming STAC specification 1.1.
Ideally, you could directly implement against it, and for backward compatibility also check eo/raster bands.

https://github.com/radiantearth/stac-spec/pull/1254
https://github.com/stac-extensions/raster/issues/42
https://github.com/stac-extensions/eo/pull/29

Please see discussion https://github.com/radiantearth/stac-spec/discussions/1213 for more context.

**Comment by thomas-maschler** [comment]
I added a ticket for support for internal tiles here: https://github.com/stac-extensions/raster/issues/43

**Comment by rouault** [comment]
> It would be good to consider band-related changes in the upcoming STAC specification 1.1.

@thomas-maschler if I've well understood the changes, implemented per https://github.com/OSGeo/gdal/pull/8931/commits/c63a640c71ccd9c8348cad258677a01586c3211e

**Comment by m-mohr** [comment]
@rouault Some of the properties will get a raster prefix, but we don't have the PR up yet in raster. So an example band object will look like this:

```json
               {
                    "name": "B1",
                    "eo:common_name": "nir",
                    "data_type": "uint8",
                    "unit": "dn",
                    "nodata": 1,
                    "raster:scale": 10,
                    "raster:offset": 1.2,
                    "raster:bits_per_sample": 7
                }
```

Thank you for your work, Even.

**Comment by rouault** [comment]
The backport to `release/3.8` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 41a3c755de... STACTA: use STAC Raster extension to get number of bands, their data type, nodata value, scale/offset, units, and avoid fetching a metatile
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging frmts/stacta/stactadataset.cpp
CONFLICT (content): Merge conflict in frmts/stacta/stactadataset.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.8 release/3.8
# Navigate to the new working tree
cd .worktrees/backport-release/3.8
# Create a new branch
git switch --create backport-8931-to-release/3.8
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 41a3c755de91855cc1d650decf3e46e076698a43,bfbb48a44b2506919153b836b70178d0e6f0070f,6e02499c15b838ca41ed12319ea57b715866468d
# Push it to GitHub
git push --set-upstream origin backport-8931-to-release/3.8
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.8
```
Then, create a pull request where the `base` branch is `release/3.8` and the `compare`/`head` branch is `backport-8931-to-release/3.8`.

**Comment by rouault** [comment]
3.8 backport in https://github.com/OSGeo/gdal/pull/8961

**Pull request merged**
