### PR TITLE
Improvements to WCS driver

### PR DESCRIPTION
**Pull request by ajolma**
## What does this PR do?

Check error when getting capabilities. Do not add zero capabilities entry to cache. Correct action if global metadata file is missing. In metadata record only subdataset NAME and DESC. In v2 put dataset metadata to global domain.

## What are related issues/pull requests?

#515 #516

## Tasklist

 - [ ] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by ajolma** [comment]
I'm a still a bit unsure what to put into _DESC since GetCapabilies docs differ from version to version and it contains various things.

**Comment by rouault** [comment]
> I'm still a bit unsure what to put into _DESC since GetCapabilies docs differ from version to version and it contains various things.

That could be just the coverage name (+ every other parameters, in some human readable form, that are in the _NAME content in case you have several subdatasets with the same coverage name)

**Comment by rouault** [comment]
```
frmts/wcs/wcsdataset100.cpp:654,style,unreachableCode,Statements following return, break, continue, goto or throw will never be executed.
frmts/wcs/wcsdataset110.cpp:849,style,unreachableCode,Statements following return, break, continue, goto or throw will never be executed.
```

**Comment by ajolma** [comment]
Now the DESC is "label" in 1.0 and "Title" in 1.1 or 2.0, if it is available, otherwise the id. "label" is required, "Title" is not always included, its requiredness seems ambiguous (OGC 06-121r9 Figure 7 and Table 21 are in conflict)

**Comment by ajolma** [comment]
Whoa! Too soon, sorry. The SUBDATASETS was still in the subdataset metadata. Also much metadata was (and is) still missing -- it needs to be copied from Capabilities and CoverageDescription.

**Comment by ajolma** [comment]
And I hadn't even started to write tests. The check boxes was there for a purpose.

**Comment by rouault** [comment]
Ah sorry ... well, you can open a new PR with the follow up changes

**Pull request merged**
