### PR TITLE
gdal2tiles produces garbage tiles (#6174)

### PR DESCRIPTION
**Pull request by avyavkumar**
Reference to #6174 on https://trac.osgeo.org/gdal/ticket/6174. 
Couldn't update autotest/pyscripts/test_gdal2tiles.py because additional arguments are required after the script has launched.

### CODE REVIEW

**Comment by rouault** [comment]
This break the tests in autotest/pyscripts/test_gdal2tiles.py : https://s3.amazonaws.com/archive.travis-ci.org/jobs/98685932/log.txt

```
Running tests from pyscripts/test_gdal2tiles.py
  TEST: test_gdal2tiles_py_1 ... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

The build has been terminated
```

**Comment by avyavkumar** [comment]
The break in the third test, is it platform independent? I cannot say for certain if it is related to the files modified, because the break is detected after the tests have been evaluated.

```
Found libgdal we are running against : /usr/lib/libgdal.so.2.1.0
travis_time:end:0103f91a:start=1451236993949369972,finish=1451237001769175907,duration=7819805935
[0K
[32;1mThe command "LD_LIBRARY_PATH=$PWD python ogr_sqlite.py" exited with 0.[0m
travis_time:start:1ccb0b13
[0K$ cd ..
travis_time:end:1ccb0b13:start=1451237001773235826,finish=1451237001776502240,duration=3266414
[0K
[32;1mThe command "cd .." exited with 0.[0m

Done. Your build exited with 1.
```

**Comment by rouault** [comment]
Failures are reported when they occur, but that doesn't make the whole tests to abort immediatly. And they are summarized at the end. In your case the on the fly report is :
```
Running tests from pyscripts/test_gdal2tiles.py
  TEST: test_gdal2tiles_py_1 ... 25350
28185
6147
59026
fail
    line 57: wrong checksum for band 1
  TEST: test_gdal2tiles_py_2 ... 8130
10496
65274
63715
fail
    line 84: wrong checksum for band 1
```

**Comment by avyavkumar** [comment]
Hmm, when I ran the tests on my machine, the reported checksum values (in the test file) were the same as the output I got after running my copy of the changed python file. But in the Travis build they are different. Any thoughts?

**Comment by rouault** [comment]
Perhaps that on your machine you're not running your modified script ?

**Comment by avyavkumar** [comment]
Oh no, I most definitely am. I checked the test cases thrice before modifying the test_gdal2tiles script, as well as testing on a separate copy of gdal2tiles.

**Pull request closed without merging**
