### PR TITLE
netCDF: optimize IReadBlock() and CheckData() handling of partial blo…

### PR DESCRIPTION
**Pull request by jdemaria**
…cks in the x axis by re-using the GDAL block buffer instead of allocating a new temporary buffer for each block (#5950)

### CODE REVIEW

**Comment by jdemaria** [comment]
Close [(https://trac.osgeo.org/gdal/ticket/5950)]
Modified lines are now covered by autotest with my new unit test.

**Comment by jdemaria** [comment]
I see in the travis log:
**TEST: netcdf_60 ... 
('old = ', (1, 9, 5, 2.582))
('new = ', [1.0, 8.0, 4.5, 2.5])
fail**
I had also this problem on my side but it seems that the error was only in the associated GDAL PAM .aux.xml file and it worked when I removed it and the XML file was regenerated with expected statistics. Seems like the last pixel of the image was missing in statistics, maybe approximate stats? but in the test I check for non-approximate stats.
Any idea?

**Comment by jdemaria** [comment]
Maybe my problem is similar to [https://trac.osgeo.org/gdal/ticket/4244]

**Comment by jdemaria** [comment]
Tried gdal.SetConfigOption( 'GDAL_PAM_ENABLED', 'NO' ) in the test and remove the .aux.xml but still not work

**Comment by rouault** [comment]
Committed in r33493

**Pull request closed without merging**
