### PR TITLE
Fixed bug when reading corrupted RMF files

### PR DESCRIPTION
**Pull request by drons**
Fixed by multiple targeting:
* 666c945 - control overview search loop count
* a6b33b5, a4e8575 - check subheader signature

Commit a4e8575 may be redundant, but it allows us to drop out corrupted data at an early stage.

### CODE REVIEW

**Comment by rouault** [comment]
Thanks. Committed in https://trac.osgeo.org/gdal/changeset/40953 (with a bit of silencing of the warnings emitted during tests)

**Comment by drons** [comment]
Hello! @rouault 
I'm replace errors by warnings: 4788c2c2ce663045342dfbf1e96db6d3541636f4
Will you take changes from here or do I make a new pull request?

**Comment by rouault** [comment]
I've taken the commit as it. Pushed in r41035

**Comment by drons** [comment]
Thanks!

**Pull request closed without merging**
