### PR TITLE
Support for Requester Pays S3 buckets

### PR DESCRIPTION
**Pull request by mojodna**
To enable, set `AWS_REQUEST_PAYER=requester`

http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html

### CODE REVIEW

**Comment by rouault** [comment]
Can you document the new config option in the doc of VSIInstallS3FileHandler (port/cpl_vsil_curl.cpp) ?

**Comment by mojodna** [comment]
Done; thanks for the pointer to the existing docs.

**Comment by rouault** [comment]
I've committed your patch in trunk r37174 with a change in the tests that weren't really working well since the expected signature in webserver.py hadn't been updated.

**Comment by mojodna** [comment]
Ah, excellent. Thanks!!

**Pull request closed without merging**
