### PR TITLE
WFS filter: use double-quotes for PropertyIsLike attributes

### PR DESCRIPTION
**Pull request by aborruso**
Otherwise the output xml query have both double and single quotes https://lists.osgeo.org/pipermail/gdal-dev/2022-November/056480.html

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by jratike80** [comment]
I think that single quotes are just wrong. This example is from the "OpenGIS Filter Encoding Implementation Specification"
```
<Filter>
<PropertyIsLike wildCard="*" singleChar="#" escapeChar="!">
<PropertyName>LAST_NAME</PropertyName>
<Literal>JOHN*</Literal>
</PropertyIsLike>
</Filter>
```

**Comment by rouault** [comment]
> I think that single quotes are just wrong

no, they are not: cf https://stackoverflow.com/a/6800482 .

@aborruso  As I suspected, some unit tests should be adjusted. See the end of the output of https://github.com/OSGeo/gdal/actions/runs/3497336791/jobs/5856354519 . The file to edit is autotest/ogr/ogr_wfs.py . Are you able to add a commit with the needed changes ? I'll do it otherwise

**Comment by aborruso** [comment]
> I'll do it otherwise

It's better, thank you, but I looked at the file and I don't understand what to change

**Comment by aborruso** [comment]
Thank you very much @rouault and all you gdal folks

**Pull request merged**
