### PR TITLE
Support VerticalCS for DTED and SRTM drivers

### PR DESCRIPTION
**Pull request by hobu**
* The DTED driver should output EGM96 as the vertical coordinate system
* The SRTM driver should output EGM96 as the vertical coordinate system
* The DTED and SRTM drivers should use the ``REPORT_COMPD_CS`` configure option to allow vertical coordinate systems to be returned.

### CODE REVIEW

**Comment by hobu** [comment]
I think the tests are all passing now that this PR impacted, but there appears to be some tests still failing.

**Comment by rouault** [comment]
You get the same build failures as current master : https://travis-ci.org/OSGeo/gdal . Seems there's an issue with postgresql/postgis packages, and another specific issue in the mingw target.  So your changes are probably good to commits

**Comment by rouault** [comment]
@hobu Travis failures should be fixed with https://trac.osgeo.org/gdal/changeset/39964

**Comment by rouault** [comment]
@hobu Merged ???? Eh this is a mirror. The master is SVN ! You broke the mirror

**Comment by rouault** [comment]
@hobu I've force pushed back to the previous git commit to restore the mirror in a proper state.

Checkout svn, and apply the attached patch with patch -p1 < 558c5753e8c6247fe7cb6dbca562d4e6b1ad66da.patch and then svn commit
[558c5753e8c6247fe7cb6dbca562d4e6b1ad66da.patch.zip](https://github.com/OSGeo/gdal/files/1264605/558c5753e8c6247fe7cb6dbca562d4e6b1ad66da.patch.zip)

**Comment by rouault** [comment]
(the patch should be called e99a51373aa0892454ad7bd10387f9da4355b41a.patch . sorry, I wrongly picket up the sha of the previous git commit, but the content is the one of your work)

**Comment by rouault** [comment]
@hobu In case I wasn''t clear above: I just "reverted" your git commit in the github repo. Applying to SVN remains to do. (I can do it if you wish. Just thought you might want your name in the commit)

**Comment by hobu** [comment]
d'oh. sorry for breaking stuff.

**Comment by hobu** [comment]
> I can do it if you wish.

I would probably screw that up 😄 

Can we just switch to Github?

**Comment by rouault** [comment]
> I would probably screw that up :smile:

Committed in r39970

> Can we just switch to Github?

I'm not opposed to that. I guess we would probably have to move the Trac tickets to github too (not sure how we would handle the collision between old Trac tickets and corresponding numbers of existing github pull requests).

**Pull request merged**
