### PR TITLE
CMake: change way we discover PROJ to avoid prioritizing PROJ 9 and 8 (fixes #8942)

### LINKED ISSUE #8942: Cannot control what `proj` is used with GDAL
## Expected behavior and actual behavior.

`GDAL` cannot link against arbitrary `proj` versions and will use `proj9` over any other `proj >=6`, regardless of how the search paths for cmake are constructed.

Specifically:
1. The documentation suggests that an arbitrary proj location can be specified via these cmake variables `PROJ_INCLUDE_DIR` and `PROJ_LIBRARY_RELEASE`
https://gdal.org/development/building_from_source.html#proj
2. However, these appear to only be used when searching for `proj` in a non-`CONFIG` mode
https://github.com/OSGeo/gdal/blob/v3.8.0/cmake/modules/packages/FindPROJ.cmake#L37
which only seems to happen when looking for `proj6`
https://github.com/OSGeo/gdal/blob/v3.8.0/cmake/helpers/CheckDependentLibraries.cmake#L378
3. Otherwise, the proj find logic uses a `CONFIG` search, and prioritizes `proj9` and `proj8` 
https://github.com/OSGeo/gdal/blob/v3.8.0/cmake/helpers/CheckDependentLibraries.cmake#L371

Therefore, the outcome is that arbitrary versions of proj>=6 cannot be used. 
For example, in the context of library dependency management like `spack`, if `proj7` is first in the cmake search paths, `GDAL` will pass over it, and use `proj 9`. This is problematic if a system `proj9` is used (e.g., from homebrew or apt) instead of a custom-built `proj`.

Below is a `find_pacakge` debug  trace from cmake where I was expecting a custom-built `proj7.2.1` to be used and linked against. Instead, `GDAL` linked against homebrew's `proj9`. The path `/Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/lib/cmake/proj/proj-config.cmake` was manually confirmed as valid.

```
  find_package considered the following locations for PROJ's Config module:

    /var/folders/tr/v_kqwm7x25x3y68l_p5qh1gw0000gn/T/cmarsh/spack-stage/spack-stage-gdal-3.8.0-f5a2r5rexdlv74imgptmadls3caz5oyw/spack-src/CMakeFiles/pkgRedirects/PROJConfig.cmake
    /var/folders/tr/v_kqwm7x25x3y68l_p5qh1gw0000gn/T/cmarsh/spack-stage/spack-stage-gdal-3.8.0-f5a2r5rexdlv74imgptmadls3caz5oyw/spack-src/CMakeFiles/pkgRedirects/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libpng-1.6.39-tkxa7i2fbzr7q5tkht2zn6mbnravekcd/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libpng-1.6.39-tkxa7i2fbzr7q5tkht2zn6mbnravekcd/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libgeotiff-1.7.1-7i2pay7n7kyf2lkdgw3ih5k2nkz35ttu/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libgeotiff-1.7.1-7i2pay7n7kyf2lkdgw3ih5k2nkz35ttu/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/lib/cmake/proj4/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/lib/cmake/proj4/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/lib/cmake/proj/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/lib/cmake/proj/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/share/proj/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/proj-7.2.1-ulvikgu6cuz3c2xwmuxifqlhnnkg6353/share/proj/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/sqlite-3.43.2-cnpvxmmjnwdcyl7x2norcwy5yomtg43a/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/sqlite-3.43.2-cnpvxmmjnwdcyl7x2norcwy5yomtg43a/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/readline-8.2-afhogdyk5ngwn765nyrxopebih2gdctx/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/readline-8.2-afhogdyk5ngwn765nyrxopebih2gdctx/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libtiff-4.5.1-yflqcndxbcs3jxv2z7lcnqnv5ckphpl3/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libtiff-4.5.1-yflqcndxbcs3jxv2z7lcnqnv5ckphpl3/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/cmake-3.27.7-3x67s5ytcashm6xvy3jfyohu43spsif6/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/cmake-3.27.7-3x67s5ytcashm6xvy3jfyohu43spsif6/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/curl-8.4.0-fql7y6fhrqrc5acvlqtsdpkojww3ln3n/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/curl-8.4.0-fql7y6fhrqrc5acvlqtsdpkojww3ln3n/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/zlib-ng-2.1.4-cky7voimjpmerjaesrf3xok7jfafae5i/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/zlib-ng-2.1.4-cky7voimjpmerjaesrf3xok7jfafae5i/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/pkgconf-1.9.5-32slusryiobjjsqnxex2acz4lvgsxwfi/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/pkgconf-1.9.5-32slusryiobjjsqnxex2acz4lvgsxwfi/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/ninja-1.11.1-ng2ct2a543iwxerlx3dtt3v5jn45dgw5/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/ninja-1.11.1-ng2ct2a543iwxerlx3dtt3v5jn45dgw5/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libjpeg-turbo-3.0.0-muokhbxajh2fiv4n4iox2gmpgajq2ftn/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libjpeg-turbo-3.0.0-muokhbxajh2fiv4n4iox2gmpgajq2ftn/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/ncurses-6.4-jjieq2gyfu7bqrqan3mmsh3gyf2nlom5/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/ncurses-6.4-jjieq2gyfu7bqrqan3mmsh3gyf2nlom5/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/json-c-0.16-ctbahsk5m2gqw42xqm22jywlq6l4qcnb/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/json-c-0.16-ctbahsk5m2gqw42xqm22jywlq6l4qcnb/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/geos-3.12.1-uti3c3v2g7tpxxlof7r3o7jf7syztlb7/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/geos-3.12.1-uti3c3v2g7tpxxlof7r3o7jf7syztlb7/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/expat-2.5.0-ikwq3n2ajyhvfbsbohrju5rjz74dosev/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/expat-2.5.0-ikwq3n2ajyhvfbsbohrju5rjz74dosev/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/nghttp2-1.57.0-6wbi3szx3pt5dzqfpnhvqdts75muw54h/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/nghttp2-1.57.0-6wbi3szx3pt5dzqfpnhvqdts75muw54h/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/lib/spack/env/clang/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/lib/spack/env/clang/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/lib/spack/env/case-insensitive/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/lib/spack/env/case-insensitive/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/lib/spack/env/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/lib/spack/env/proj-config.cmake
    /Users/cmarsh/.pyenv/versions/3.10.4/PROJConfig.cmake
    /Users/cmarsh/.pyenv/versions/3.10.4/proj-config.cmake
    /Users/cmarsh/.pyenv/versions/3.10.4/CMake/PROJConfig.cmake
    /Users/cmarsh/.pyenv/versions/3.10.4/CMake/proj-config.cmake
    /opt/homebrew/Cellar/pyenv/2.3.12/libexec/PROJConfig.cmake
    /opt/homebrew/Cellar/pyenv/2.3.12/libexec/proj-config.cmake
    /opt/homebrew/Cellar/pyenv/2.3.12/plugins/python-build/PROJConfig.cmake
    /opt/homebrew/Cellar/pyenv/2.3.12/plugins/python-build/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/cmake/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/cmake/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/lib/cmake/proj4/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/lib/cmake/proj4/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/lib/cmake/proj/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/lib/cmake/proj/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/share/proj/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/var/spack/environments/chm/.spack-env/view/share/proj/proj-config.cmake
    /opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims/PROJConfig.cmake
    /opt/homebrew/Cellar/pyenv-virtualenv/1.2.1/shims/proj-config.cmake
    /Users/cmarsh/.pyenv/shims/PROJConfig.cmake
    /Users/cmarsh/.pyenv/shims/proj-config.cmake
    /Users/cmarsh/.pyenv/PROJConfig.cmake
    /Users/cmarsh/.pyenv/proj-config.cmake
    /Users/cmarsh/PROJConfig.cmake
    /Users/cmarsh/proj-config.cmake
    /opt/homebrew/opt/qt5/PROJConfig.cmake
    /opt/homebrew/opt/qt5/proj-config.cmake
    /Users/cmarsh/Documents/science/code/spack/PROJConfig.cmake
    /Users/cmarsh/Documents/science/code/spack/proj-config.cmake
    /opt/homebrew/PROJConfig.cmake
    /opt/homebrew/proj-config.cmake
    /opt/homebrew/lib/cmake/proj4/PROJConfig.cmake
    /opt/homebrew/lib/cmake/proj4/proj-config.cmake
    /opt/homebrew/lib/cmake/proj/PROJConfig.cmake
    /opt/homebrew/lib/cmake/proj/proj-config.cmake

  The file was found at

    /opt/homebrew/lib/cmake/proj/proj-config.cmake
```

## Steps to reproduce the problem.

Build gdal with cmake

## Operating system

macos & linux (uncertain about windows)

## GDAL version and provenance

8.3.x

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
CC @dg0yt if you want to double check. The reason for that change is https://github.com/OSGeo/gdal/issues/8942. And the initial reason for explicitly trying with PROJ config file was because of static linking issues on Windows when using FindPROJ module (#5210 / https://github.com/OSGeo/gdal/pull/5212)

**Comment by dg0yt** [comment]
I am against this change. It adds much complexity for something which can be resolved easily by one configuration parameter.
But I will write that in the issue.

**Comment by dg0yt** [comment]
Imagine we could do the opposite in some places: Replace 30 lines of incomprehensible, custom CMake code with 5 lines of basic CMake find stuff... 🌻

**Comment by rouault** [comment]
superseded per https://github.com/OSGeo/gdal/pull/8964

**Pull request closed without merging**
