### PR TITLE
Updates to the java bindings to generate maven artifacts.

### PR DESCRIPTION
**Pull request by jdeolive**
This change updates the build for the java bindings to generate maven artifacts that meet the requirements of the central maven repository. It also includes some infrastructure for signing the artifacts with GPG, another requirement for central.

### CODE REVIEW

**Comment by rouault** [comment]
There's a Travis build failure :
```
BUILD FAILED

/home/travis/build/OSGeo/gdal/gdal/swig/java/build.xml:57: /home/travis/build/OSGeo/gdal/gdal/swig/java/java does not exist.

Total time: 7 seconds

make: *** [build] Error 1
```

**Comment by jdeolive** [comment]
Hey Even. Thanks for the feedback. 

- Yes, developers can use their own keys. I'll update the release instructions with some steps how to do this.
- Once the OSSRH infrastructure is set up I was going to follow up on the release document with the steps on how to deploy the artifacts. 
- As for the build failure, I updated the build.xml, I hope that fixes it.

**Comment by rouault** [comment]
> Right. How about I take the maven part out of the default ant build and make running it a manual step documented as part of the release process? With obviously a note that this step only works on Linux/OSX. Will that work?

Sounds good. It might for example be a non-default ant task.

**Comment by jdeolive** [comment]
Ok, pull request updated.

>

**Comment by jdeolive** [comment]
Ok, final instructions to deploy to maven central added to the pull request. 

Once you are happy with the pull request I can squash all of the commits down into a single commit. Or do you prefer maintaining all of the individual commits?

**Comment by rouault** [comment]
Since the master VCS is SVN and I do by applying the .patch (having issues with git-svn sometimes...), I folded the commits into this single one 
r28842 "Java bindings: updates to generate maven artifacts (patch by Justin Deoliveira)"

**Comment by jdeolive** [comment]
Awesome, thanks a lot Even! I'll push the artifact for 1.11.2 into central later today. 

I was also thinking I would perhaps make a quick update to this wiki page to let users know they can find the jar in maven central.

  http://trac.osgeo.org/gdal/wiki/GdalOgrInJava

Or do you recommend another page?

**Comment by rouault** [comment]
> I was also thinking I would perhaps make a quick update to this wiki page to let users know they can find the jar in maven central.
> 
> http://trac.osgeo.org/gdal/wiki/GdalOgrInJava

Sounds good

**Pull request closed without merging**
