### PR TITLE
TIFF/COG: report content of the header ghost area in metadata

### PR DESCRIPTION
**Pull request by rouault**
See https://github.com/cogeotiff/rio-cogeo/issues/151#issuecomment-669240560

### CODE REVIEW

**Comment by vincentsarago** [comment]
thanks so much for this @rouault 🙏

**Comment by vincentsarago** [comment]
👋 @rouault was this included in latest 3.1.2 release or is planned for 3.2.0 ?

**Comment by rouault** [comment]
As indicated in the milestone: 3.2.0

**Comment by vincentsarago** [comment]
🤦 thanks Even

**Pull request merged**
