### PR TITLE
VFK: Support to UTF-8 VFK data

### PR DESCRIPTION
**Pull request by isax-sro**
## What does this PR do?

Support for UTF-8 encoding. The support for old encodings and possibly new ones should also work.

## Environment

Provide environment details, if relevant:

* OS: Debian
* Compiler: gcc

### CODE REVIEW

**Comment by rouault** [comment]
CC @landam

**Comment by rouault** [comment]
Doxygen / documentation issue:
```
 vfkpropertydefn.cpp:44:10: error: parameter 'bEncoding' not found in the function declaration [-Werror,-Wdocumentation]
  \param bEncoding encoding (only for "text" type)
         ^~~~~~~~~
```

**Comment by isax-sro** [comment]
Can you point me to some place how to compile GDAL from github code? The configure file is missing so standard way
`
./configure
./make && make install
`
is not possible.

**Comment by rouault** [comment]
> The configure file is missing

run "./autogen.sh" before to generate it.

by the way, you should re-target your pull request against the master branch of GDAL, which is where changes should go first

**Comment by isax-sro** [comment]
Thanks for configure file help.
How to rebuild GDAL if there are changes in header files? It seems to me I have to do `make clean` and start fresh new build with `make` that takes so long. Any help?

**Pull request closed without merging**
