### PR TITLE
Generate `./configure` with `./autogen.sh` during build process.

### LINKED ISSUE #3561: Do not put configure in git
Having to regenerate it each time configure.ac is modified is a bad practice and not intuitive for new contributors
Will require running autogen.sh to be run in the CI configurations, Docker, etc.

### PR DESCRIPTION
**Pull request by cmarmo**
## What does this PR do?
This pull request remove `./configure` and `aclocal.m4` from git.
They are now produced by `autogen.sh` during the building process.

## What are related issues/pull requests?
Fixes #3561

## Failing github Actions
 - [x] Conda: if I understand correctly the recipe for the build should be updated on [conda-forge](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/build.sh)? 
- [x] Fedora Rawhide: a segmentation fault in the tests that I can't reproduce... if anyone has any idea... :(

### CODE REVIEW

**Comment by cmarmo** [comment]
Removing the WIP because after reading the ref in #4341 I can't find another solution...
Thanks for considering this PR anyway if it can be useful.

**Comment by rouault** [comment]
Regarding the Conda builds, I suspect that adding the generation of configure in gdal/ci/travis/conda/setup.sh should fix the build, as the Conda build copies the whole tree to do the build

the gdal/mkgdaldist.sh script should also be updated to generate configure, since we want it to be included in the official tarballs

>     * Fedora Rawhide: a segmentation fault in the tests that I can't reproduce... if anyone has any idea... :(

I've seen that in other PRs recently, so unrelated to your changes

**Comment by rouault** [comment]
gdal/fuzzers/build.sh also needs to be updated

**Comment by cmarmo** [comment]
>     * [x]  Conda: if I understand correctly the recipe for the build should be updated on [conda-forge](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/build.sh)?

Thanks @rouault for your suggestion: I've put the `autogen.sh` in the conda setup and the build succeeded. However I'm wondering if the conda-forge recipe is meant to work only on the gdal dist (containing the `./configure`)  or also with the git repository: in this second case  changing the recipe would be the appropriate way to build. What is the best way to made them aware of the change (if the PR will be accepted)?

>     * [x]  Fedora Rawhide: a segmentation fault in the tests that I can't reproduce... if anyone has any idea... :(

Thanks... it went away as you said.

**Comment by rouault** [comment]
>  if the conda-forge recipe is meant to work only on the gdal dist (containing the `./configure`) or also with the git repository: in this second case changing the recipe would be the appropriate way to build. What is the best way to made them aware of the change (if the PR will be accepted)?

yes, once this PR is merged, a PR to https://github.com/conda-forge/gdal-feedstock will be appropriate.

I was wondering also if we shouldn't had a rule in gdal/GNUmakefile like :
```
configure: configure.ac
    ./autogen.sh
```
so that it is regenerated for developers ?

**Comment by cmarmo** [comment]
> I was wondering also if we shouldn't had a rule in gdal/GNUmakefile like :
> 
> ```
> configure: configure.ac
>     ./autogen.sh
> ```
> 
> so that it is regenerated for developers ?

To be honest, once documented I don't think typing
```
$ ./autogen.sh
```
is more time-consuming than
```
$ make configure
```
and having one single option is less confusing ... at least for me....

Also in the procedure "autogen -> configure -> make" I don't like to have `make` creating `configure` ...
But I guess it's personal taste... so you are the maintainer, if you really like the idea I will add it... :)

BTW, should I squash all my messy commits? Thanks!

**Comment by rouault** [comment]
> is more time-consuming than
> 
> ```
> $ make configure
> ```

ah, and I actually meant to make that configure target as a dependency of the default build target. I believe that's what automagically done by full autoconf/automake projects, but GDAL only uses automake. The idea is that you manually bootstrap with ./autogen.sh the first time you build the repository, and then what that's done, changes in configure.ac cause configure to be automatically regenerated (and ./configure automatically called). That's more a wish item than a hard requirement (as our manual makefiles that lack dependency rules will always cause the build experience to be painful), if that turns out to be too complicated.

> BTW, should I squash all my messy commits? Thanks!

I'll do that with the Squash and merge github button

**Comment by cmarmo** [comment]
>  I believe that's what automagically done by full autoconf/automake projects, but GDAL only uses automake. The idea is that you manually bootstrap with ./autogen.sh the first time you build the repository, and then what that's done, changes in configure.ac cause configure to be automatically regenerated (and ./configure automatically called).

I think it could be worth it to improve `./autogen.sh` in the long term, this will also make easier packaging for distributions.

**Comment by rouault** [comment]
> I think it could be worth it to improve `./autogen.sh` in the long term, this will also make easier packaging for distributions.

to be honest, the long (and hopefully not so long) term solution will be to wipe off completely current build systems to use cmake. I would have suggested not to do anything regarding that ticket if you had asked before,  but as you were 90% finished already...

**Comment by cmarmo** [comment]
> to be honest, the long (and hopefully not so long) term solution will be to wipe off completely current build systems to use cmake. I would have suggested not to do anything regarding that ticket if you had asked before, but as you were 90% finished already...

Glad to know! :)

**Comment by cmarmo** [comment]
Since cmake is the perspective, should this be closed or merged soon? Thanks!

**Comment by rouault** [comment]
I'm merging this . Thanks!

**Pull request merged**
