### PR TITLE
Use typedefs to both define new return value types and tell Swig about them.

### PR DESCRIPTION
**Pull request by ajolma**
This compiles and test ok in Perl.

Removes few %applys and #ifdefs.

### CODE REVIEW

**Comment by ajolma** [comment]
Should do this: http://stackoverflow.com/questions/10147445/github-adding-commits-to-existing-pull-request

**Comment by rouault** [comment]
@ajolma Not sure if you are aware of it but currently the Python bindings generated files are not refreshed by the Travis builds. So you either need to "make generate" in swig/python and commit those files, or edit .travis.yml to do the refresh (probably by removing --with-python in ./configure and doing cd swig/python; make generate; make; sudo make install; cd ../.. after the library build)

**Comment by ajolma** [comment]
ok, thanks. I've been running the autotests myself but it's good to see travis do proper job too.

**Comment by rouault** [comment]
@ajolma Do you intend this work to be in GDAL 2.0 or GDAL 2.1 ? I'm not clear if the changes related to default arguments will have user visible consequences or if it's just cleanup for us. If it's cleanup, we can probably postpone to 2.1 to minimize risks.

**Comment by ajolma** [comment]
25.05.2015, 12:12, Even Rouault kirjoitti:
>
> @ajolma <https://github.com/ajolma> Do you intend this work to be in 
> GDAL 2.0 or GDAL 2.1 ? I'm not clear if the changes related to default 
> arguments will have user visible consequences or if it's just cleanup 
> for us. If it's cleanup, we can probably postpone to 2.1 to minimize 
> risks.
>

It is not my intention to make any changes to the APIs (although I would 
love to), so it is basically just a cleanup (of 10 years of patches of 
patches of ...).

So yes, we can postpone this to 2.1. I'm just wondering how well the 
tests really test everything since the cleanup is rather heavy and 
corner cases may be left untested.

Ari

**Comment by rouault** [comment]
@ajolma regarding the build failure, try "sudo python setup.py install " instead of "sudo make install" for the python bindings installation. I hate those python dist-utils stuff.

Regarding tests, the Python bindings are very well tested by the autotest suite. Java and CSharp are only partialy tested.

**Comment by ajolma** [comment]
One thing comes to mind, which could be easy to change accidentally and are very subtle changes, are the keyword arguments in Python. The keyword is picked from the method definition in Swig interface. I'm not sure right now if I have changed those but I'll keep that in mind.

**Comment by ajolma** [comment]
What's the travis setup? The last test error does not occur in my machine.

**Comment by rouault** [comment]
It's a Ubuntu 12.04 VM, so with Perl 5.14.2 presumably (http://packages.ubuntu.com/precise/perl and http://docs.travis-ci.com/user/languages/perl/). And with swig 2.0.4

**Pull request closed without merging**
