### PR TITLE
CI: Add `ubuntugis` PPA by URL

### PR DESCRIPTION
**Pull request by lnicola**
## What does this PR do?

I can reproduce the PPA issue easily on Ubuntu 20.04 (22.04 works file), but adding by URL instead seems to fix it.

The signing key is taken from the PPA page.

## What are related issues/pull requests?

https://lists.osgeo.org/pipermail/ubuntu/2023-October/002046.html

## Tasklist

 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by lnicola** [comment]
s390x failure seems unrelated.

**Comment by rouault** [comment]
thanks! could you also update ../ci/travis/csa_common/before_install.sh in a similar way (it is used not only by Travis-CI but also by ../.github/workflows/clang_static_analyzer.yml) ?

**Comment by lnicola** [comment]
Done, not sure how I originally missed it. There's another one in `swig/python/gdal-utils/test-ubuntu-install.sh.txt`, but that seems unused?

**Comment by rouault** [comment]
> There's another one in `swig/python/gdal-utils/test-ubuntu-install.sh.txt`, but that seems unused?

I think so

**Comment by rouault** [comment]
The backport to `release/3.7` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
To https://github.com/OSGeo/gdal.git
 ! [remote rejected]       backport-8571-to-release/3.7 -> backport-8571-to-release/3.7 (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/cmake_builds.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/OSGeo/gdal.git'

```
</details>


To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.7 release/3.7
# Navigate to the new working tree
cd .worktrees/backport-release/3.7
# Create a new branch
git switch --create backport-8571-to-release/3.7
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 5fa155111fb5eb01395030a8e3b88e305dd421f1
# Push it to GitHub
git push --set-upstream origin backport-8571-to-release/3.7
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.7
```
Then, create a pull request where the `base` branch is `release/3.7` and the `compare`/`head` branch is `backport-8571-to-release/3.7`.

**Comment by rouault** [comment]
cherry-picked to 3.7 per f33e4f877cd0e0a78be3c4c99d9a4b8380ac4390

**Comment by lnicola** [comment]
We could have waited, it's going to be fixed soon: https://bugs.launchpad.net/launchpad/+bug/2039251.

**Pull request merged**
