### PR TITLE
enable lossless compression for webp in tiff

### PR DESCRIPTION
**Pull request by normanb**
## What does this PR do?

Fixes the bug reported https://gitlab.com/libtiff/libtiff/merge_requests/32 that webp compression in TIFF doesn't support lossless compression.

## What are related issues/pull requests?

https://gitlab.com/libtiff/libtiff/merge_requests/32

## Tasklist

 - [x] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by rouault** [comment]
On gcc52_stdcpp14_sanitize
```  TEST: tiff_write_tiled_webp ... [22011, 22335, 21583]
fail
    line 8070: fail
```
Likely due to using oldish webp, you may need to test for WEBP_LOSSLESS in md['DMD_CREATIONOPTIONLIST']. I also see the test for #if WEBP_ENCODER_ABI_VERSION >= 0x0209 being added in tif_webp.c. Should that version be set as the minimum to offer WEBP_LOSSLESS ? Otherwise lossless might not be lossless, right ?

**Comment by normanb** [comment]
@rouault I pushed the change to check for `WEBP_LOSSLESS`. 

`Exact` corresponding to `WEBP_ENCODER_ABI_VERSION >= 0x020` preserves the values that would be marked as transparent in RGBA. WebP supported lossless prior to this version without `exact`, this is an enhancement that I am marking as required rather than the default of false. What are your thoughts?

**Comment by rouault** [comment]
> WebP supported lossless prior to this version without `exact`, this is an enhancement that I am marking as required rather than the default of false

Ah ok. Then requiring WEBP_ENCODER_ABI_VERSION >= 0x0100 is good enough. Preserving exact values in A=0 region doesn't seem critical enough to me to required >= 0x0209 for the LOSSLESS mode (most dataset will have R=G=B=0 when A=0)

**Comment by normanb** [comment]
ok, I will remove that check for `exact`

**Comment by rouault** [comment]
> ok, I will remove that check for `exact`

Ah, I probably wasn't clear enough. I meant that your previous code seemed fine to me after your explanations. But I'm fine also with your latest simplification

**Comment by rouault** [comment]
OK, please submit the equivalent PR to libtiff

**Comment by normanb** [comment]
@rouault thanks - https://gitlab.com/libtiff/libtiff/merge_requests/46

**Comment by vincentsarago** [comment]
🎉

**Pull request merged**
