### PR TITLE
Doc: attempt at fixing issue with color of version switch

### LINKED ISSUE #10680: Doc: Move version selection to nagivation bar
### Feature description

Make it easier to notice the version selector by placing it at the bottom of the navigation bar, as is done with the PROJ docs:

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10680

### CODE REVIEW

**Comment by pjonsson** [comment]
I have no idea if it's related to the problems you're seeing, but readthedocs are apparently enabling this by default from today: https://about.readthedocs.com/blog/2024/07/addons-by-default/

**Comment by rouault** [comment]
> I have no idea if it's related to the problems you're seeing, but readthedocs are apparently enabling this by default from today: https://about.readthedocs.com/blog/2024/07/addons-by-default/

this is indeed related

**Comment by rouault** [comment]
The backport to `release/3.9` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 6931949e16... Doc: fix issue with color of version switch
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging doc/source/conf.py
[backport-10959-to-release/3.9 66ad22a5fb] Doc: set flyout_display=attached
 Author: Even Rouault <even.rouault@spatialys.com>
 Date: Mon Oct 7 22:21:22 2024 +0200
 1 file changed, 1 insertion(+)
Auto-merging doc/source/gdal_rtd/static/css/gdal.css
CONFLICT (content): Merge conflict in doc/source/gdal_rtd/static/css/gdal.css

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.9 release/3.9
# Navigate to the new working tree
cd .worktrees/backport-release/3.9
# Create a new branch
git switch --create backport-10959-to-release/3.9
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 0bf19955546948de991bcc13024fd372f288b2c4,6931949e16dcd7287d24a0419a7341c5b4dd2847
# Push it to GitHub
git push --set-upstream origin backport-10959-to-release/3.9
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.9
```
Then, create a pull request where the `base` branch is `release/3.9` and the `compare`/`head` branch is `backport-10959-to-release/3.9`.

**Comment by rouault** [comment]
manually cherry-picked to 3.9

**Pull request merged**
