### PR TITLE
fix: wasm/emscripten "long long" type check 

### PR DESCRIPTION
**Pull request by remoe**
Using of AutoConf internal checks. Own AutoConf macro not needed any more?
This is needed to compile with emscripten.

### CODE REVIEW

**Comment by rouault** [comment]
Please also run "autoreconf" (with autoconf 2.69) and commit the modified autoconf file, since that one is (weirdly) in git

**Comment by remoe** [comment]
you mean the "configure" - file ?

**Comment by remoe** [comment]
Calling of "autoreconf" changes the following files:
gdal/aclocal.m4
gdal/configure
gdal/port/cpl_config.h.in

Ok, to commit?

**Comment by rouault** [comment]
Ah I was too fast.. I meant the 'configure' file, and I only meant running 'autoconf' (not autoreconf). Could you revert your last commit, run 'autoconf' and commit 'configure' ?

**Comment by remoe** [comment]
ok, done.

**Pull request merged**
