### PR TITLE
Fixed reading nodata value for RMF driver and added scaling support

### PR DESCRIPTION
**Pull request by AlexBobkov**

### CODE REVIEW

**Comment by rouault** [comment]
The nodata changes make sense, but I'm not sure to understand why you define GetScale() and SetScale() since you don't read/write scale from the format.

**Comment by AlexBobkov** [comment]
Raw elevations in RMF format (*.mtw) can be in different units: meters, centimeters, millimeters, meters. I need to pass GDALDataset to a 3rd party library that expects elevations to be in meters. So I supposed I can use the Get/SetScale methods to set proper scale to convert elevations to meters.

**Comment by rouault** [comment]
- How do you know in which unit the elevation are (user choice) ?
- Does the 3rd party library use GetScale () ?

You could probably avoid implementing GetScale()/SetScale()  at all, by just changing RMFDataset to make it derive from GDALPamDataset and RMFRasterBand from GDALPamRasterBand. The GetScale()/SetScale() have a default implementation there, that will be persisted furthermore in a .aux.xml file.

**Comment by AlexBobkov** [comment]
> How do you know in which unit the elevation are (user choice) ?

This information is stored in the file and can be obtained with GetUnitType method.

> Does the 3rd party library use GetScale () ?

No, it does not yet. But I can provide a patch there too.

> You could probably avoid implementing GetScale()/SetScale() at all, by just changing RMFDataset to make it derive from GDALPamDataset and RMFRasterBand from GDALPamRasterBand. The GetScale()/SetScale() have a default implementation there, that will be persisted furthermore in a .aux.xml file.

All necessary information (unit type) is already stored in the file. There is no need to save it to xml file. Scale is only needed during runtime and can be inferred from unit type.

**Comment by rouault** [comment]
Ah I missed that GetUnitType() was implemented. Then I think the best would be for the 3rd party libary to read it and do the conversion to meter from that. Using GetScale() would be a hack.

**Comment by AlexBobkov** [comment]
OK, I've rolled back the GetScale()/SetScale() changes

**Comment by rouault** [comment]
Committed in trunk r29423

**Pull request closed without merging**
