### PR TITLE
add gdaladdo option to set webp level

### PR DESCRIPTION
**Pull request by tbonfort**
Currently there is no way to set the webp compression level when creating overviews. This PR implements the functionality (with the same kludges as what's done when setting JPEG quality, i.e. it would need a substantial cleanup one day).
Documentation commits will follow pending on wether this is accepted...

### CODE REVIEW

**Comment by rouault** [comment]
LGTM. Yes, documentation would be needed. Would you also mind adding tests in autotest/gcore/tiff_write.py ? You could take inspiration from test_tiff_write_90() and test_tiff_write_91(), but looking at them, they are not so convincing regarding checking that the quality setting is propagated to overviews: I think that instead of the file size (which is global to full resolution + overviews), we should check that the band.GetOverview(0).Checksum() value changes when applying different quality settings.

**Comment by rouault** [comment]
> inspiration from test_tiff_write_90() and test_tiff_write_91(), but looking at them, they are not so convincing

fixed in commit 3b6f49e34506d00e6d7ae8c2dbbac89096bab9ec

**Comment by tbonfort** [comment]
Added some tests, and fixed up 3b6f49e, but I can't get them to produce correct results on my instance, waiting for the autotests to kick in.
I'm getting some unexpected behavior locally:
in autotest/gdrivers/data:
```
gdal_translate -co COMPRESS=WEBP -b 1 -b 1 -b 1 -colorinterp red,green,blue utm.tif 99.tif
gdal_translate -co COMPRESS=WEBP -b 1 -b 1 -b 1 -colorinterp red,green,blue utm.tif 77.tif
gdal_translate -co COMPRESS=WEBP -b 1 -b 1 -b 1 -colorinterp red,green,blue utm.tif 33.tif
gdaladdo --config WEBP_LEVEL_OVERVIEW 33  -r average 33.tif 2 4
gdaladdo --config WEBP_LEVEL_OVERVIEW 77  -r average 77.tif 2 4
gdaladdo --config WEBP_LEVEL_OVERVIEW 99 -r average 99.tif 2 4
ls -l 33.tif 77.tif 99.tif
# files are identical

gdal_translate -co COMPRESS=WEBP -b 1 -b 1 -b 1 -colorinterp red,green,blue utm.tif 33.tif
gdal_translate -co COMPRESS=WEBP -b 1 -b 1 -b 1 -colorinterp red,green,blue utm.tif 77.tif
gdal_translate -co COMPRESS=WEBP -b 1 -b 1 -b 1 -colorinterp red,green,blue utm.tif 99.tif
gdaladdo --config WEBP_LEVEL_OVERVIEW 99 --config GDAL_NUM_THREADS 8 -r average 99.tif 2 4
gdaladdo --config WEBP_LEVEL_OVERVIEW 77 --config GDAL_NUM_THREADS 8 -r average 77.tif 2 4
gdaladdo --config WEBP_LEVEL_OVERVIEW 33 --config GDAL_NUM_THREADS 8 -r average 33.tif 2 4
ls -l 33.tif 77.tif 99.tif
#files are different, with expected sizes w.r.t overview webp quality level
```

**Comment by tbonfort** [comment]
replaced by #3039

**Pull request closed without merging**
