### PR TITLE
[PostgreSQL] Populate GDAL_DMD_ILLEGAL_FIELD_NAMES

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Review by rouault — APPROVED** [review]
Interesting that xmin and xmax are illegal!

**Comment by nyalldawson** [comment]
@rouault 

> Interesting that xmin and xmax are illegal!

Totally! I'm really surprised that I haven't seen more postgis users bump into this restriction before :thinking: 
(I had to double check and confirm it myself before I believed it!)

**Comment by nyalldawson** [comment]
@rouault are you aware offhand of any other formats with field names limitations?

**Comment by rouault** [comment]
Nothing jumps to mind

**Pull request merged**
