### PR TITLE
fix for #3343

### PR DESCRIPTION
**Pull request by idanmiara**
## What does this PR do?

a few minor fixes for https://github.com/OSGeo/gdal/pull/3343

## What are related issues/pull requests?

https://github.com/OSGeo/gdal/pull/3343

## Tasklist

 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by idanmiara** [comment]
`from osgeo import gdalnumeric` fails on MacOS and minigw. 
Isn't that what the `README.md` implies to import instead of numpy?

**Comment by rouault** [comment]
> `from osgeo import gdalnumeric` fails on MacOS and minigw.

as I mentioned in another of your PR, I suspect numpy isn't installed in those 2 CI setups. The gdalnumeric module is currently optional as we don't require numpy

**Comment by idanmiara** [comment]
> > `from osgeo import gdalnumeric` fails on MacOS and minigw.
> 
> as I mentioned in another of your PR, I suspect numpy isn't installed in those 2 CI setups. The gdalnumeric module is currently optional as we don't require numpy

Is this the [`Numeric`](https://pypi.org/project/Numeric/) python package that mentioned in the readme?
Does it supposed to be a drop in replacement for `numpy` to some extent and is installed on these CI setups? 
Or where `numpy` is not installed all the tests that depend on `gdalnumeric` just skipped?

Would you rather require `numpy` and drop all these excess mechanisms or something else?

**Comment by rouault** [comment]
Hum you asking questions from times where I was hardly involved with the project :-)

> Is this the [`Numeric`](https://pypi.org/project/Numeric/) python package that mentioned in the readme?

Numeric was (I believe) a competing project with numpy.  It is no longer relevant. > 10 years ago, there was a transition for the old-gen GDAL python bindings which used Numeric (I believe??) to numpy, and gdalnumeric was meant to ease the transition.

> Does it supposed to be a drop in replacement for numpy to some extent and is installed on these CI setups?

No idea if it is a drop-in replacement. I believe it is no longer relevant, at least for GDAL. It is not installed on any CI setup

> Or where numpy is not installed all the tests that depend on gdalnumeric just skipped?

Yes, tests that depend on numpy / gdalnumeric are skipped

> Would you rather require numpy and drop all these excess mechanisms or something else?

I wouldn't be opposed to requiring numpy to build the GDAL python bindings. I believe most people (and distributions) build GDAL Python bindings with numpy. You might raise the question on gdal-dev to see if anyone has objections.

**Comment by idanmiara** [comment]
asan_build faild - I'm not sure if it's a problem with the CI or with the PR.

**Comment by idanmiara** [comment]
Does the failure of `test_http_3` has anything to do with my PR?

**Comment by idanmiara** [comment]
now `test_vsicurl_streaming_1` fails... why is that?

**Comment by rouault** [comment]
> now `test_vsicurl_streaming_1` fails... why is that?

likely a flake. restarting. unfortunately download.osgeo.org is sometimes super slow

**Pull request merged**
