### PR TITLE
MRF/LERC: check that values are within target type range before casting

### PR DESCRIPTION
**Pull request by rouault**
CC @lucianpls

### CODE REVIEW

**Comment by lucianpls** [comment]
@rouault 
Lerc1Image is used in other projects, it can't depend on gdal headers.
How about using the explicit limits directly:
```
static int numBytesFlt(float z)
{
    if (z > 32767 || z < -32768 || z != int16_t(z))
        return 4;
    if (z > 127 || z < -128)
        return 2;
    return 1;
}
```

**Comment by rouault** [comment]
> How about using the explicit limits directly:

done

**Comment by lucianpls** [comment]
@rouault
GDALIsValueInRange<float>(NAN) returns false. It should be true, since NAN is a valid float value.

**Comment by lucianpls** [comment]
> @rouault GDALIsValueInRange<float>(NAN) returns false. It should be true, since NAN is a valid float value for use as NDV in this case.

I'm not sure that NAN works as explicit NDV, not the infinities. But it does seem strange that infinities are considered in range, while NAN is not.

**Comment by rouault** [comment]
> But it does seem strange that infinities are considered in range, while NAN is not.

yeah, I don't recall the reason for that. This was changed long time ago in 6e7704a9a47d62b67cca2fd1bd9cfe45df8266c4. Probably because NaN are generally annoying to work with, so GDALIsValueInRange() excludes them.

> I'm not sure that NAN works as explicit NDV, nor the infinities

Do you want me to add a std::isfinite() test in addition ?

**Comment by lucianpls** [comment]
> Do you want me to add a std::isfinite() test in addition ?

No, it should be fine the way it looks now. Thanks!

**Pull request merged**
