### PR TITLE
Terrago legacy: field alias name support for FileGDB

### PR DESCRIPTION
**Pull request by alanstewart-terragotech**
## What does this PR do?

Adds GetAliasName() and SetAliasName() to class OGRFieldDefn and implements support for them in the FileGDB driver. Python support is included. Test scripts are added to gdalautotest.

## What are related issues/pull requests?

None.

## Tasklist

 - [x] ADD YOUR TASKS HERE

    None.

 - [x] Add test case(s)

    ogr_fgdb_26()
    ogr_fgdb_27()

 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:

    Windows 7 Pro

* Compiler:

    Visual Studio 2017 32-bit

### CODE REVIEW

**Comment by alanstewart-terragotech** [comment]
I won’t be able to look at this until the week after Thanksgiving.

Alan
Sent from my iPad

On Nov 16, 2018, at 11:27 AM, Even Rouault <notifications@github.com<mailto:notifications@github.com>> wrote:


@rouault requested changes on this pull request.

________________________________

In gdal/ogr/ogr_feature.h<https://github.com/OSGeo/gdal/pull/1102#discussion_r234262030>:

> @@ -106,12 +107,16 @@ class CPL_DLL OGRFieldDefn

   public:
                         OGRFieldDefn( const char *, OGRFieldType );
+                        OGRFieldDefn( const char *, const char *, OGRFieldType );


I know you are imitating the existing legacy coding style, but naming the parameters would be much appreciated

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234262756>:

> @@ -83,6 +106,7 @@ OGRFieldDefn::OGRFieldDefn( const char * pszNameIn, OGRFieldType eTypeIn ) :

 OGRFieldDefn::OGRFieldDefn( const OGRFieldDefn *poPrototype ) :
     pszName(CPLStrdup(poPrototype->GetNameRef())),
+    pszAliasName(CPLStrdup(poPrototype->GetAliasNameRef())),


CPLStrdup() of NULL will not return NULL but an empty string, so I think you should do poPrototype->GetAliasNameRef() != nullptr ? CPLStrdup(...) : nullptr

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234262847>:

> @@ -222,6 +247,80 @@ const char *OGR_Fld_GetNameRef( OGRFieldDefnH hDefn )
     return OGRFieldDefn::FromHandle(hDefn)->GetNameRef();
 }

+/************************************************************************/
+/*                              SetAliasName()                               */


trim a few spaces at the right. Other occurences below too

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234263185>:

> @@ -222,6 +247,80 @@ const char *OGR_Fld_GetNameRef( OGRFieldDefnH hDefn )
     return OGRFieldDefn::FromHandle(hDefn)->GetNameRef();
 }

+/************************************************************************/
+/*                              SetAliasName()                               */
+/************************************************************************/
+
+/**
+ * \brief Reset the alias name of this field.
+ *
+ * This method is the same as the C function OGR_Fld_SetAliasName().
+ *
+ * @param pszNameIn the new alias name to apply.


wrong parameter name.

Add @since GDAL 2.4

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234263417>:

> +
+/**
+ * \brief Reset the alias name of this field.
+ *
+ * This method is the same as the C function OGR_Fld_SetAliasName().
+ *
+ * @param pszNameIn the new alias name to apply.
+ */
+
+void OGRFieldDefn::SetAliasName( const char * pszAliasNameIn )
+
+{
+    if( pszAliasName != pszAliasNameIn )
+    {
+        CPLFree( pszAliasName );
+        pszAliasName = CPLStrdup( pszAliasNameIn );


is nullptr accepted as an argument ?
There should be a decision if the absence of an alias is the nullptr or the empty string, and put everything consistant with that decision

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234263516>:

> +    {
+        CPLFree( pszAliasName );
+        pszAliasName = CPLStrdup( pszAliasNameIn );
+    }
+}
+
+/************************************************************************/
+/*                          OGR_Fld_SetAliasName()                           */
+/************************************************************************/
+/**
+ * \brief Reset the alias name of this field.
+ *
+ * This function is the same as the CPP method OGRFieldDefn::SetAliasName().
+ *
+ * @param hDefn handle to the field definition to apply the new alias name to.
+ * @param pszName the new alias name to apply.


wrong parameter name.

Add @since GDAL 2.4

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234263782>:

> +    ((OGRFieldDefn *) hDefn)->SetAliasName( pszAliasName );
+}
+
+/************************************************************************/
+/*                             GetAliasNameRef()                             */
+/************************************************************************/
+
+/**
+ * \fn const char *OGRFieldDefn::GetAliasNameRef();
+ *
+ * \brief Fetch alias name of this field.
+ *
+ * This method is the same as the C function OGR_Fld_GetAliasNameRef().
+ *
+ * @return pointer to an internal alias name string that should not be freed or
+ * modified.


Add @since GDAL 2.4

________________________________

In gdal/ogr/ogrfielddefn.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234263811>:

> + * This method is the same as the C function OGR_Fld_GetAliasNameRef().
+ *
+ * @return pointer to an internal alias name string that should not be freed or
+ * modified.
+ */
+
+/************************************************************************/
+/*                         OGR_Fld_GetAliasNameRef()                         */
+/************************************************************************/
+/**
+ * \brief Fetch alias name of this field.
+ *
+ * This function is the same as the CPP method OGRFieldDefn::GetAliasNameRef().
+ *
+ * @param hDefn handle to the field definition.
+ * @return the alias name of the field definition.


Add @since GDAL 2.4

________________________________

In gdal/ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234263915>:

> @@ -1661,6 +1662,13 @@ char* FGdbLayer::CreateFieldDefn(OGRFieldDefn& oField,

             fieldname_clean = temp_fieldname;
             oField.SetName(fieldname_clean.c_str());
+
+            /*  Attempt to preserve the original fieldname */
+            if(aliasname == NULL)


nullptr

________________________________

In gdal/ogr/ogrsf_frmts/filegdb/FGdbLayer.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234264301>:

> @@ -1694,10 +1702,10 @@ char* FGdbLayer::CreateFieldDefn(OGRFieldDefn& oField,
     /* We know nothing about Scale, so zero it out */
     CPLCreateXMLElementAndValue(defn_xml,"Scale", "0");

-    /*  Attempt to preserve the original fieldname */
-    if (fieldname != fieldname_clean)
+    /* Only set the AliasName if client requested it */
+    if (aliasname != NULL)


nullptr

________________________________

In gdal/swig/include/ogr.i<https://github.com/OSGeo/gdal/pull/1102#discussion_r234264613>:

> @@ -2194,6 +2194,18 @@ public:
     OGR_Fld_SetName(self, name);
   }

+  const char * GetAliasName() {
+    return (const char *) OGR_Fld_GetAliasNameRef(self);
+  }
+
+  const char * GetAliasNameRef() {


You can drop the GetAliasNameRef(). GetAliasName() wil be enough

________________________________

In gdal/swig/python/extensions/gdal_array_wrap.cpp<https://github.com/OSGeo/gdal/pull/1102#discussion_r234265190>:

> @@ -1,6 +1,6 @@
 /* ----------------------------------------------------------------------------
  * This file was automatically generated by SWIG (http://www.swig.org).
- * Version 3.0.8
+ * Version 3.0.12


could you regenerate with swig 3.0.8 exactly so as to have the minimum diff ?

**Comment by alanstewart-terragotech** [comment]
I think I have addressed everything.

Note:
1) In ArcGIS, when a field's alias name is requested the field's name is returned if no alias name has been assigned. This behavior is what has been implemented for filegdb.
2) C/C++ interfaces have no problem with passing null to SetAliasName(), but Python throws a value error.
3) I hope I have not screwed up too badly in my git-usage!

**Comment by rouault** [comment]
Please do a git rebase on top of latest origin/master so as to keep the commit history of this PR readable. And also squash your commits

Can be done withthe following procedure of https://github.com/OSGeo/gdal/blob/master/CONTRIBUTING.md
```
git fetch origin
git rebase origin/master
git reset --soft origin/master
git commit -a -m "Put here the synthetic commit message"
git push -f my_user_name my_branch
```

**Comment by rouault** [comment]
There is a doxygen mis-formatting
```
Generating docs for compound G/home/travis/build/OSGeo/gdal/gdal/ogr/ogrfielddefn.cpp:300: warning: Found unknown command `\freed'
/home/travis/build/OSGeo/gdal/gdal/ogr/ogrfielddefn.cpp:301: warning: Found unknown command `\field'
```
And
autotest/ogr/ogr_fgdb.py:2649: local variable 'name' is assigned to but never used
And
```
ogrfielddefn.cpp: In function ‘void OGR_Fld_SetAliasName(OGRFieldDefnH, const char*)’:
ogrfielddefn.cpp:288:23: error: use of old-style cast [-Werror=old-style-cast]
     ((OGRFieldDefn *) hDefn)->SetAliasName( pszAliasNameIn );
```

**Comment by alanstewart-terragotech** [comment]
I have problems with files that are auto-generated by swig.

‘git rebase origin/master’ lists several conflicting files.
So I run the swig build to freshly build these files.
‘git add’ on each conflicted file.
‘git rebase –continue’  lists a bunch more swig-generated files as ‘needs update’.
‘git add’ each of these since they’ve just been regenerated.
‘git rebase –continue’ results in conflicts, apparently on every file mentioned so far.

I clearly know/understand enough to totally f*ck myself. I of the generation that does not normally use this kind of language.

‘git rebase –abort’, which as I understand takes me back to the state immediately after ‘git fetch origin’.

Alan Stewart
Senior Software Engineer
TerraGo Technologies
3200 Windy Hill Road, Suite 1550W
Atlanta, GA 30339 USA
O.  +1 678.391.9615

www.terragotech.com<applewebdata://B24C0762-C7C9-4431-8518-ACC915448B89/www.terragotech.com>

**Comment by alanstewart-terragotech** [comment]
Think I got it, including the most recent change requests.

git fetch origin
git rebase origin/master
git rebase –skip (because the conflicts are all in swig-generated files)
Rebuild swig just to be sure. Does not generate any changes recognized by ‘git status’.
Then reset, commit and push as specified.

Alan Stewart
Senior Software Engineer
TerraGo Technologies
3200 Windy Hill Road, Suite 1550W
Atlanta, GA 30339 USA
O.  +1 678.391.9615

www.terragotech.com<applewebdata://B24C0762-C7C9-4431-8518-ACC915448B89/www.terragotech.com>

**Comment by alanstewart-terragotech** [comment]
Attempting to fix the linux/macos builds...

**Comment by alanstewart-terragotech** [comment]
Builds appear to be fixed, but tests appear to be hanging on some platforms and failing on others. The failures are not obviously due to my changes. Possibly a problem with Travis?

**Comment by rouault** [comment]
There are still errors:
```
Checking for tabulation characters...
ogr/ogrfielddefn.cpp
FAIL: tabulations detected. Please remove them!
```
There are also test failures:
https://api.travis-ci.com/v3/job/163375818/log.txt
I'd bet they are due to the regenerated SWIG bindings: the regenerated files appear to have unrelated changes. Can you generate it from Linux/Mac ? (since the GNUmakefile does some hacks after SWIG has run)

Also can you amend the commit message to be more descriptive.

**Comment by alanstewart-terragotech** [comment]
Where is the tabulation error? I can’t find it. Is it that there are tab characters in the file?

I’ve never been able to get autotest to run cleanly on my box, even before I started this branch.

I could possibly setup a MacOS environment.

Alan Stewart
Senior Software Engineer
TerraGo Technologies
3200 Windy Hill Road, Suite 1550W
Atlanta, GA 30339 USA
O.  +1 678.391.9615

www.terragotech.com<applewebdata://B24C0762-C7C9-4431-8518-ACC915448B89/www.terragotech.com>

**Comment by rouault** [comment]
> Is it that there are tab characters in the file?

yes

**Comment by alanstewart-terragotech** [comment]
I have struggled mightily with git... No problem setting up and building on MacOS, but getting to where I could push the resulting changes was frustrating. This push is of the regenerated gdal/swig/python files. I did have to make temporary change to the GNUMakfile in that location. The MacOS version of sed does not support a '--version' option. The comment in said file seems to say that particular line is not necessary, so I commented it out to perform this build.

**Comment by rouault** [comment]
This PR is staled. Do you intend to revive it ?

**Comment by alanstewart-terragotech** [comment]
I’m actively working on resolving the CI failures. Is there something I need to do to “revive” it?

Alan Stewart
Senior Software Engineer
TerraGo Technologies
3200 Windy Hill Road, Suite 1550W
Atlanta, GA 30339 USA
O.  +1 678.391.9615

www.terragotech.com<applewebdata://B24C0762-C7C9-4431-8518-ACC915448B89/www.terragotech.com>

**Comment by rouault** [comment]
>  Is there something I need to do to “revive” it?

Yes, rebasing on top of current master, solve conflict, cleanup commit history

**Comment by alanstewart-terragotech** [comment]
I’m currently working on master, I think. A fresh git clone from my fork will ultimately fetch from OSGeo/gdal, does it not? I’m trying to locally replicate the GitHub CI success from master on OSX and Ubuntu before moving back to my branch.

Alan Stewart
Senior Software Engineer
TerraGo Technologies
3200 Windy Hill Road, Suite 1550W
Atlanta, GA 30339 USA
O.  +1 678.391.9615

www.terragotech.com<applewebdata://B24C0762-C7C9-4431-8518-ACC915448B89/www.terragotech.com>

**Pull request closed without merging**
