### PR TITLE
avoid UnicodeDecodeError: charmap codec can't decode byte

### PR DESCRIPTION
**Pull request by jmckenna**
This allows GDAL /doc/ to compile on Windows (leveraging MS4W's Python 3.7.5).

### CODE REVIEW

**Comment by rouault** [comment]
can you possibly make the fix Python 2 compatible ? I believe our Azure Pipeline job still use python2. Or possible just change mentions to "python" in gdal/doc/Makefile to python 3 ?

**Comment by rouault** [comment]
> Or possible just change mentions to "python" in gdal/doc/Makefile to python 3 ?

I've added a commit for that in the branch

**Comment by jmckenna** [comment]
Sorry I lost power last night, i was testing my changes in Python2...    no worries!  cheers.

**Comment by jmckenna** [comment]
I should have marked the ticket with 'accepted' or something.  Anyway glad it is solved.

**Comment by jmckenna** [comment]
I can't change 'assigned' here.  Anyway, cheers from across the ocean.

**Comment by rouault** [comment]
Re-opening so that CI tests run completely before I can merge

**Comment by jmckenna** [comment]
oops yes sorry.  thanks for the changes.

**Comment by jmckenna** [comment]
Nice work, passes the doc test.  Thanks again. (not closing, ha)

**Comment by rouault** [comment]
Cherry-picked to 3.1

**Pull request merged**
