### PR TITLE
Fix issues with gdalbuildvrt and gdalwarp regarding src/dst/vrtnodata arguments and negative values (3.9.0 regression)

### PR DESCRIPTION
**Pull request by rouault**
Fixes https://lists.osgeo.org/pipermail/gdal-dev/2024-July/059162.html

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
I assume you have checked that there is not a way to fix this in argparse.hpp instead of pre-processing argv. I'm afraid it will resurface sooner or later.

**Comment by rouault** [comment]
> I assume you have checked that there is not a way to fix this in argparse.hpp instead of pre-processing argv. I'm afraid it will resurface sooner or later.

I did consider that option and you're right it is fragile, but it is not clear how that can be fixed in argparse itself. I guess that could be done but that would be a more extensive change I was willing to do, and I'm not sure how that would be welcomed by upstream, because basically the logic in argparse is to consider that anything starting with a dash and not being a number is a new option, rather than trusting the expected number of values for the option.

**Comment by rouault** [comment]
The backport to `release/3.9` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply c30f96e611... gdalwarp: fix -srcnodata/-dstnodata to accept negative value in first position (3.9.0 regression)
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging doc/source/programs/gdalwarp.rst
CONFLICT (content): Merge conflict in doc/source/programs/gdalwarp.rst

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.9 release/3.9
# Navigate to the new working tree
cd .worktrees/backport-release/3.9
# Create a new branch
git switch --create backport-10353-to-release/3.9
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick c30f96e611f2c46a776ddecd06285f0fbe0d676c,1d2ca0724ec0b5edca00bc9d02d1de5a74f7c1a3,79ae4414601ae9d6e7137853e537e011e758f4e4,ca6fd7fcea9186437aa1cbf845013583f1c03112
# Push it to GitHub
git push --set-upstream origin backport-10353-to-release/3.9
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.9
```
Then, create a pull request where the `base` branch is `release/3.9` and the `compare`/`head` branch is `backport-10353-to-release/3.9`.

**Comment by rouault** [comment]
backported in https://github.com/OSGeo/gdal/pull/10365

**Pull request merged**
