### PR TITLE
Still override $OPT when running python setup.py

### PR DESCRIPTION
**Pull request by bje-**
## What does this PR do?

This PR silences warnings produced by `python setup.py build` when building the Python C++ extensions. Apparently `setup.py` script uses the same flags as were used to build Python itself. On my system, warnings such as `-Wstrict-prototypes` are included and these are passed to `gcc` when compiling the C++ extension code. This produces a diagnostic message that `-Wstrict-prototypes` is not supported for C++ code (not applicable).

The setup.py infrastructure also doesn't provide the ability to easily control the C++ compiler flags (see https://bugs.python.org/issue1222585). Overriding $OPT with a set of sensible flags is the most appropriate workaround in the meantime.

## What are related issues/pull requests?

PR #360 

## Environment

Provide environment details, if relevant:

* OS: Ubuntu 16.04
* Compiler: GCC

### CODE REVIEW

**Comment by rouault** [comment]
I'm a bit ambivalent about that one... I'm wondering if some distributions wouldn't already override OPT with hardening flags. Perhaps @sebastic would know what/if distributions mess with Python extension compilation flags ?

**Comment by sebastic** [comment]
AFAIK distributions just set their hardening flags when building Python and let setuptools use that.

**Comment by rouault** [comment]
OK, so my understanding is that if we override OPT, we'll loose those hardening flags

**Comment by sebastic** [comment]
Correct, can't you use `python-config` to get the buildflags and append the ones you need?

**Comment by bje-** [comment]
40a329c51fcab75923481c554c9f035f10060162 is much more acceptable, yes?

**Comment by rouault** [comment]
> 40a329c is much more acceptable, yes?

Yes

**Comment by bje-** [comment]
It might be easier to just cherrypick 40a329c into master.

**Comment by rouault** [comment]
Actually I see this breaks on the mingw_w64 target with:
```
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    os.environ['OPT'] = " ".join(f for f in opt.split() if f != '-Wstrict-prototypes')
AttributeError: 'NoneType' object has no attribute 'split'
fixme:msvcrt:__clean_type_info_names_internal (0x1e2c80d0) stub
Cannot determine OUTDIR
```

**Comment by rouault** [comment]
I'm confused. Does that mean that your setup.py changes take only effect if OPT is explicitly defined as an environment variable, and so the removal of -Wstrict-prototypes wouldn't work by default ? I somehow thought that the get_config_vars('OPT') would get the 'resolved' flags, but apparently it just gets an environment variable ?

**Comment by bje-** [comment]
Sorry, I made a mistake in my commit message. I meant to just say that `get_config_vars('OPT')` may simply return `None`. It may get the value from the environment or from build system crumbs (eg `/usr/lib/python2.7/config-x86_64-linux-gnu/Makefile`). I'll amend the commit message.

**Comment by rouault** [comment]
Can you drop the GNUmakefile change as well so we can have testing of what the final change would be ?

**Pull request merged**
