### PR TITLE
NAS driver update

### PR DESCRIPTION
**Pull request by jef-n**

### CODE REVIEW

**Comment by rouault** [comment]
Failure on MacOS build should be fixed per e4026b077a092f614dc8a25b0025f01080eee47d

**Comment by rouault** [comment]
clang static analyzer:
```
{
  "uri": "file:///home/runner/work/gdal/gdal/ogr/ogrsf_frmts/nas/nashandler.cpp",
  "msg": "Value stored to 'pszName' during its initialization is never read",
  "location": {
    "importance": "essential",
    "location": {
      "message": {
        "text": "Value stored to 'pszName' during its initialization is never read"
      },
      "physicalLocation": {
        "artifactLocation": {
          "fileIndex": 0,
          "uri": "file:///home/runner/work/gdal/gdal/ogr/ogrsf_frmts/nas/nashandler.cpp"
        },
        "region": {
          "endColumn": 25,
          "endLine": 464,
          "startColumn": 25,
          "startLine": 464
        }
      }
    }
  }
}
```

**Comment by rouault** [comment]
@jef-n Has this sufficiently been tested to be included in 3.8.0 ?

**Comment by jef-n** [comment]
> @jef-n Has this sufficiently been tested to be included in 3.8.0 ?

I think so.  I verified that it produces identical results using old data and it works with new test data - but there's no real data yet and there will be a hard switch beginning next year in most German states (GeoInfoDok 6.0.1 => 7.1.2).

**Comment by rouault** [comment]
ok, thanks. merging

**Pull request merged**
