### PR TITLE
Fix build issues with latest msys2 mingw64 compiler & re-enable CI builds

### LINKED ISSUE #5317: CI: build-windows-msys2-mingw disabled
An upgrade in the msys2-mingw toolchain causes lots of warnings and errors to appear: https://github.com/OSGeo/gdal/runs/5216450145?check_suite_focus=true
We can not differences in the following packages:
``
$ diff -u /tmp/old.txt /tmp/new.txt
--- /tmp/old.txt	2022-02-16 14:56:34.422230084 +0100
+++ /tmp/new.txt	2022-02-16 14:56:22.422319897 +0100
@@ -1,4 +1,3 @@
-: Retrieving packages...
 mingw-w64-x86_64-gcc-11.2.0-8-any downloading...
 mingw-w64-x86_64-gcc-ada-11.2.0-8-any downloading...
 mingw-w64-x86_64-python-3.9.10-2-any downloading...
@@ -8,11 +7,11 @@
 mingw-w64-x86_64-cmake-3.22.2-1-any downloading...
 mingw-w64-x86_64-sqlite3-3.37.2-1-any downloading...
 mingw-w64-x86_64-gdb-multiarch-11.2-2-any downloading...
-mingw-w64-x86_64-binutils-2.37-4-any downloading...
-mingw-w64-x86_64-headers-git-9.0.0.6373.5be8fcd83-1-any downloading...
+mingw-w64-x86_64-binutils-2.37-5-any downloading...
+mingw-w64-x86_64-headers-git-9.0.0.6373.5be8fcd83-2-any downloading...
 mingw-w64-x86_64-openssl-1.1.1.m-1-any downloading...
 mingw-w64-x86_64-gdb-11.2-2-any downloading...
-mingw-w64-x86_64-crt-git-9.0.0.6373.5be8fcd83-1-any downloading...
+mingw-w64-x86_64-crt-git-9.0.0.6373.5be8fcd83-2-any downloading...
 mingw-w64-x86_64-gettext-0.21-3-any downloading...
 mingw-w64-x86_64-tcl-8.6.11-5-any downloading...
 mingw-w64-x86_64-tk-8.6.11.1-2-any downloading...
@@ -60,11 +59,11 @@
 mingw-w64-x86_64-mpc-1.2.1-1-any downloading...
 mingw-w64-x86_64-jansson-2.14-1-any downloading...
 mingw-w64-x86_64-libffi-3.3-4-any downloading...
-mingw-w64-x86_64-winpthreads-git-9.0.0.6373.5be8fcd83-1-any downloading...
-mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any downloading...
+mingw-w64-x86_64-winpthreads-git-9.0.0.6373.5be8fcd83-2-any downloading...
+mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-2-any downloading...
 mingw-w64-x86_64-termcap-1.3.1-6-any downloading...
 mingw-w64-x86_64-libsystre-1.0.1-4-any downloading...
 mingw-w64-x86_64-libb2-0.98.1-1-any downloading...
 mingw-w64-x86_64-libmangle-git-9.0.0.6373.5be8fcd83-1-any downloading...
-mingw-w64-x86_64-winstorecompat-git-9.0.0.6373.5be8fcd83-1-any downloading...
-mingw-w64-x86_64-windows-default-manifest-6.4-3-any downloading...
+mingw-w64-x86_64-winstorecompat-git-9.0.0.6373.5be8fcd83-2-any downloading...
+mingw-w64-x86_64-windows-default-manifest-6.4-4-any downloading...

### PR DESCRIPTION
**Pull request by rouault**
Fixes #5317

@dg0yt I believe this can go first into master, and you'll queue your further fixes on top of it ?

### CODE REVIEW

**Comment by dg0yt** [comment]
> @dg0yt I believe this can go first into master, and you'll queue your further fixes on top of it ?

Sure! :+1:

**Comment by rouault** [comment]
@kdesjard I've now merged it, so you can just test master.

**Comment by kdesjard** [comment]
Ran gdal_translate (conv to geotiff) and gdalinfo on 17 ASF products and few CDPF ones and worked fine.

**Comment by rouault** [comment]
@kdesjard Thanks for the feedback

**Pull request merged**
