### PR TITLE
[pgeo] Read non-spatial tables

### LINKED ISSUE #2889: Cannot read non-spatial tables from Personal Geodatabases
The PGEO driver does not support reading non-spatial tables from mdb files. Additionally, because the generic odbc driver will not accept a mdb file where the GDB_GeomColumns table exists, it is also impossible to use the odbc driver to read these non-spatial tables.

### PR DESCRIPTION
**Pull request by nyalldawson**
Without this change the Pgeo driver cannot read non-spatial tables
from Personal Geodatabases. (Additionally, because the generic odbc
driver will not accept a mdb file where the GDB_GeomColumns table
exists, it is impossible to use the odbc driver to read these
non-spatial tables.)

Fixes #2889

### CODE REVIEW

**Comment by nyalldawson** [comment]
https://github.com/OSGeo/gdal/pull/2888 is a pre-requisite for the new test to work

**Comment by nyalldawson** [comment]
@rouault is this one suitable for backport?

**Comment by rouault** [comment]
Looks to me more like a new functionality. If you badly need it in 3.1 branch in time for 3.1.3, please issue now a pull request against it (you might need to tweak the path to the file in autotest, since files got moved in data/xxxx subfolders in master)

**Comment by nyalldawson** [comment]
@rouault no problem -- happy to defer to your instincts here and delay the fix to 3.2!

**Pull request merged**
