### PR TITLE
WEBP/JPEGXL/GTiff: add COMPRESSION_REVERSIBILITY item in IMAGE_STRUCTURE metadata domain

### PR DESCRIPTION
**Pull request by rouault**
- WEBP: report a COMPRESSION_REVERSIBILITY=LOSSLESS/LOSSY metadata item in IMAGE_STRUCTURE
- JPEGXL: report a COMPRESSION_REVERSIBILITY=LOSSLESS (possibly)/LOSSY metadata item in IMAGE_STRUCTURE
- GTiff: report a COMPRESSION_REVERSIBILITY=LOSSLESS (possibly)/LOSSY metadata item in IMAGE_STRUCTURE for WEBP and JXL compression
    * Requires reading the header of one tile/strip and the availability of the standalone WEBP and JPEGXL drivers.
    * Use that information to set the m_bWebPLossless/m_bJxlLossless flags in update mode
- GTiff: read/write JPEGXL and WEBP compression parameters (for main dataset only) in IMAGE_STRUCTURE metadata domain of GDAL_METADATA tag

### CODE REVIEW

**Comment by idanaviv10** [comment]
Hi, 
This is a great feature, and it will help a lot. 
Is there any way to do it also for the overviews ? 
Another thing that might help is to have the quality of the layer (1-100), would this be possible ? 

Thanks in advance, 
Idan

**Comment by rouault** [comment]
> Is there any way to do it also for the overviews ?

yes:
```
$ gdal_translate byte.tif test.tif
$ gdaladdo test.tif 2 --config COMPRESS_OVERVIEW JXL
$ gdalinfo test.tif -oo OVERVIEW_LEVEL=0
[...}
Image Structure Metadata:
  COMPRESSION=JXL
  COMPRESSION_REVERSIBILITY=LOSSLESS (possibly)
  INTERLEAVE=BAND
$ python -c "from osgeo import gdal; ds = gdal.Open('test.tif'); print(ds.GetRasterBand(1).GetOverview(0).GetDataset().GetMetadata('IMAGE_STRUCTURE'))"
{'COMPRESSION': 'JXL', 'COMPRESSION_REVERSIBILITY': 'LOSSLESS (possibly)', 'INTERLEAVE': 'BAND'}
```

> Another thing that might help is to have the quality of the layer (1-100), would this be possible ?

that's not something encoded in the codestream of JPEGXL or WEBP. This could only be done by adding some GDAL specific metadata. I'm considering it

**Comment by idanaviv10** [comment]
Great! 
Having the quality level is something that will really help in situation where you need compare raster with different qualities of the compression. Today is kind of horrible to do it (you must write it down yourself and hope not to make a mistake, and working with a team is even harder).
I hope you will add it to the gdal specific metadata, this will make my life far more easier :)

Thanks in advance,
Idan

**Comment by rouault** [comment]
> I hope you will add it to the gdal specific metadata, this will make my life far more easier :)

done

**Comment by idanaviv10** [comment]
Thank you so much !! 
You made my life now so much better :)

**Comment by idanaviv10** [comment]
Hi,
Is there a way to get the quality of the compression for a specific overview ? 
When I try to use the `gdalinfo  output.tif -oo OVERVIEW_LEVEL=0` I don't get the WEBP_LEVEL in the Image Structure Metadata.

**Comment by jratike80** [comment]
Your use case about using different quality settings for each overview level feels rather uncommon. Maybe if you have customized workflows you could consider to use also customized metadata items. You wrote
> you must write it down yourself and hope not to make a mistake

but maybe it could be helped by adding some automation into your processes like creating overviews with a script that automatically writes the applied overview quality into image metadata. Simple example with gdal_edit about the last part.

```
...
gdal_edit -mo "overview_quality=0:100;1:80,2:70" test.tif

gdalinfo test.tif
Metadata:
  AREA_OR_POINT=Area
  overview_quality=0:100;1:80,2:70
  TIFFTAG_RESOLUTIONUNIT=3 (pixels/cm)
  TIFFTAG_XRESOLUTION=0.393677
  TIFFTAG_YRESOLUTION=0.393677
```

**Comment by idanaviv10** [comment]
>  In that case, if the quality of the first overview is 70%, who can tell what is the quality of the second overview that is compressed again with 70% quality settings?
Is creating all the overviews together works differently (using gdalaldo), each overview will be created from the full resolution or it will be created from the next higher resolution overview?  

> It is common to have a different compression for full resolution and overviews
I totally agree, it might worth in the future to have a section in the metadata saying what is the quality of the overviews (all of them as this is a common use case). For now I am considering using your advice for using gdal_edit or something similar in code.

**Pull request merged**
