### PR TITLE
Doc: insert space character in :choices: output, to be nice with browsers line-break insertion logic

### LINKED ISSUE #10778: Docs: incorrect display of long lines (using Chrome on Windows 10)
### What is the bug?

Using Google Chrome 128.0.6613.138 on Windows 10:

image

The horizontal scrolling bar is not available.

### Steps to reproduce the issue

Open https://gdal.org/en/latest/drivers/vector/filegdb.html using Google Chrome on Windows 10.

### Versions and provenance

Windows 10 Home 1903 64-bit 10.0.18362 Build 18362.778

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10778

### CODE REVIEW

**Comment by jratike80** [comment]
By https://stackoverflow.com/questions/24488950/css-to-break-a-line-only-on-a-certain-character there is also a character called ZERO WIDTH SPACE (U+2000B). But maybe such invisible space could make more confusion than traditional space.

**Comment by rouault** [comment]
> By https://stackoverflow.com/questions/24488950/css-to-break-a-line-only-on-a-certain-character there is also a character called ZERO WIDTH SPACE (U+2000B). But maybe such invisible space could make more confusion than traditional space.

Thanks for the hint. Let's test this hypothesis in https://github.com/OSGeo/gdal/pull/10782

**Comment by rouault** [comment]
ok, so we have the RTD preview of this pull request in https://gdal--10781.org.readthedocs.build/en/10781/drivers/vector/filegdb.html

**Comment by rouault** [comment]
superseded per https://github.com/OSGeo/gdal/pull/10782

**Pull request closed without merging**
