### PR TITLE
Google cloud - Support type=authorized_user JSON file for authentication

### PR DESCRIPTION
**Pull request by AndreaGiardini**
## What does this PR do?

Google cloud provides two types of JSON files: `service_account` and `authorized_user`.
Inside the JSON file, the key named `type` distinguishes between the two.

By default, whenever we set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, gdal assumes the JSON file is of type `service_account` and expects to find a key named `private_key` in there.

In reality, when a user runs `gcloud auth application-default login`, the JSON file is of type `authorized_user`. In this case, the `access_key`, `secret_key` and `refresh_token` will be available, but there will be no `private_key`.

With this pull request we introduce support for `authorized_user` JSON files.

To work around this problem until now:
* we avoided setting the `GOOGLE_APPLICATION_CREDENTIALS` env variable
* we used to set the correct environment variables using this script:
```
jq -r 'to_entries[] | "GS_OAUTH2_" + (.key | ascii_upcase) + "=" + .value' \
   $HOME/.config/gcloud/application_default_credentials.json
```
That would generate these env variables:
```
GS_OAUTH2_CLIENT_ID=xxx
GS_OAUTH2_CLIENT_SECRET=xxx
GS_OAUTH2_QUOTA_PROJECT_ID=xxx
GS_OAUTH2_REFRESH_TOKEN=xxx
GS_OAUTH2_TYPE=authorized_user
```

---

I tested the PR locally. 

Before:

```
$ GOOGLE_APPLICATION_CREDENTIALS='/home/andrea/.config/gcloud/application_default_credentials.json' gdalinfo /vsigs/bucket/xxx_002d_20180529.tif

ERROR 1: Private key should be set
ERROR 1: Private key should be set
ERROR 1: Private key should be set
ERROR 1: Private key should be set
ERROR 1: Private key should be set
ERROR 1: Private key should be set
gdalinfo failed - unable to open '/vsigs/bucket/xxx_002d_20180529.tif'.
```

After:

```
$ GOOGLE_APPLICATION_CREDENTIALS='/home/andrea/.config/gcloud/application_default_credentials.json' gdalinfo /vsigs/bucket/xxx_002d_20180529.tif

Driver: GTiff/GeoTIFF
Files: /vsigs/bucket/xxx_002d_20180529.tif
Size is 13460, 6768
Coordinate System is:
[...]
```

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by AndreaGiardini** [comment]
@rouault I added the tests as you suggested. Let me know if you have other comments

**Comment by rouault** [comment]
The bullet in https://github.com/OSGeo/gdal/blob/master/doc/source/user/virtual_file_systems.rst#vsigs-google-cloud-storage-files about GOOGLE_APPLICATION_CREDENTIALS probably needs some tweaking.

**Comment by AndreaGiardini** [comment]
@rouault That should be fixed now

**Comment by AndreaGiardini** [comment]
Thank you @rouault . Do you have a timeline for the release of 3.4.2?

**Comment by rouault** [comment]
> Do you have a timeline for the release of 3.4.2?

==> https://github.com/OSGeo/gdal/milestone/35

**Pull request merged**
