### PR TITLE
Fix compiling for ios

### PR DESCRIPTION
**Pull request by m-kuhn**
"Darwin" matches osx only

### CODE REVIEW

**Comment by rouault** [comment]
Did you test on a recent enough master ? https://github.com/OSGeo/gdal/pull/6024 address iOS build issues in a different way

**Comment by m-kuhn** [comment]
I tested 3.5.2 only, patching with https://github.com/OSGeo/gdal/pull/6024 now

**Comment by m-kuhn** [comment]
I can confirm https://github.com/OSGeo/gdal/pull/6024 works, but this one looks simpler and I'm not sure https://github.com/OSGeo/gdal/pull/6024 has other advantages?

**Comment by rouault** [comment]
> I can confirm #6024 works, but this one looks simpler and I'm not sure #6024 has other advantages?

It was found by the reporter of what lead to #6024 that your approach helped, but was not sufficient (there were compilation errors with statsvfs64 for example). See thread https://lists.osgeo.org/pipermail/gdal-dev/2022-July/thread.html#56026 . Perhaps there was some oddity in the build environment of the reporter...

**Comment by m-kuhn** [comment]
In this case let's stick to https://github.com/OSGeo/gdal/pull/6024

**Pull request closed without merging**
