### PR TITLE
MITAB: Disable table fields "laundering" for non-neutral charset and add UTF-8 charset

### PR DESCRIPTION
**Pull request by drons**
Try to fix https://github.com/Toblerity/Fiona/issues/1399

Unfortunately, I do not have a modern version of MapInfo to check the correctness.

### CODE REVIEW

**Comment by rouault** [comment]
@jratike80 Do you have access to recent MapInfo? If so it could be useful if you could provde a .mif/.mid and/or .tab using UTF-8 encoding

**Comment by rouault** [comment]
> If so it could be useful if you could provde a .mif/.mid and/or .tab using UTF-8 encoding

and possibly with non-ASCII field names

**Comment by rouault** [comment]
@drons This doesn't build

**Comment by drons** [comment]
NB! utf8 mid/mif was generated using iconv utility, requires verification with MapInfo.

**Comment by drons** [comment]
@rouault maybe `std::iswalpha` is a more suitable function for a "laundering"?

**Comment by rouault** [comment]
> `std::iswalpha` is a more suitable function for a "laundering"?

I don't know what constraints MapInfo set, if any...

**Comment by drons** [comment]
> I don't know what constraints MapInfo set, if any...
There is a comment in [GDAL](https://github.com/OSGeo/gdal/blob/d06db897f0982f2f60b0f3a092700c6cdedd0c67/ogr/ogrsf_frmts/mitab/mitab_utils.cpp#L471) code about oldie MapInfo fields name constraints. But there are weak constraints at resent [MapInfo](https://docs.precisely.com/docs/sftw/mapinfo-pro/v2021/en-us/pdf/mapinfo-pro-v2021-user-guide.pdf#_OPENTOPIC_TOC_PROCESSING_d6230e245058).

**Comment by rouault** [comment]
> But there are weak constraints at resent [MapInfo](https://docs.precisely.com/docs/sftw/mapinfo-pro/v2021/en-us/pdf/mapinfo-pro-v2021-user-guide.pdf#_OPENTOPIC_TOC_PROCESSING_d6230e245058).

so maybe relax / remove laundering if we generate for a recent MapInfo version?

**Comment by drons** [comment]
I'll think about testcase

**Comment by rouault** [comment]
> I'll think about testcase

thanks, and some documentation for the new option in doc/source/drivers/vector/mitab.rst
By the way, I've just merged https://github.com/OSGeo/gdal/pull/10291 into master. It would be great if you could rebase your PR on top of it, and add the UTF-8 entry in the [doc/source/drivers/vector/mapinfo_encodings.csv](https://github.com/OSGeo/gdal/pull/10291/files#diff-d24cdd6c6ec8ff126bf3b5433de848c446b8b6dcc30565d33e3de8ee9040cc3e) file

**Pull request merged**
