### PR TITLE
Python bindings: replace unsafe use of tempfile.mktemp() by mkstemp()…

### PR DESCRIPTION
**Pull request by rouault**
… (fixes https://huntr.dev/bounties/59e93871-266a-40be-9aad-4576d3dc48f2/)

CC @idanmiara I'm not sure if all those code paths are tested

### CODE REVIEW

**Comment by idanmiara** [comment]
> … (fixes https://huntr.dev/bounties/59e93871-266a-40be-9aad-4576d3dc48f2/)
> 
> CC @idanmiara I'm not sure if all those code paths are tested

The report in the link is not public.

I'm looking now at the tests.

**Comment by rouault** [comment]
> The report in the link is not public.

they just point to the fact that tempfile.mktemp() is deprecated and potentially insecure, and mkstemp() should be used instead. The security risk in the GDAL context is probably low in practice, but better use the recommended approach.

**Comment by idanmiara** [comment]
> > The report in the link is not public.
> 
> they just point to the fact that tempfile.mktemp() is deprecated and potentially insecure, and mkstemp() should be used instead. The security risk in the GDAL context is probably low in practice, but better use the recommended approach.

Thanks for this clarification.

**Comment by idanmiara** [comment]
3/4 of the effected functions are tested.
`extent_util.make_temp_vrt` is not tested (it is used in gdal_calc if `extent not in [Extent.IGNORE, Extent.FAIL]`).
I shall add tests for this functionality in another commit. I have some previous commitments to fulfill first.

**Comment by rouault** [comment]
@idanmiara is it good for merging or do you want to have a deeper look ?

**Comment by idanmiara** [comment]
Yes, went over it. Looks good to me. Thanks!

**Pull request merged**
