### PR TITLE
Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
hum, the version selector appears as white-over-white... any idea @dbaston  ?

**Comment by rouault** [comment]
ok, I'm merging this to avoid pull requests to be "red". Attempt at sticking to sphinx-rtd-theme 2.0 done in https://github.com/OSGeo/gdal/pull/10956 doesn't lead to better results...

**Comment by rouault** [comment]
The backport to `release/3.9` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply c418dde090... Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
CONFLICT (modify/delete): .github/workflows/doc_checks.yml deleted in HEAD and modified in c418dde090 (Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0).  Version c418dde090 (Doc: use 'version_selector' instead of 'display_version' which is deprecated by sphinx-rtd-theme 3.0.0) of .github/workflows/doc_checks.yml left in tree.
Auto-merging doc/source/conf.py

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.9 release/3.9
# Navigate to the new working tree
cd .worktrees/backport-release/3.9
# Create a new branch
git switch --create backport-10954-to-release/3.9
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick c418dde0908dcb7187b54788f9b9b380f7b4c31c,5de2b509ad7664c1e08cc7dbcb8532be7b9fa49c
# Push it to GitHub
git push --set-upstream origin backport-10954-to-release/3.9
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.9
```
Then, create a pull request where the `base` branch is `release/3.9` and the `compare`/`head` branch is `backport-10954-to-release/3.9`.

**Comment by rouault** [comment]
first commit manually backported to 3.9 per 501754d048e07b07932ec268b6ed3c43ea0819e3

**Comment by dbaston** [comment]
> hum, the version selector appears as white-over-white... any idea @dbaston ?

Just getting to this now, but gdal.org looks OK to me. Let me know if there's still anything for me to look into.

**Comment by rouault** [comment]
> Just getting to this now, but gdal.org looks OK to me. Let me know if there's still anything for me to look into.

yes, I believe we're good now. See https://github.com/OSGeo/gdal/issues/10680#issuecomment-2398015889 for related changes (didn't want to step over your toes on this, but CI got broken because of the sphinx-rtd-theme 3.0.0 update and one thing led to another... including my struggling with CSS 🤮)

**Pull request merged**
