### PR TITLE
SAFE (Sentinel1): multiple improvements related to SLC/calibration

### PR DESCRIPTION
**Pull request by rouault**
Contributed by Esri

### CODE REVIEW

**Comment by rouault** [comment]
@oarcher / @agrouaze  As I see you had interest in that driver and I'm not a specialist of that domain, if you could give that a try to this pull request, that would be welcome

**Comment by oarcher** [comment]
@agrouaze, what we can do is to compare the xsar calibration with this new GDAL slc calibration. Do you have some time to do this ?

**Comment by agrouaze** [comment]
I can do the comparison, but not this week.

**Comment by rouault** [comment]
> I can do the comparison, but not this week.

ok, I'll merge this then. But do not hesitate to provide feedback when you've a chance

**Pull request merged**
