### PR TITLE
Experimental fix TIFF files reading with one big stripe

### PR DESCRIPTION
**Pull request by drons**
This is continuation of pull request https://github.com/OSGeo/gdal/pull/90
I'm not 100% feel certain in this changeset, but it fix problem with one stripe TIFF files.

### CODE REVIEW

**Comment by rouault** [comment]
Could you post the output of tiffdump on the tiff file you're trying to make recognized ?

**Comment by drons** [comment]
```
1.tif:
Magic: 0x4949 <little-endian> Version: 0x2a <ClassicTIFF>
Directory 0: offset 88 (0x58) next 0 (0)
ImageWidth (256) LONG (4) 1<3104>
ImageLength (257) LONG (4) 1<2430>
BitsPerSample (258) SHORT (3) 1<16>
Compression (259) SHORT (3) 1<1>
Photometric (262) SHORT (3) 1<1>
PlanarConfig (284) SHORT (3) 1<1>
StripOffsets (273) LONG (4) 1<202>
MinSampleValue (280) SHORT (3) 1<0>
MaxSampleValue (281) SHORT (3) 1<1023>
```

**Comment by drons** [comment]
Yesterday i'm run git bisect with 'gdalinfo my_file.tif' and found first broken commit.
git 1f0d59a
svn: trunk@28198

**Comment by rouault** [comment]
Should be fixed per https://trac.osgeo.org/gdal/ticket/6490 . My fix is a bit more restrictive, but you spotted the right place.

**Pull request closed without merging**
