### PR TITLE
Lerc: resync with Esri/lerc@cfe2057 and remove Lerc V1 compression for MRF driver

### PR DESCRIPTION
**Pull request by rouault**
@lucianpls This is a preliminary step for adding a LERC codec for TIFF compression, as discussed with @rprinceley

This is not exactly  Esri/lerc@cfe2057 , but quite close to it. Differences are 0 -> nullptr, a few cppcheck annotations and some bound checking found through oss-fuzz that seems to be missing from the Esri/lerc repo (hopefully I haven't lost existing bound checking in other places, we'll see...)

### CODE REVIEW

**Comment by lucianpls** [comment]
Please don't do this.  LERC V1 is essential for compatibility with Esri's terrain tiles.

**Comment by lucianpls** [comment]
Removing LERC V1 is not acceptable.  It is required for compatibility with Esri terrain tiles, and many of the older clients

**Comment by rouault** [comment]
> Removing LERC V1 is not acceptable. It is required for compatibility with Esri terrain tiles, and many of the older clients

Eh, I just pulled an ESRI repository ;-) In case the commit message is not clear: this just removes the LercV1 *writing*. The read side is still preserved

**Comment by lucianpls** [comment]
MRF needs to have both reading and writing capabilities, which is why that code was there in the first place.

**Comment by rouault** [comment]
Putting this on hold as requested per @rprinceley . Closing this PR without merging it

**Pull request closed without merging**
