### PR TITLE
type hints fix and variable init

### PR DESCRIPTION
**Pull request by idanmiara**
## What does this PR do?

fix some minor bugs for GDAL 3.3
`color_table.py` - fix some inaccurate type hints
`gdalattachpct.py` -  `driver_name` was not initialized so it might crash if no `-of` is provided.

### CODE REVIEW

**Comment by idanmiara** [comment]
@rouault this fix should be backported also to 3.3.
What is the recommended path for fixes? rebase on 3.3 and then after it's merged to master we merge/cherry pick it to master or rebase on master and cherry pick to 3.3 ? or something else?

**Comment by rouault** [comment]
> fix some minor bugs for GDAL 3.3

What does that fix exactly ? Which tests demonstrate the need for that ?
You can use the "backport release/3.3" tag for that, and once the main PR is merged the backport bot opens a new PR against the targetted branch

**Comment by idanmiara** [comment]
> > fix some minor bugs for GDAL 3.3
> 
> What does that fix exactly ? Which tests demonstrate the need for that ?
> You can use the "backport release/3.3" tag for that, and once the main PR is merged the backport bot opens a new PR against the targetted branch

For the type hints fix, it's mainly for IDE hints as the interpreter ignores them anyway.
As for `gdalattachpct.py` it might crash if no `-of` is provided as `driver_name` was not initialized.
I can make a test for that but I think it's rather an esoteric/random test.
Overall it is a minor fix so we can also drop the backport.

**Comment by idanmiara** [comment]
I don't think I have permissions for setting tags.

**Comment by rouault** [comment]
OK, I'll merge this with the backport tag. But as you rework a lot of Python operational code, there should be an equivalent, if not bigger activity, on the testing side as well (as an example of humility for all of us: SQLite3 has more than 100 times more testing code than operational code : https://www.sqlite.org/testing.html)

**Comment by rouault** [comment]
> I don't think I have permissions for setting tags.

I've sent you an invite with the "triage" permission that should enable you to set labels

I see the automatic backport failed (the backport bot hasn't been used much and might be broken). Please create a new PR against release/3.3 manually

**Comment by idanmiara** [comment]
> > I don't think I have permissions for setting tags.
> 
> I've sent you an invite with the "triage" permission that should enable you to set labels
> 
> I see the automatic backport failed (the backport bot hasn't been used much and might be broken). Please create a new PR against release/3.3 manually

Thanks!

**Comment by idanmiara** [comment]
> OK, I'll merge this with the backport tag. But as you rework a lot of Python operational code, there should be an equivalent, if not bigger activity, on the testing side as well (as an example of humility for all of us: SQLite3 has more than 100 times more testing code than operational code : https://www.sqlite.org/testing.html)

I see your point... I will start investing more energy into that.

**Pull request merged**
