### PR TITLE
Doc: insert Unicode zero-width space character in :choices: output, to be nice with browsers line-break insertion logic

### LINKED ISSUE #10778: Docs: incorrect display of long lines (using Chrome on Windows 10)
### What is the bug?

Using Google Chrome 128.0.6613.138 on Windows 10:

image

The horizontal scrolling bar is not available.

### Steps to reproduce the issue

Open https://gdal.org/en/latest/drivers/vector/filegdb.html using Google Chrome on Windows 10.

### Versions and provenance

Windows 10 Home 1903 64-bit 10.0.18362 Build 18362.778

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10778

### CODE REVIEW

**Comment by jratike80** [comment]
Wouldn't it be enough to add zero width space just on one side of `/`?

**Comment by rouault** [comment]
> Wouldn't it be enough to add zero width space just on one side of `/`?

presumably, but this would lack symmetry (and I'm not going to enter political debates whether left or right should be preferred) :-) :-)

**Comment by rouault** [comment]
@jratike80 @agiudiceandrea Could you check if https://gdal--10782.org.readthedocs.build/en/10782/drivers/vector/filegdb.html renders correctly for you?

**Comment by jratike80** [comment]
Renders fine for me on Windows with Chrome 128.0.6613.120 and with Edge 128.0.2739.67

**Comment by agiudiceandrea** [comment]
Renders fine also for me 
image

**Pull request merged**
