### PR TITLE
gdaldem: syncing all datatypes to 64-bit float for faster shading on 64bit machines

### PR DESCRIPTION
**Pull request by Komzpa**
Shaves off 15% of hillshade generation time on my machine/dataset.

### CODE REVIEW

**Comment by rouault** [comment]
- There are a few unnecessary whitespace changes in lines not changed otherwise
-  A side effect of this commit is that the output of the slope, aspect, TRI, TPI and roughness algorithms is now Float64 instead of Float32 (i.e. twice larger files). We probably don't need that much of output precision (and the gdaldem manual in apps/gdal_utilities.dox explicitely mentions 32-bit floating point). So you should probably only acquire data on Float64, but still output Float32 (in the non Byte cases)

**Comment by Komzpa** [comment]
@rouault should I not change whitespace at all, or separate it into a "tidying" commit?

As for further profiling, one of the slowest parts now is ARE_REAL_EQUAL define, which probablt should be rewritten into something like AlmostEqual2sComplement from http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm (but I lack skills to make it polymorphic for both float and double in current code layout).

**Comment by rouault** [comment]
I'd prefer avoiding the whitespace changes completely.

**Comment by rouault** [comment]
Substantial speed improvements have been made into trunk, in particular when the input DEM is byte/int16. Closing this PR under the assumption that the trunk improvements make it obsolete

**Pull request closed without merging**
