### PR TITLE
FlatGeobuf writing: in SPATIAL_INDEX=NO mode, deal with empty geometries as if there were null

### LINKED ISSUE #11419: Segmentation fault when writing an empty polygon to FlatGeobuf
### What is the bug?

This simple script using the Python bindings ends in a segmentation fault. It doesn't appear to fail using another driver, for example `GPKG`.

It also doesn't fail in this way without `SPATIAL_INDEX=NO`... in that case it (correctly) refuses to write the empty polygon because an empty geometry cannot be indexed spatially.

```Python
from osgeo import gdal, ogr
gdal.UseExceptions()

drv = ogr.GetDriverByName("FlatGeobuf")
ds = drv.CreateDataSource("test.fgb")
layer = ds.CreateLayer("test.fgb", geom_type=ogr.wkbPolygon, options=["SPATIAL_INDEX=NO"])

feat_def = layer.GetLayerDefn()
empty_feat = ogr.Feature(feat_def)
empty_poly = ogr.Geometry(ogr.wkbPolygon)
empty_feat.SetGeometry(empty_poly)
layer.CreateFeature(empty_feat)

empty_feat = None
ds = None
```

### Steps to reproduce the issue

To reproduce, run the sample script in the bug description. I tested this using the latest Docker image, `ghcr.io/osgeo/gdal:ubuntu-small-3.10.0`:

```bash
docker run -it --rm -v ~/work:/data ghcr.io/osgeo/gdal:ubuntu-small-3.10.0 bash
cd /data
python test.py
```

This results in:
```
Segmentation fault (core dumped)
```

### Versions and provenance

Reproduced in the latest Docker image `ghcr.io/osgeo/gdal:ubuntu-small-3.10.0`, although it also happened in earlier versions. (For example, 3.8.5 built on a MacBook.)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
- this fixes the crash when writing an empty polygon. Fixes #11419
- this avoids a reading error when writing an empty line

@bjornharrtell Can you confirm that FlatGeobuf is not a fan of EMPTY geometries ?

### CODE REVIEW

**Comment by bjornharrtell** [comment]
@rouault confirmed. I either like to pretend they do not exist or treat them as null geometry.

**Comment by rouault** [comment]
Also add support for writing a file without feature in SPATIAL_INDEX=NO mode ( @bjornharrtell no reason why we should disallow this, right ? since writing empty files in SPATIAL_INDEX=YES mode already works)

**Comment by bjornharrtell** [comment]
> Also add support for writing a file without feature in SPATIAL_INDEX=NO mode ( @bjornharrtell no reason why we should disallow this, right ? since writing empty files in SPATIAL_INDEX=YES mode already works)

No, must been an oversight that it wasn't doing so already.

**Comment by rouault** [comment]
The backport to `release/3.10` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply e1f2404082... FlatGeobuf writing: in SPATIAL_INDEX=NO mode, deal with empty geometries as if there were null
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/ogr/ogr_flatgeobuf.py
CONFLICT (content): Merge conflict in autotest/ogr/ogr_flatgeobuf.py
Auto-merging ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.10 release/3.10
# Navigate to the new working tree
cd .worktrees/backport-release/3.10
# Create a new branch
git switch --create backport-11420-to-release/3.10
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick e1f240408258b7505c80582721509110226848dc,c59ee2217869fb3ee5af5be28a48c653ac07f576
# Push it to GitHub
git push --set-upstream origin backport-11420-to-release/3.10
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.10
```
Then, create a pull request where the `base` branch is `release/3.10` and the `compare`/`head` branch is `backport-11420-to-release/3.10`.

**Comment by rouault** [comment]
cherry-picked to 3.10 per 340f72f58afbf8f00e7c6f2f83da5ec08b2a7d5f and f3e4b05b9a64968bd37305da1ef6b06d0e0b2200

**Pull request merged**
