### PR TITLE
HANA: Add support for fast extent estimation

### PR DESCRIPTION
**Pull request by jatsqi**
## What does this PR do?

With QRC/1 2024 a new and faster way to estimate extents of spatial column has been added to HANA.
More precisely, users can now use special columns in [this table](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-spatial-reference/spatial-extent-with-sys-m-st-geometry-columns?locale=en-US) to get an estimation of the extent of a spatial column.
Even though the stored extent is only an estimation, it is often good enough.
Especially for very large tables costly aggregation functions are avoided every time the extent is recomputed.
The extent information in the mentioned HANA table is only available after a delta-merge, so a fallback to the standard behaviour, i.e. via aggregation functions, was added in case the data is unavailable or has not yet been computed.

## What are related issues/pull requests?

None.

## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [x] Add test case(s)
 - [x] Add documentation (no documentation required, this change is not user-facing)
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by rouault** [comment]
Python linting issue. Cf https://github.com/OSGeo/gdal/actions/runs/10214824460/job/28264531781?pr=10543

**Comment by jatsqi** [comment]
Ah thanks @rouault, seems like I forgot to run the linter for this.

**Comment by rouault** [comment]
@jatsqi Now that it has been merged, it seems it causes random failures in test_ogr_hana_39(). See https://github.com/OSGeo/gdal/actions/runs/10253377428/job/28365852783?pr=10549 . Can you have a look at that?

**Comment by jatsqi** [comment]
@rouault I'll have a look right away 👍

**Comment by jatsqi** [comment]
@rouault I did some digging and talked with a colleague about this, and it seems that it is not that straightforward to test this, but I'm convinced the implementation itself is correct.
I've opened a PR #10553 for this, so at least the pipeline is no longer failing for new PRs.

**Pull request merged**
