### PR TITLE
CSW: Add 'title' as query-able property

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## What does this PR do?

Adds 'title' as query-able property for the CSW driver.

I'm not sure if a corresponding "other_titles" should also be added or not. I think not.

## What are related issues/pull requests?

This should fix https://github.com/OSGeo/gdal/issues/6718.

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by rouault** [comment]
Did you test this actually work ?

> I'm not sure if a corresponding "other_titles" should also be added or not. I think not.

yeah, I don't think it is needed (I should have added comment to explain those other_ stuff. can't remember for my life what my intention was...)

**Comment by agiudiceandrea** [comment]
> this actually work ?

executing the command reported in the issue report:
`ogrinfo --debug on -ro -al "CSW:http://www.pcn.minambiente.it/geoportal/csw" -where "title LIKE 'strutture'"`
the error `ERROR 1: "title" not recognised as an available field.` is no longer displayed and the command returns the following output:
```
INFO: Open of `CSW:http://www.pcn.minambiente.it/geoportal/csw'
      using driver `CSW' successful.

Layer name: records
Geometry: Polygon
Feature Count: 0
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Geometry Column = boundingbox
identifier: String (0.0)
other_identifiers: StringList (0.0)
title: String (0.0)
type: String (0.0)
subject: String (0.0)
other_subjects: StringList (0.0)
references: String (0.0)
other_references: StringList (0.0)
modified: String (0.0)
abstract: String (0.0)
date: String (0.0)
language: String (0.0)
rights: String (0.0)
format: String (0.0)
other_formats: StringList (0.0)
creator: String (0.0)
source: String (0.0)
anytext: String (0.0)
```

While using the command `ogrinfo -ro -al "CSW:http://www.pcn.minambiente.it/geoportal/csw" -where "title LIKE '%strutture%'"`: 

the output is:
```
INFO: Open of `CSW:http://www.pcn.minambiente.it/geoportal/csw'
      using driver `CSW' successful.

Layer name: records
Geometry: Polygon
Feature Count: 3
Extent: (6.000000, 35.200000) - (19.885300, 47.200000)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Geometry Column = boundingbox
identifier: String (0.0)
other_identifiers: StringList (0.0)
type: String (0.0)
subject: String (0.0)
other_subjects: StringList (0.0)
references: String (0.0)
other_references: StringList (0.0)
modified: String (0.0)
abstract: String (0.0)
date: String (0.0)
title: String (0.0)
rights: String (0.0)
format: String (0.0)
other_formats: StringList (0.0)
creator: String (0.0)
source: String (0.0)
anytext: String (0.0)
OGRFeature(records):1
  identifier (String) = m_amte:299FN3:92c57f6d-aed7-4ca3-c1e1-671d80feb115
  other_identifiers (StringList) = (1:{2E066D2E-3261-4F7A-9827-1688639A0599})
  title (String) = Atlante nazionale delle aree a rischio di desertificazione - Indice di impatto: aree urbane e principali infrastrutture
  type (String) = downloadableData
  subject (String) = aree naturali
  other_subjects (StringList) = (7:paesaggio,ecosistemi,desertificazione,Nazionale,RNDT,EU,geoscientificInformation)
  references (String) = http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/Atlante_desertificazione.map&service=wms&request=getCapabilities&version=1.3.0
  other_references (StringList) = (4:http://wms.pcn.minambiente.it/wcs/DES_URBANO?service=wcs&request=getCapabilities,http://www.pcn.minambiente.it/anteprima/DES_URB
ANO.gif,http://www.pcn.minambiente.it/geoportal/csw?getxml=%7B2E066D2E-3261-4F7A-9827-1688639A0599%7D,http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/A
tlante_desertificazione.map&service=wms&request=getCapabilities&version=1.3.0)
  modified (String) = 2022-11-29T16:00:20+01:00
  abstract (String) = Il Ministero dellAmbiente e della Tutela del Territorio ha finanziato con atto del 28-12-2001 l'Istituto Sperimentale per lo Studio e la Difesa
 del Suolo di Firenze per la ''Predisposizione di Atlante Nazionale delle aree a rischio di desertificazione'' alla scala di riconoscimento (scale di riferimento 1:1
00.000 - 1.250.000). Il MATTM considera tale Atlante strumento propedeutico alla corretta attuazione del Piano Nazionale per la Lotta alla Siccit├á e Desertificazion
e, adottato dallo Stato Italiano in attuazione della Convenzione delle Nazioni Unite per la Lotta alla Siccit├á ed alla Desertificazione. Nel sopracitato atto ├¿ pre
vista la partecipazione dell'Istituto Nazionale di Economia Agraria nei suoi specifici settori di competenza. L'area di studio comprende Abruzzo, Basilicata, Calabri
a, Campania, Lazio, Marche, Molise Puglia, Sardegna, Sicilia, Toscana, Umbria. Le aree urbane, cos├¼ come le principali infrastrutture, sono superfici caratterizzate
 dalla perdita irreversibile della funzionalit├á produttiva ed ecologica del suolo.
  POLYGON ((8.082 35.2153,19.8853 35.2153,19.8853 44.204,8.082 44.204,8.082 35.2153))

OGRFeature(records):2
  identifier (String) = m_amte:299FN3:ad5f561e-1e56-4b2b-f504-fe4ff7a9e446
  other_identifiers (StringList) = (1:{F8703C77-1DFF-412B-9604-F7FB3AF02DBD})
  title (String) = Infrastrutture ferroviarie - Tratte ferroviarie
  type (String) = downloadableData
  subject (String) = Nazionale
  other_subjects (StringList) = (7:ferrovia,rete ferroviaria,infrastrutture per il traffico,trasporti,RNDT,EU,transportation)
  references (String) = http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0
  other_references (StringList) = (4:http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Rete_ferroviaria.map&service=wfs&request=getCapabilities,http://www.pcn.minamb
iente.it/anteprima/ferrovie.gif,http://www.pcn.minambiente.it/geoportal/csw?getxml=%7BF8703C77-1DFF-412B-9604-F7FB3AF02DBD%7D,http://wms.pcn.minambiente.it/ogc?map=/
ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0)
  modified (String) = 2022-12-06T15:17:49+01:00
  abstract (String) = Il progetto Strati Prioritari di Interesse Nazionale (DBPrior10k), ├¿ stato realizzato nellambito dell'Intesa Stato-Regioni-Enti Locali sui Sis
temi Informativi Geografici (IntesaGIS) a partire dal settembre 2003, ed ├¿ stato consegnato dal Centro Interregionale, che ne ha svolto la direzione lavori, agli En
ti Committenti (Regione Basilicata, Ministero dell'Ambiente) nel giugno 2005. Nel dicembre 2006 la RSDE su incarico del CTC IntesaGIS ha completato l'attivit├á di pu
bblicazione del DBPRIOR10K su www.IntesaGIS ed omogeneizzazione preliminare del grafo della viabilit├á. Le attivit├á svolte nel 2007 dal Centro Interregionale hanno
portato all'integrazione dei dati che ancora mancavano al fine di completare l'intera copertura nazionale. Per la viabilit├á ferroviaria sono state acquisite tutte l
e ferrovie del territorio nazionale, sia appartenenti alle Ferrovie dello Stato che ad altre compagnie. Gli strati informativi relativi alle infrastrutture ferroviar
ie sono costituiti da elementi lineari e puntuali. Gli elementi lineari individuano la tratta ferroviaria.
  POLYGON ((6.0 35.2,19.7 35.2,19.7 47.2,6.0 47.2,6.0 35.2))

OGRFeature(records):3
  identifier (String) = m_amte:299FN3:e44e45a0-f439-4c6e-d3a0-9cbf76e117d4
  other_identifiers (StringList) = (1:{E40B7C2E-DA71-47F3-96E1-57162942BB73})
  title (String) = Infrastrutture ferroviarie - Nodi ferroviari
  type (String) = downloadableData
  subject (String) = Nazionale
  other_subjects (StringList) = (7:ferrovia,rete ferroviaria,infrastrutture per il traffico,trasporti,RNDT,EU,transportation)
  references (String) = http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0
  other_references (StringList) = (4:http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Rete_ferroviaria.map&service=wfs&request=getCapabilities,http://www.pcn.minamb
iente.it/anteprima/ferrovie.gif,http://www.pcn.minambiente.it/geoportal/csw?getxml=%7BE40B7C2E-DA71-47F3-96E1-57162942BB73%7D,http://wms.pcn.minambiente.it/ogc?map=/
ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0)
  modified (String) = 2022-12-06T15:19:17+01:00
  abstract (String) = Il progetto Strati Prioritari di Interesse Nazionale (DBPrior10k), ├¿ stato realizzato nell'ambito dell'Intesa Stato-Regioni-Enti Locali sui Si
stemi Informativi Geografici (IntesaGIS) a partire dal settembre 2003, ed ├¿ stato consegnato dal Centro Interregionale, che ne ha svolto la direzione lavori, agli E
nti Committenti (Regione Basilicata, Ministero dell'Ambiente) nel giugno 2005. Nel dicembre 2006 la RSDE su incarico del CTC IntesaGIS ha completato l'attivit├á di p
ubblicazione del DBPRIOR10K su www.IntesaGIS ed omogeneizzazione preliminare del grafo della viabilit├á. Le attivit├á svolte nel 2007 dal Centro Interregionale hanno
 portato all'integrazione dei dati che ancora mancavano al fine di completare l'intera copertura nazionale. Gli strati informativi relativi alle infrastrutture ferro
viarie sono costituiti da elementi lineari e puntuali. Gli elementi puntuali individuano le intersezioni degli elementi lineari, e sono codificati in modo da descriv
ere il tipo di intersezione che rappresentano.
  POLYGON ((6.0 35.2,19.7 35.2,19.7 47.2,6.0 47.2,6.0 35.2))
```

I don't know if those are the correct results.

**Comment by agiudiceandrea** [comment]
> this actually work ?

executing the command reported in the issue report:
`ogrinfo --debug on -ro -al "CSW:http://www.pcn.minambiente.it/geoportal/csw" -where "title LIKE 'strutture'"`
the error `ERROR 1: "title" not recognised as an available field.` is no longer displayed and the command returns the following output:
```
INFO: Open of `CSW:http://www.pcn.minambiente.it/geoportal/csw'
      using driver `CSW' successful.

Layer name: records
Geometry: Polygon
Feature Count: 0
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Geometry Column = boundingbox
identifier: String (0.0)
other_identifiers: StringList (0.0)
title: String (0.0)
type: String (0.0)
subject: String (0.0)
other_subjects: StringList (0.0)
references: String (0.0)
other_references: StringList (0.0)
modified: String (0.0)
abstract: String (0.0)
date: String (0.0)
language: String (0.0)
rights: String (0.0)
format: String (0.0)
other_formats: StringList (0.0)
creator: String (0.0)
source: String (0.0)
anytext: String (0.0)
```

While using the command `ogrinfo -ro -al "CSW:http://www.pcn.minambiente.it/geoportal/csw" -where "title LIKE '%strutture%'"`: 

the output is:
```
INFO: Open of `CSW:http://www.pcn.minambiente.it/geoportal/csw'
      using driver `CSW' successful.

Layer name: records
Geometry: Polygon
Feature Count: 3
Extent: (6.000000, 35.200000) - (19.885300, 47.200000)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Geometry Column = boundingbox
identifier: String (0.0)
other_identifiers: StringList (0.0)
title: String (0.0)
type: String (0.0)
subject: String (0.0)
other_subjects: StringList (0.0)
references: String (0.0)
other_references: StringList (0.0)
modified: String (0.0)
abstract: String (0.0)
date: String (0.0)
language: String (0.0)
rights: String (0.0)
format: String (0.0)
other_formats: StringList (0.0)
creator: String (0.0)
source: String (0.0)
anytext: String (0.0)
OGRFeature(records):1
  identifier (String) = m_amte:299FN3:92c57f6d-aed7-4ca3-c1e1-671d80feb115
  other_identifiers (StringList) = (1:{2E066D2E-3261-4F7A-9827-1688639A0599})
  title (String) = Atlante nazionale delle aree a rischio di desertificazione - Indice di impatto: aree urbane e principali infrastrutture
  type (String) = downloadableData
  subject (String) = aree naturali
  other_subjects (StringList) = (7:paesaggio,ecosistemi,desertificazione,Nazionale,RNDT,EU,geoscientificInformation)
  references (String) = http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/Atlante_desertificazione.map&service=wms&request=getCapabilities&version=1.3.0
  other_references (StringList) = (4:http://wms.pcn.minambiente.it/wcs/DES_URBANO?service=wcs&request=getCapabilities,http://www.pcn.minambiente.it/anteprima/DES_URB
ANO.gif,http://www.pcn.minambiente.it/geoportal/csw?getxml=%7B2E066D2E-3261-4F7A-9827-1688639A0599%7D,http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/raster/A
tlante_desertificazione.map&service=wms&request=getCapabilities&version=1.3.0)
  modified (String) = 2022-11-29T16:00:20+01:00
  abstract (String) = Il Ministero dellAmbiente e della Tutela del Territorio ha finanziato con atto del 28-12-2001 l'Istituto Sperimentale per lo Studio e la Difesa
 del Suolo di Firenze per la ''Predisposizione di Atlante Nazionale delle aree a rischio di desertificazione'' alla scala di riconoscimento (scale di riferimento 1:1
00.000 - 1.250.000). Il MATTM considera tale Atlante strumento propedeutico alla corretta attuazione del Piano Nazionale per la Lotta alla Siccit├á e Desertificazion
e, adottato dallo Stato Italiano in attuazione della Convenzione delle Nazioni Unite per la Lotta alla Siccit├á ed alla Desertificazione. Nel sopracitato atto ├¿ pre
vista la partecipazione dell'Istituto Nazionale di Economia Agraria nei suoi specifici settori di competenza. L'area di studio comprende Abruzzo, Basilicata, Calabri
a, Campania, Lazio, Marche, Molise Puglia, Sardegna, Sicilia, Toscana, Umbria. Le aree urbane, cos├¼ come le principali infrastrutture, sono superfici caratterizzate
 dalla perdita irreversibile della funzionalit├á produttiva ed ecologica del suolo.
  POLYGON ((8.082 35.2153,19.8853 35.2153,19.8853 44.204,8.082 44.204,8.082 35.2153))

OGRFeature(records):2
  identifier (String) = m_amte:299FN3:ad5f561e-1e56-4b2b-f504-fe4ff7a9e446
  other_identifiers (StringList) = (1:{F8703C77-1DFF-412B-9604-F7FB3AF02DBD})
  title (String) = Infrastrutture ferroviarie - Tratte ferroviarie
  type (String) = downloadableData
  subject (String) = Nazionale
  other_subjects (StringList) = (7:ferrovia,rete ferroviaria,infrastrutture per il traffico,trasporti,RNDT,EU,transportation)
  references (String) = http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0
  other_references (StringList) = (4:http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Rete_ferroviaria.map&service=wfs&request=getCapabilities,http://www.pcn.minamb
iente.it/anteprima/ferrovie.gif,http://www.pcn.minambiente.it/geoportal/csw?getxml=%7BF8703C77-1DFF-412B-9604-F7FB3AF02DBD%7D,http://wms.pcn.minambiente.it/ogc?map=/
ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0)
  modified (String) = 2022-12-06T15:17:49+01:00
  abstract (String) = Il progetto Strati Prioritari di Interesse Nazionale (DBPrior10k), ├¿ stato realizzato nellambito dell'Intesa Stato-Regioni-Enti Locali sui Sis
temi Informativi Geografici (IntesaGIS) a partire dal settembre 2003, ed ├¿ stato consegnato dal Centro Interregionale, che ne ha svolto la direzione lavori, agli En
ti Committenti (Regione Basilicata, Ministero dell'Ambiente) nel giugno 2005. Nel dicembre 2006 la RSDE su incarico del CTC IntesaGIS ha completato l'attivit├á di pu
bblicazione del DBPRIOR10K su www.IntesaGIS ed omogeneizzazione preliminare del grafo della viabilit├á. Le attivit├á svolte nel 2007 dal Centro Interregionale hanno
portato all'integrazione dei dati che ancora mancavano al fine di completare l'intera copertura nazionale. Per la viabilit├á ferroviaria sono state acquisite tutte l
e ferrovie del territorio nazionale, sia appartenenti alle Ferrovie dello Stato che ad altre compagnie. Gli strati informativi relativi alle infrastrutture ferroviar
ie sono costituiti da elementi lineari e puntuali. Gli elementi lineari individuano la tratta ferroviaria.
  POLYGON ((6.0 35.2,19.7 35.2,19.7 47.2,6.0 47.2,6.0 35.2))

OGRFeature(records):3
  identifier (String) = m_amte:299FN3:e44e45a0-f439-4c6e-d3a0-9cbf76e117d4
  other_identifiers (StringList) = (1:{E40B7C2E-DA71-47F3-96E1-57162942BB73})
  title (String) = Infrastrutture ferroviarie - Nodi ferroviari
  type (String) = downloadableData
  subject (String) = Nazionale
  other_subjects (StringList) = (7:ferrovia,rete ferroviaria,infrastrutture per il traffico,trasporti,RNDT,EU,transportation)
  references (String) = http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0
  other_references (StringList) = (4:http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Rete_ferroviaria.map&service=wfs&request=getCapabilities,http://www.pcn.minamb
iente.it/anteprima/ferrovie.gif,http://www.pcn.minambiente.it/geoportal/csw?getxml=%7BE40B7C2E-DA71-47F3-96E1-57162942BB73%7D,http://wms.pcn.minambiente.it/ogc?map=/
ms_ogc/WMS_v1.3/Vettoriali/Rete_ferroviaria.map&service=wms&request=getCapabilities&version=1.3.0)
  modified (String) = 2022-12-06T15:19:17+01:00
  abstract (String) = Il progetto Strati Prioritari di Interesse Nazionale (DBPrior10k), ├¿ stato realizzato nell'ambito dell'Intesa Stato-Regioni-Enti Locali sui Si
stemi Informativi Geografici (IntesaGIS) a partire dal settembre 2003, ed ├¿ stato consegnato dal Centro Interregionale, che ne ha svolto la direzione lavori, agli E
nti Committenti (Regione Basilicata, Ministero dell'Ambiente) nel giugno 2005. Nel dicembre 2006 la RSDE su incarico del CTC IntesaGIS ha completato l'attivit├á di p
ubblicazione del DBPRIOR10K su www.IntesaGIS ed omogeneizzazione preliminare del grafo della viabilit├á. Le attivit├á svolte nel 2007 dal Centro Interregionale hanno
 portato all'integrazione dei dati che ancora mancavano al fine di completare l'intera copertura nazionale. Gli strati informativi relativi alle infrastrutture ferro
viarie sono costituiti da elementi lineari e puntuali. Gli elementi puntuali individuano le intersezioni degli elementi lineari, e sono codificati in modo da descriv
ere il tipo di intersezione che rappresentano.
  POLYGON ((6.0 35.2,19.7 35.2,19.7 47.2,6.0 47.2,6.0 35.2))
```

I don't know if those are the correct results.

**Comment by agiudiceandrea** [comment]
See https://github.com/OSGeo/gdal/issues/6718#issuecomment-1350522215

**Comment by rouault** [comment]
Cool. Merging

**Comment by aborruso** [comment]
Hi @rouault @agiudiceandrea I'm using docker `gdal:alpine-normal-3.6.1` and I have still `ERROR 1: "title" not recognised as an available field.`.

Am I doing something wrong?

**Comment by rouault** [comment]
> Am I doing something wrong?

no, this is only in master / 3.7.0dev

**Comment by aborruso** [comment]
> no, this is only in master / 3.7.0dev

@rouault  Is there a docker image for it?

**Comment by rouault** [comment]
not refreshed recently, but you can build it manually by checking out master and running:
``./docker/alpine-normal/build.sh --platform linux/amd64``

**Comment by aborruso** [comment]
> not refreshed recently, but you can build it manually by checking out master and running:
> `./docker/alpine-normal/build.sh --platform linux/amd64`

I have this error

```
Error response from daemon: network mode "docker_build_gdal" not supported by buildkit
```

**Comment by agiudiceandrea** [comment]
The fix is only gdal dev, not in 3.6.

**Comment by rouault** [comment]
I'm refreshing the master Docker images to include the GPKG spatial index fix, so as a side effect this commit will also be included. At time of writing, the ``osgeo/gdal:latest`` image has been refreshed

**Comment by aborruso** [comment]
It works great: thank you @agiudiceandrea and @rouault

**Comment by aborruso** [comment]
@rouault first of all thank you very much for ogrinfo `-json` output, it's great.

If I run

```
ogrinfo -ro -al  "CSW:http://www.pcn.minambiente.it/geoportal/csw" -where "title LIKE '%aree%'" | grep 'title (String) ='
```

I have 16 layers titles.

If I add `-json`

```
ogrinfo -ro -al -json "CSW:http://www.pcn.minambiente.it/geoportal/csw" -where "title LIKE '%aree%'"
```

I do not have the titles, and the other layer fields: is this normal?

Thank you

**Comment by rouault** [comment]
> I do not have the titles, and the other layer fields: is this normal?

yes: see https://gdal.org/programs/ogrinfo.html#cmdoption-ogrinfo-features

**Pull request merged**
