### PR TITLE
LOS: Implement simple violation location reporting

### PR DESCRIPTION
**Pull request by Ryanf55**
## What does this PR do?

* Implements basic support for reporting a location where LOS  is violated. It reports the location of the first detected violation.
* It's not symmetric due to bresenham's optimizations, but it will at least return one location where terrain is violated (if it is)

## What are related issues/pull requests?

#9562 

## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [x] Add test case(s)
 - [ ] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: Ubuntu 22
* Compiler: G++11

## Instructions
```bash
cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build build --target gdal_unit_test -j `nproc`
./build/autotest/cpp/gdal_unit_test --gtest_filter="test_alg.GDALIsLineOfSightVisible*"
# Or, with GDB
 gdb ./build/autotest/cpp/gdal_unit_test
>>> r --gtest_filter="test_alg.GDALIsLineOfSightVisible*"
```

### CODE REVIEW

**Comment by rouault** [comment]
Can you update autotest/alg/los.py or autotest/cpp/test_alg.cpp?

**Comment by Ryanf55** [comment]
> Can you update autotest/alg/los.py or autotest/cpp/test_alg.cpp?

Yup. Are you on with heuristic based testing that doesn't check for exact locations reported because it's currently an implementation detail that doesn't matter?
More importantly, the values get set to something between points A and B.

**Comment by rouault** [comment]
> Are you on with heuristic based testing that doesn't check for exact locations

I would just test the current returned values. If one day the algorithm is changed, we can always update the expected results

**Comment by rouault** [comment]
code formatting issue: cf https://github.com/OSGeo/gdal/actions/runs/8880363204/job/24380232858?pr=9785

**Comment by Ryanf55** [comment]
> code formatting issue: cf https://github.com/OSGeo/gdal/actions/runs/8880363204/job/24380232858?pr=9785

Linter is fixed, only failure left is unrelated on windows: https://github.com/OSGeo/gdal/actions/runs/8887950310/job/24404034582?pr=9785#step:13:2102

**Comment by rouault** [comment]
@Ryanf55 Can you adjust the documentation of the function that currently says that the intersection reporting is not currently implemented?

**Comment by Ryanf55** [comment]
Done. Note - the implementation sets the values to -1 if there is no intersection. Do you think I should re-order that to set it to `nullptr`?

**Comment by rouault** [comment]
> Do you think I should re-order that to set it to `nullptr`?

I don't understand what you mean. You can't set to nullptr the value of a ``int*``

**Pull request merged**
