### PR TITLE
[jpg] Correctly read GCPS when an .aux.xml sidecar has GeodataXform present in the ESRI metadata element instead of root element

### PR DESCRIPTION
**Pull request by nyalldawson**
Previously we ignored these because we first encountered a SRS element as a direct child of the root node.

### CODE REVIEW

**Comment by rouault** [comment]
Can you use smallish .jpg files (even if they are dummy and unrelated to the .aux.xml) ? 2x 533kB is too large.

**Comment by nyalldawson** [comment]
@rouault 

> Can you use smallish .jpg files (even if they are dummy and unrelated to the .aux.xml) ? 2x 533kB is too large.

Sure, done

**Comment by rouault** [comment]
The backport to `release/3.6` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 60a0c0ce98... [jpg] Correctly read GCPS when an .aux.xml sidecar has GeodataXform
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/gdrivers/jpeg.py
CONFLICT (content): Merge conflict in autotest/gdrivers/jpeg.py

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.6 release/3.6
# Navigate to the new working tree
cd .worktrees/backport-release/3.6
# Create a new branch
git switch --create backport-7072-to-release/3.6
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 60a0c0ce98f3fe452ee11c3fe4b79993cbc9e60e
# Push it to GitHub
git push --set-upstream origin backport-7072-to-release/3.6
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.6
```
Then, create a pull request where the `base` branch is `release/3.6` and the `compare`/`head` branch is `backport-7072-to-release/3.6`.

**Comment by rouault** [comment]
manually backported in 3.6 per f6065f26daffb2fbbf93e16073914377e9c15013

**Comment by nyalldawson** [comment]
Thanks @rouault !

**Pull request merged**
