### PR TITLE
Enable Bash completions and control installation

### PR DESCRIPTION
**Pull request by cjmayo**
## What does this PR do?

bash-completion expects completions to be installed in a given directory
and named for program being completed.

Detect the directories as suggested in the FAQ:
https://github.com/scop/bash-completion/blob/master/README.md#faq

Control installation with a new configuration option --with-bash-completion.
If it is not specified nothing will be installed.
If a path is passed completions will be installed in that directory.

Install the GDAL completion script as gdalinfo and create symlinks to it
for the other programs.

---

This works for me and I've tried to address the situation raised in the previous ticket (below) by not installing by default, and it also allows a custom path to be used. I'm a bit cautious because I can't see how anyone is using the current code. On the other hand when ${prefix} is being prepended to the path returned by pkg-config it does seem pretty broken.

## What are related issues/pull requests?
https://trac.osgeo.org/gdal/ticket/6381

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: Gentoo Linux
* Compiler: gcc

### CODE REVIEW

**Comment by rouault** [comment]
Could you run "autoconf" and commit the modified configure file ?

**Comment by cjmayo** [comment]
Done, although my version appears to be newer. I've added an additional commit to separate the changes from the version change alone.

**Comment by cjmayo** [comment]
Perhaps I shouldn't have added the autoreconf changes into the same commit as the real changes. I'm happy to separate those out again into a separate commit.

**Comment by rouault** [comment]
can you revert at least the changes in port/cpl_config.h.in  ?

**Comment by cjmayo** [comment]
> can you revert at least the changes in port/cpl_config.h.in ?

That's done (and a separate autoreconf commit).

**Pull request merged**
