### PR TITLE
Python bindings: fix/workaround installation into /usr/local/lib/python{version}/dist-packages when prefix is /usr/local

### LINKED ISSUE #10242: make install puts python packages in the wrong directory
### What is the bug?

after `make install` this fails:
> python -c 'import osgeo'

with this error:
> Traceback (most recent call last):
>  File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'osgeo'

### Steps to reproduce the issue

in a `Debian GNU/Linux 12 (bookworm)` system build and install gdal , then run `python -c 'import osgeo'`

### Versions and provenance

Problem was found in release/3.6 branch

### Additional context

The default python system path does not include `/usr/local/lib/python3/dist-packages` but GDAL installs in there.

### PR DESCRIPTION
**Pull request by rouault**
Fixes #10242

### CODE REVIEW

**Comment by strk** [comment]
Do I need to wipe some CMake cache for it to be effective ?
The commit cherry-picked into release/3.9 did not fix the issue but still installed in `python3`

**Comment by rouault** [comment]
> Do I need to wipe some CMake cache for it to be effective ?

I'm not sure...

> The commit cherry-picked into release/3.9 did not fix the issue but still installed in python3

Weird. I tested locally on Ubuntu 20.04. Can you further diagnose?

**Comment by strk** [comment]
Should the python installation path be printed by cmake ?

**Comment by strk** [comment]
Sorry upon re-reading your changes I see you provided a workaround cmake define `GDAL_PYTHON_INSTALL_PREFIX` and you mentioned something about --prefix and --install-layout=deb -- I just assumed a vanilla `cmake .` to just work (and I was wrong, obvously)

You also assumed I was using those switches somehow, which I wasn't.

For documentation:

Are the --prefix and --install-layout=deb just left-over from autoconf times ?
How do I use `GDAL_PYTHON_INSTALL_PREFIX`

**Comment by rouault** [comment]
I've just testing successfully the following:

inside ``docker run --rm -it -v $PWD:$PWD debian:12``

```
apt update
apt install cmake g++ make python3-dev python3-numpy python3-setuptools libproj-dev swig
cd /home/even/gdal/gdal/
mkdir build_debian12
cd build_debian12/
cmake ..
make -j$(nproc)
make install
ldconfig
python3 -c "from osgeo import gdal; print(gdal.VersionInfo(None))"
```

``make install`` does install in /usr/local/lib/python3.11/dist-packages:
```
[...]
running install_lib
creating /usr/local/lib/python3.11/dist-packages/osgeo_utils
[...]
creating /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/_gdal_array.cpython-311-x86_64-linux-gnu.so -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/_osr.cpython-311-x86_64-linux-gnu.so -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/_ogr.cpython-311-x86_64-linux-gnu.so -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/osr.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/gdalnumeric.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/__init__.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/gdal_array.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/_gnm.cpython-311-x86_64-linux-gnu.so -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/gdalconst.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/gnm.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/_gdalconst.cpython-311-x86_64-linux-gnu.so -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/ogr.py -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/_gdal.cpython-311-x86_64-linux-gnu.so -> /usr/local/lib/python3.11/dist-packages/osgeo
copying build/lib.linux-x86_64-3.11/osgeo/gdal.py -> /usr/local/lib/python3.11/dist-packages/osgeo
[...]
```

**Comment by strk** [comment]
Sorry, you are right the install is now in /usr/local/lib/python3.11/dists-packages, it works (I was building with python disabled, fooled by the switch from autoconf to cmake).

The import from python also then works, out of the box (after ldconfig): woo !!

**Review by strk — APPROVED** [review]
Great work Even, and very fast !

**Comment by strk** [comment]
I verified this backports cleanly to release/3.9 -- it would be nice if it could go to even older releases ( I was needing this in 3.6 )

**Comment by rouault** [comment]
> it would be nice if it could go to even older releases

we just maintain the latest one, ie release/3.9 at present. Too much effort for little reward in maintaining more

**Comment by rouault** [comment]
Not backporting this to 3.9 as this changes the installation path of python bindings, which might break users

**Pull request merged**
