### PR TITLE
[WIP] Add support for PathLike objects (pathlib.Path) in gdal/ogr core functions

### PR DESCRIPTION
**Pull request by idanmiara**
## What does this PR do?

Implement https://github.com/OSGeo/gdal/issues/1613

### CODE REVIEW

**Comment by idanmiara** [comment]
I know I need to add `path_args` to the swig bindings files, but I couldn't find how.

**Comment by rouault** [comment]
> I know I need to add `path_args` to the swig bindings files, but I couldn't find how.

What do you mean exactly ?

**Comment by idanmiara** [comment]
> > I know I need to add `path_args` to the swig bindings files, but I couldn't find how.
> 
> What do you mean exactly ?

I've edited the auto generated `gdal.py` and `ogr.py` to add the required functionality.
I couldn't find how to make this change in the source `.i` files

**Comment by rouault** [comment]
> I've edited the auto generated `gdal.py` and `ogr.py` to add the required functionality.

you definitely shouldn't do that. This will be lost at the next update.

You should rather modify the "%typemap(in) (const char *utf8_path) (int bToFree = 0)" in swig/include/python/typemaps_python.i to accept a PathLike in addition to a string . And then "make generate && make" in swig/python (please use SWIG 3.0.12 to regenerate the files. SWIG builds easily from sources)

**Comment by idanmiara** [comment]
> %typemap(in) (const char *utf8_path) (int bToFree = 0)

I thought about that, but that's a c function, and I need to apply a Python function

**Comment by rouault** [comment]
> I thought about that, but that's a c function, and I need to apply a Python function

you'll have to use the C Python API to call your Python function. Some inspiration might be taken from InitializePythonAndLoadGDALPythonDriverModule() in gcore/gdalpythondriverloader.cpp. Mostly for the use of  PyImport_ImportModule() and PyObject_Call(). You don't need to create a module on-the-fly like done in InitializePythonAndLoadGDALPythonDriverModule().

**Comment by idanmiara** [comment]
> > I thought about that, but that's a c function, and I need to apply a Python function
> 
> you'll have to use the C Python API to call your Python function. Some inspiration might be taken from InitializePythonAndLoadGDALPythonDriverModule() in gcore/gdalpythondriverloader.cpp. Mostly for the use of PyImport_ImportModule() and PyObject_Call(). You don't need to create a module on-the-fly like done in InitializePythonAndLoadGDALPythonDriverModule().

Thanks for your pointers.
I hope I'll have time to look into it soon. 
I've made https://github.com/OSGeo/gdal/pull/3722 to address the related issues that I could already solve.

**Comment by idanmiara** [comment]
I'll reopen this PR when it's ready.

**Pull request closed without merging**
