### PR TITLE
Target netcoreapp3.1

### PR DESCRIPTION
**Pull request by bjornharrtell**
ref https://github.com/OSGeo/gdal/issues/3711

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Doesn't appear to help. The error is refering to "Microsoft Visual Studio Offline Packages" as the source of dependencies and I'm not sure what that is but it appears to not have what was and is needed.

**Comment by rouault** [comment]
maybe using https://github.com/actions/setup-dotnet would help ?  Defaulting to 3.1 breaks the appveyor.yml build

**Comment by rouault** [comment]
not sure if it is a change in the VM (https://github.com/actions/virtual-environments/commits/main/images/win/Windows2019-Readme.md doesn't mention a today or yesterday change). Might be on the nuget side ?

**Comment by bjornharrtell** [comment]
it could possibly help to explicitly add expected toolchain at least that's indicated in this similar issue - https://developercommunity.visualstudio.com/t/nuget-restore-failing-on-azure-agents-packages-not/985186

**Comment by rouault** [comment]
I'm not sure if this PR is still of interest after https://github.com/OSGeo/gdal/pull/3769?

**Comment by bjornharrtell** [comment]
It's probably a good idea to move away from .NET Core 2.1 at some point. Not sure if the appveyor setup has much life left?

**Comment by rouault** [comment]
> Not sure if the appveyor setup has much life left?

probably not that much, but it shouldn't be too difficult to specify the old dotnetcore by putting its value in the nmake.local generated in appveyor.yml

**Pull request closed without merging**
