### PR TITLE
do not use global code in pytest

### LINKED ISSUE #3223: gdal_calc unit tests are silently skipped and some fail
gdal_calc unit tests seem to be silently skipped and when fixed some of them fail

## Expected behavior and actual behavior.

Actual
```
mmom@mmom-workstation:~/src/gdal/autotest$ pytest  pyscripts/test_gdal_calc.py 
Test session starts (platform: linux, Python 3.7.5, pytest 5.3.5, pytest-sugar 0.9.2)
rootdir: /home/mmom/src/gdal-mmomtchev/autotest, inifile: pytest.ini
plugins: env-0.6.2, sugar-0.9.2
collecting ... 

Results (0.97s):
```

Expected

```
mmom@mmom-workstation:~/src/gdal-mmomtchev/autotest$ pytest  pyscripts/test_gdal_calc.py 
Test session starts (platform: linux, Python 3.7.5, pytest 5.3.5, pytest-sugar 0.9.2)
rootdir: /home/mmom/src/gdal-mmomtchev/autotest, inifile: pytest.ini
plugins: env-0.6.2, sugar-0.9.2
collecting ... 
 pyscripts/test_gdal_calc.py ✓✓✓                                                                                                                                                              30% ███       
```

## Steps to reproduce the problem.

Do the steps from `CONTRIBUTING.md`

## Operating system

Ubuntu 19.10

## GDAL version and provenance

git master

### PR DESCRIPTION
**Pull request by mmomtchev**
## What does this PR do?

Remove global code from ` test_gdal_calc.py`
Fix #3223 

## What are related issues/pull requests?

#3223

### CODE REVIEW

**Comment by mmomtchev** [comment]
This just reenables the unit tests, some of them fail

**Comment by mmomtchev** [comment]
@rouault do not merge, I will look into the failing tests

**Comment by rouault** [comment]
@idanmiara might possibly help w.r.t test_gdal_calc_py_9() failure

**Comment by mmomtchev** [comment]
in `test_gdal_calc_py_4()`, the geotransforms are missing from the output file, the result is otherwise correct

**Comment by mmomtchev** [comment]
In fact, for test #4, I think that the new behavior is the correct one, the input file does not have a valid geotransform

**Comment by mmomtchev** [comment]
No, for #4 the geotransforms do look better than before, but I am getting 3 identical bands when I should not

**Comment by mmomtchev** [comment]
I get different results when I use the deprecated script from the old location - which I think the unit test uses too

**Comment by mmomtchev** [comment]
@roualt It is not as bad as it seems, I think the only problem is that the deprecated script does not import the right `gdal_calc` after building in a dev tree

**Comment by mmomtchev** [comment]
@rouault does the tests work for you? Because now that I am calling the right `gdal_calc` script (I just updated the PR), only test 9 is still failing
And even that one works if I manually call the script
So I guess it is a Python import path issue?

**Comment by rouault** [comment]
The tests now pass with your changes in autotest/pyscripts/test_gdal2tiles.py . I don't need the changes in autotest/pymod/test_py_scripts.py : they don't hurt, but I don't think they're really needed and should be reverted. They must hide something wrong with your dev environment. Do you source the "gdal/scripts/setdevenv.sh" script that will set PYTHONPATH ?

**Comment by mmomtchev** [comment]
Yes, I did source it and `gdalinfo --version` does show the dev tree. But my system GDAL is 3.1.0, so if something is included from it, it explains that test 9 fails

**Comment by mmomtchev** [comment]
@rouault I found the problem - the dataset is not closed after writing and if computing the checksum by reopening the file, the reported checksum is zero
Once the dataset is closed, the checksum is correct
But I wonder, should `gdal_calc.Calc` return a closed dataset? Who shall close the dataset in this case?

**Comment by rouault** [comment]
> But I wonder, should `gdal_calc.Calc` return a closed dataset? Who shall close the dataset in this case?

That's one of the recent change done by @idanmiara . gdal_calc.Calc() returns a dataset that hasn't been closed, so if you want to gdal.Open() it you need to close it before. This is similar to gdal.Translate() or gdal.Warp()

**Comment by idanmiara** [comment]
> > But I wonder, should `gdal_calc.Calc` return a closed dataset? Who shall close the dataset in this case?
> 
> That's one of the recent change done by @idanmiara . gdal_calc.Calc() returns a dataset that hasn't been closed, so if you want to gdal.Open() it you need to close it before. This is similar to gdal.Translate() or gdal.Warp()

If the result of gdal_calc.Calc() is not assigned to a variable then the dataset would be closed by itself, right?
So I guess that shouldn't be a problem.

**Comment by idanmiara** [comment]
> @idanmiara might possibly help w.r.t test_gdal_calc_py_9() failure

sorry, what's w.r.t?

**Comment by idanmiara** [comment]
@mmomtchev would you please explain in which cases some tests are skipped when they shouldn't be skipped ?
Why would the value of gdalnumeric_not_available or script_path would need to be evaluated in each test?
In which case would script_path not be found ?
Wouldn't it be easier/cleaner to run the tests against the gdal_calc module and not as a script anyway?

**Comment by mmomtchev** [comment]
@idanmiara I didn't investigate further - I guess there is something special about the way `pytest` loads modules - but I don't have an idea what

**Comment by rouault** [comment]
I'm merging this as it fixes a regression in testing. @idanmiara feel free to submit follow-up PR

**Comment by idanmiara** [comment]
> I'm merging this as it fixes a regression in testing. @idanmiara feel free to submit follow-up PR

thanks.

**Pull request merged**
