### PR TITLE
LVBAG specification enhancements

### LINKED ISSUE #3221: OGR LVBAG Driver: addressable objects conversions should follow XSD
"Addressable objects" within the BAG are Object Types that have (one or more) addresses.
Three types Verblijfsobject  (VBO, hard to translate: "Living-unit", "Apartment"), Ligplaats (LIG, on water, mainly for living boats), Standplaats (STA, on land, like camp-ground). Will use these abbrevs below, and PND for Pand (Building).

These objects are defined within an [XSD](https://github.com/lvbag/BAG-2.0-Extract/tree/master/Vernieuwde%20XSD's), see `imbag/IMBAGLV/objecten/v20200601/IMBAGLV_Objecten-2.1.0.xsd` (attached here). Several design decisions there are not very obvious, but should still be addressed in the LVBAG Driver. Will expand below for each issue. Most have to do with "multiplicity". 

It may help to look at the [Python object definitions in NLExtract BAG v1](https://github.com/nlextract/NLExtract/blob/master/bag/src/bagobject.py) and the [BAG Postgres tables](https://github.com/nlextract/NLExtract/blob/master/bag/db/script/bag-db.sql).

### N-M Relation PND-VBO
A VBO is usually N:1 to a PND Building, i.e. a PND contains (`maaktDeelUitVan`/"Is-part-of") one or more VBOs. But there are also cases where a VBO belongs to more than 1 PND. Hence the relation PND-VBO in the XSD is N-M. This should be reflected in the LVBAG output. 
Currently only one PND related to a VBO is assumed.

The relevant XSD excerpt:

```
					<xs:element name="maaktDeelUitVan" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>Een verblijfsobject maakt onderdeel uit van een pand.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:choice minOccurs="1" maxOccurs="unbounded">
								<xs:element ref="Objecten-ref:PandRef"/>
							</xs:choice>
						</xs:complexType>
					</xs:element>
```

Within NLExtract this was solved by generating a relation-table ("tussentabel") `verblijfsobjectpand ` that enumerates all PND-VBO relations.
LVBAG could do something similar like generating a PND-VBO object. This object should also contain the VBO `voorkomen` attributes. Generating an identifier array `StringList` (preferred) or comma-separated for `maaktDeelUitVan` would also be possible and more compact.

### One or more "usage-purposes" ("gebruiksdoelen") VBO 
The relevant XSD excerpt:

```
					<xs:element name="gebruiksdoel" type="Objecten:Gebruiksdoel" minOccurs="1" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>Een categorisering van de gebruiksdoelen van het betreffende verblijfsobject, zoals dit formeel door de overheid als zodanig is toegestaan.</xs:documentation>
						</xs:annotation>
					</xs:element>
```

Within NLExtract this was solved by generating a relation-table ("tussentabel") `verblijfsobjectgebruiksdoel ` .
But LVBAG could also solve this more compact by generating a comma-separated list as a string.
Or more formally a string array type `StringList` (preferred). `ogr2ogr` can expand to comma-separated if needed with `-fieldTypeToString StringList`.
#### VBO handle sub-addresses
XSD excerpt:

```	<xs:element name="_AdresseerbaarObject" type="Objecten:_AdresseerbaarObject" abstract="true">
		<xs:annotation>
			<xs:documentation>Een Adresseerbaar object is een (abstract) object waaraan adressen kunnen worden toegekend</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="_AdresseerbaarObject" abstract="true">
		<xs:sequence>
			<xs:element name="heeftAlsHoofdadres" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Een adresseerbaar object heeft als hoofadres een nummeraanduiding.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:choice minOccurs="1" maxOccurs="1">
						<xs:element ref="Objecten-ref:NummeraanduidingRef"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="voorkomen" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="Historie:Voorkomen" minOccurs="1" maxOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="heeftAlsNevenadres" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Een adresseerbaar object heeft als nevenadres een nummeraanduiding.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:choice minOccurs="1" maxOccurs="unbounded">
						<xs:element ref="Objecten-ref:NummeraanduidingRef"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Verblijfsobject" type="Objecten:Verblijfsobject" abstract="false">
		<xs:annotation>
			<xs:documentation>Een Verblijfsobject is de kleinste binnen één of meerdere panden gelegen en voor woon -, bedrijfsmatige - of recreatieve doeleinden geschikte eenheid van gebruik, die ontsloten wordt via een eigen toegang vanaf de openbare weg, een erf of een gedeelde verkeersruimte en die onderwerp kan zijn van rechtshandelingen.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="Verblijfsobject" abstract="false">
		<xs:complexContent>
			<xs:extension base="Objecten:_AdresseerbaarObject">
				<xs:sequence>
					<xs:element name="identificatie" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>De unieke aanduiding van een verblijfsobject.</xs:documentation>
						</xs:annotation>
```

A VBO, STA, LIG ("addresseerbaarobject") always has only one main address (`heeftAlsHoofdadres`) and zero or more sub-adresses (`heeftAlsNevenadres`). 

In NLExtract BAG v1 a `nevenadres` object was generated for each occurrence with this definition:

```
CREATE TABLE adresseerbaarobjectnevenadres (
  identificatie VARCHAR(16),
  aanduidingRecordInactief BOOLEAN,
  aanduidingRecordCorrectie INTEGER,
  begindatumTijdvakGeldigheid TIMESTAMP WITH TIME ZONE,
  einddatumTijdvakGeldigheid TIMESTAMP WITH TIME ZONE,
  ligplaatsStatus ligplaatsStatus,
  standplaatsStatus standplaatsStatus,
  verblijfsobjectStatus verblijfsobjectStatus,
  geom_valid BOOLEAN,
  nevenadres VARCHAR(16),
  PRIMARY KEY (gid)
);
```

`identificatie` refers to the main VBO address, `nevenadres`. But this solution is maybe too complex.
Not sure why that was done.

Like with the other multiplicities a string array type `StringList` of  `nevenadres` identifiers (referring to Nummeraanduiding objects) could be generated.

### VBO Geometry may be POINT or POLYGON
Relevant XSD excerpt:

```
					<xs:element name="geometrie" type="Objecten:PuntOfVlak" minOccurs="1" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>De minimaal tweedimensionale geometrische representatie van een verblijfsobject.</xs:documentation>
						</xs:annotation>
					</xs:element>
```
with
```
	<xs:element name="PuntOfVlak" type="Objecten:PuntOfVlak" abstract="false"/>
	<xs:complexType name="PuntOfVlak" abstract="false">
		<xs:annotation>
			<xs:documentation>Ofwel een punt, ofwel een vlak. </xs:documentation>
		</xs:annotation>
		<xs:choice minOccurs="1" maxOccurs="1">
			<xs:element name="punt" type="gml:PointPropertyType">
				<xs:annotation>
					<xs:documentation>Gebruik Point.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="vlak" type="gml:SurfacePropertyType">
				<xs:annotation>
					<xs:documentation>Gebruik surface, conform NEN3610 Simple Feature Profile Niveau 2 (niet Polygon)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
```

In NLExtract BAG v1 this was solved by generating two fields `POINT geopunt` and `POLYGON geovlak`. This is my preferred solution. Defining a single multi-typed geom field as `GEOMETRY` also has issues.

## Operating system

Any

## GDAL version and provenance

GDAL 3.2.0, released 2020/10/26
[IMBAGLV_Objecten-2.1.0.xsd.txt](https://github.com/OSGeo/gdal/files/5596257/IMBAGLV_Objecten-2.1.0.xsd.txt)

### PR DESCRIPTION
**Pull request by yorickdewid**
## What does this PR do?

* Change the field type from string to stringlist for `gebruikersdoel`
* Add a secondary address to datasource LIG, STA, VBO.

## What are related issues/pull requests?
Fixes #3221 . 

## Tasklist

 - [x] Add test case(s)
 - [x] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by justb4** [comment]
* multiple `gebruiksdoelen` as `stringlist` looks ok
* `nevenadres` (sub-adress): the implementation assumes (AFAICS):
   1- an object (`num, lig, sta`) has either a `hoofdadres` or `nevenadres` (?) 
   2- in case of `nevenadres` a single occurrence is assumed but the XSD, and in practice can be 0 or more. see below

ad 1) a `num, lig, sta` always has one `hoofdadres` (and 0 or more `nevenadres`), not either/or...

ad 2) if `num, lig, sta` (AdresseerbaarObject) has a `heeftAlsNevenadres` element, then there can be one or more `NummeraanduidingRef`s, one for each sub-address. This is what happens in practice a lot. Best example is "Torentje Den Haag": see in BAGViewer: [Binnenhof 17, 2513 AA Den Haag](https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=Binnenhof%2017,%202513%20AA%20Den%20Haag&resultOffset=0&objectId=0518200000692257&geometry.x=81431.756&geometry.y=455218.921&zoomlevel=6&detailsObjectId=0518200000692259). This place has sub-addresses `Binnenhof 18, 19, 20`. They share the same VBO (id=0518010000692261 ) and thus Point. Could be a good test-case as well. See also [a very old issue](https://github.com/nlextract/NLExtract/issues/102).

XSD v20200601 excerpt with my comments as `<==`:

```
<xs:complexType name="_AdresseerbaarObject" abstract="true">
	<xs:sequence>
		<xs:element name="heeftAlsHoofdadres" minOccurs="1" maxOccurs="1">
			<xs:annotation>
				<xs:documentation>Een adresseerbaar object heeft als hoofadres een nummeraanduiding.</xs:documentation>
			</xs:annotation>
			<xs:complexType>
				<xs:choice minOccurs="1" maxOccurs="1">  <==always one main adress
					<xs:element ref="Objecten-ref:NummeraanduidingRef"/>
				</xs:choice>
			</xs:complexType>
		</xs:element>
		<xs:element name="voorkomen" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="Historie:Voorkomen" minOccurs="1" maxOccurs="1"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="heeftAlsNevenadres" minOccurs="0" maxOccurs="1"> 
			<xs:annotation>
				<xs:documentation>Een adresseerbaar object heeft als nevenadres een nummeraanduiding.</xs:documentation>
			</xs:annotation>
			<xs:complexType>
				<xs:choice minOccurs="1" maxOccurs="unbounded">   <== 1 or more if present
					<xs:element ref="Objecten-ref:NummeraanduidingRef"/>
				</xs:choice>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>
```

**Comment by yorickdewid** [comment]
> ad 1) a `num, lig, sta` always has one `hoofdadres` (and 0 or more `nevenadres`), not either/or...

There is no either or. If we find hoofdadres then there is a hoofdadres, which translates to any LIG, STA, VBO feature having a hoofdadres.

> ad 2) if `num, lig, sta` (AdresseerbaarObject) has a `heeftAlsNevenadres` element, then there can be one or more `NummeraanduidingRef`s, one for each sub-address. This is what happens in practice a lot. Best example is "Torentje Den Haag": see in BAGViewer: [Binnenhof 17, 2513 AA Den Haag](https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=Binnenhof%2017,%202513%20AA%20Den%20Haag&resultOffset=0&objectId=0518200000692257&geometry.x=81431.756&geometry.y=455218.921&zoomlevel=6&detailsObjectId=0518200000692259). This place has sub-addresses `Binnenhof 18, 19, 20`. They share the same VBO (id=0518010000692261 ) and thus Point. Could be a good test-case as well. See also [a very old issue](https://github.com/nlextract/NLExtract/issues/102).

Thanks, fix should be quite easy.

**Comment by justb4** [comment]
@yorickdewid thanks, looks good for `NevenAdres`!

**Comment by yorickdewid** [comment]
Ready for merge

**Comment by justb4** [comment]
@yorickdewid @rouault thanks for this! 

Tested multivalued attr-cases for [NLExtract](https://github.com/nlextract/NLExtract) with latest (as of feb 15, 2021) GDAL Docker Image (`alpine-small-latest `) OK.

Mapping to OGR `StringList` ok, including using OGR option `-fieldTypeToString StringList` for:

* VBO `gebruiksdoel` and `pandRef` 
* VBO, STA and LIG: `nevenadresNummeraanduidingRef` 

Tested with output both GeoJSON and PostGIS ok.

**Pull request merged**
