### PR TITLE
gdalwarp: improve logic for selecting input overview when target bounds and resolution are specified

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by sgillies** [comment]
@rouault would it make sense to have this feature in the warp API instead of only in the gdalwarp program?

**Comment by rouault** [comment]
> would it make sense to have this feature in the warp API instead of only in the gdalwarp program?

you can actually use it with the GDALWarp() C API (gdal_utils.h) since the gdalwarp binary mostly calls it those days.

**Comment by rouault** [comment]
@tbonfort Can you confirm it fixes your issue ?

**Comment by tbonfort** [comment]
@rouault I still see the same behavior unfortunately. here are some CPL_DEBUG logs if that helps:
```
CPL_DEBUG=ON LD_LIBRARY_PATH=/opt/lib go run . gs://jp2cogtest/am/am.vrt
2020/09/04 17:43:47 read jp2cogtest/am/am.vrt [0-1048576]
GDAL: GDALOpen(gs://jp2cogtest/am/am.vrt, this=0x7f0c2c16cda0) succeeds as VRT.
GDAL: Computing area of interest: 2.31819, 42.3408, 7.69174, 44.3679
OGRCT: Wrap source at 5.00497.
OGRCT: Wrap target at 5.00497.
GDAL: GDALDriver::Create(MEM,MEM:::,256,256,4,Byte,(nil))
WARP: Copying metadata from first source to destination dataset
GDAL: GDALDefaultOverviews::OverviewScan()
GDALWARP: Defining SKIP_NOSOURCE=YES
WARP: SetAlphaMax: AlphaMax not set.
WARP: SetAlphaMax: AlphaMax not set.
2020/09/04 17:43:47 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [0-1048576]
GDAL: GDALOpen(gs://jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif, this=0x7f0c2c4f8bf0) succeeds as GTiff.
2020/09/04 17:43:47 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [117440512-119537664]
2020/09/04 17:43:47 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [115343360-116391936]
2020/09/04 17:43:47 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [118489088-119537664]
2020/09/04 17:43:47 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [112197632-114294784]
2020/09/04 17:43:47 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [109051904-111149056]
GDAL: GDAL_CACHEMAX = 796 MB
2020/09/04 17:43:48 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-002.tif [0-1048576]
GDAL: GDALOpen(gs://jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-002.tif, this=0x7f0c2c16c1b0) succeeds as GTiff.
2020/09/04 17:43:48 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-002.tif [25165824-26214400]
2020/09/04 17:43:48 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-002.tif [22020096-24117248]
GDAL: GDALWarpKernel()::GWKBilinearNoMasksOrDstDensityOnlyByte() Src=111428,38332,3364x2428 Dst=0,0,32x32
2020/09/04 17:43:48 read jp2cogtest/am/France-SouthEast-ReRanked--V2-mosa-8bit-mosa-005-001.tif [116391936-117440512]
GDAL: GDALWarpKernel()::GWKBilinearNoMasksOrDstDensityOnlyByte() Src=114593,38332,3363x2428 Dst=32,0,32x32
...
```

**Comment by rouault** [comment]
@tbonfort I don't see a trace like "WARP: Selecting overview level X for Y" in your log, so it doesn't look like it selects an overview, but uses the main resolution raster.

I tried with a dataset similar to your original one (but 10 times smaller in each dimension) generated with:
```
gdal_translate byte.tif test.tif -scale 0 255 0 0 -co SPARSE_OK=YES -outsize 27032 14552 -co TILED=YES -a_ullr -4730365.833  2876021.393  4730904.167 -2217493.607 -a_srs "+proj=ortho +lon_0=99.8 +lat_0=61.52"
gdaladdo test.tif
```
and then tried the following gdalwarp
```
gdalwarp -t_srs epsg:3857 -ts 128 128 -te 10018754.171394620091 15967389.460660178214 10331840.239250702783 16280475.528516260907 -r cubic ../../gdal/gdal/test.tif out.tif -overwrite --debug on
```
With this PR, it selects the base resolution (with Src=13008,2072,167x158 Dst=0,0,128x128) and without it the 2nd overview level (with Src=3250,516,45x43 Dst=0,0,128x128)

What does your go program do exactly ?

**Comment by tbonfort** [comment]
OK, I might be mixing up which issue we were talking about, sorry for the noise.

**Comment by tbonfort** [comment]
@rouault LGTM , works perfectly!

**Pull request merged**
