### PR TITLE
SWQ: fix crash when comparing integer array fields (fixes: #6714)

### PR DESCRIPTION
**Pull request by elpaso**
When comparing integer array fields with integers the code represents the arrays with their string serialized form, comparing with the string representation of the integer value which is null led to the crash.

### CODE REVIEW

**Review by rouault — APPROVED** [review]
I feel like there would probably a better fix in a step that occurs before (SWQGeneralChecker perhaps ? not sure... as this might be trickier as IntegerList if a OGRFieldType value but not a swq_field_type one, so the mismatch is bound to cause such issues), but your fix is reasonable.

**Comment by rouault** [comment]
python tests linting issue: https://github.com/OSGeo/gdal/actions/runs/3481075088/jobs/5821696426

Install pre-commit: ``pip install precommit``
Apply it to repository (to be done once): ``pre-commit install``
Manually fix files (not needed afterwards, since it will be done automatically at git commit time): ``pre-commit run --all-files``

**Comment by pathmapper** [comment]
@rouault just noticed that this is tagged for 3.6.1 but looks like it isn't included in 3.6.1 and 3.6.2.

**Comment by rouault** [comment]
> @rouault just noticed that this is tagged for 3.6.1 but looks like it isn't included in 3.6.1 and 3.6.2.

ah good point, I guess I wanted to use the "backport release/3.6" label but accidentally used the milestone one.
I've just manually backported this in release/3.6 branch per 69d3d8a95cfb654b2cdc86e1f6252479d7a12bcb. So this will in 3.6.3

**Pull request merged**
