### PR TITLE
add scripts to python module

### PR DESCRIPTION
**Pull request by thehesiod**
## What does this PR do?
Adds the python scripts to the python module.  They are installed if you build via gnumake, but they're not included in the python module.

## Tasklist

 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment
Python

### CODE REVIEW

**Comment by thehesiod** [comment]
also fixed some PEP issues and did some code de-duping

**Comment by rouault** [comment]
This fails to build on many CI targets
```
  File "setup.py", line 438
    setup(**setup_kwargs,
```

@thehesiod  Is the intent that the scripts would be installed in /usr/lib/python2.7/dist-packages/osgeo/ ? Perhaps for this to be more pip friendly ?

@sebastic What do you think of this ? My Python packaging abilities are low. I was wondering about the impact on downstream packages.
I looked at https://packages.debian.org/sid/amd64/python-gdal/filelist and see that the Python scripts are finally in /usr/bin/  . Strangely https://packages.debian.org/sid/amd64/python3-gdal/filelist doesn't include the script. That means that someone who would want a Python3-only install wouldn't have the scripts.
As those scripts have been always considered as command line utilities we still want them to be accessible through the PATH. Perhaps have symlinks from /usr/lib/python2.7/dist-packages/osgeo/gdal_calc.py to /usr/bin/gdal_calc.py , so that people can still use it as utility (from /usr/bin) and also be able do a "from osgeo import gdal_calc" (from /usr/lib/python2.7/dist-packages/osgeo)  ?

**Comment by sebastic** [comment]
The scripts are only included in the python-gdal package because only one package can provides those files, otherwise the python3-gdal package wouldn't be co-installable along the python-gdal package.

To provide the scripts for both Python version, the scripts could be installed in `/usr/lib/<package>` using `--install-scripts`. The alternatives system can then be used to select which package should provide files (symlinks) in `/usr/bin`. We do this for some package that install scripts and for which the package build both Python 2 and Python 3 library packages.

The gdal package build is a bit of a hack to build the Python bindings for all supported interpreters, hacking in support for the above is not something I'm looking forward to doing.

People that want the Python scripts should just install the python-gdal package alongside the python3-gdal package they use for their Python3-only code.

**Comment by thehesiod** [comment]
sorry, forgot `**` is only supported in python3.5.  Just pushed a fix.

@rouault yes the scripts need to be installed under the python version the module is installed with, on my system it ends up being `~/.pyenv/versions/3.6.4/bin/gdal_merge.py` so it won't conflict with other python versions and so it references the correct python version in the script header (with this when mine is installed it adds `#!/Users/amohr/.pyenv/versions/3.6.4/bin/python3`)   This fix is needed for systems that install the gdal deb w/o python support (important for systems that don't have a python version available yet).  This fix can co-exist with systems that install the deb with the scripts support.  Having the python module not install the scripts is an oversight since if you're installing the python module it means you installed gdal c++ lib w/o python support.  This change is the "approved" way for installing scripts from your python module.

**Comment by rouault** [comment]
@thehesiod  Shouldn't the ```for f in $(SCRIPTS) ; do $(INSTALL) $$f $(DESTDIR)$(INST_BIN) ; done``` line be removed from swig/python/GNUmakefile, since when actually doing "make install" from your branch I can see that what you added and that line do the same.

```
$ make install
[....]
running install_scripts
copying build/scripts-2.7/mkgraticule.py -> /home/even/gdal/git/gdal/gdal/../install/bin
copying build/scripts-2.7/gdal_auth.py -> /home/even/gdal/git/gdal/gdal/../install/bin
copying build/scripts-2.7/gdal_proximity.py -> /home/even/gdal/git/gdal/gdal/../install/bin
[....]
for f in `ls ./scripts/*.py` ; do  /home/even/gdal/git/gdal/gdal/install-sh -c $f /home/even/gdal/git/gdal/gdal/../install/bin ; done
```

@sebastic From the above, it seems to me that that shouldn't have no impact on packaging. Well as far as I can understand it.

**Comment by thehesiod** [comment]
@rouault if I were to do that I would break downstream packages :)  This change is only for people who don't install gdal with scripts.  This should have no impact on existing distributions because those who build gdal with scripting support won't install the python module from pypi (since module will already be installed), and those that do install the pypi module module from pypi will have the scripts in a location that can't conflict with the other in any case.  Hope that makes sense.

**Comment by rouault** [comment]
> if I were to do that I would break downstream packages :)

What would exactly break ? In my above make install output, one can see that the scripts get installed twice in $PREFIX/bin. Once with your new stuff, and another with the manual ```for f in $(SCRIPTS) ; do $(INSTALL) $$f $(DESTDIR)$(INST_BIN) ;``` step

**Comment by thehesiod** [comment]
running make:
`libtool: install: /Users/amohr/dev/thehesiod/gdal/gdal/install-sh -c ./scripts/esri2wkt.py /usr/local/bin/esri2wkt.py`

and setup.py: 
`Installing esri2wkt.py script to /Users/amohr/.pyenv/versions/3.6.4/bin`

so it would break downstream packages and people's usage that depends on it being in /usr/local or whatever configured via `configure`

**Comment by thehesiod** [comment]
🍾 thanks!

**Pull request merged**
