### PR TITLE
MRF: Use shared libraries for brunsli

### PR DESCRIPTION
**Pull request by lucianpls**
## What does this PR do?

Use the C API for brunsli.

## What are related issues/pull requests?
#3945

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by rouault** [comment]
It breaks existing tests in mrf.py

**Comment by rouault** [comment]
could you amend your commit messages to have a "MRF: " prefix? Thanks

**Comment by lucianpls** [comment]
Hm.. not sure if this is what you meant

**Comment by rouault** [comment]
> Hm.. not sure if this is what you meant, looks like I made it worse

use "git fetch origin master && git rebase -i origin/master" to clean the history

**Comment by lucianpls** [comment]
Redoing the request as a single commit

**Pull request closed without merging**
