### PR TITLE
CI: Skip running on pushes to dependabot and backport branches

### LINKED ISSUE #9851: Feedback wanted about limiting duplicated CI runs
### Feature description

I want to hear about the use cases here before doing the PR I want to make, to better understand which of the two options I would choose.

### Additional context

I observed that some jobs seem to run on push and pull_request for a same commit, like the PRs that are made from the backport mechanism. Since there is a lot of long workflows here, and only 20 runners for all the OSGeo organization, waiting for CI for 3-4 hours to start isn't uncommon, so avoiding jobs and even 30 secs to 1 min here and there counts on contribution-heavy days, (and we want to keep contributions).

I want to clear up the branch filtering on workflows on push events, such as they are only run for pushes to the special branches, like master and the release branches (the ones that will have the updated CI workflows). But for me to know if it is adapted to the reality here, I want to know:
- Is there any other (active or future) branches in the repo that need to have workflows run on pushes (not PRs)?
- In forks, especially the ones of the major maintainers (like Evan Rouault), do you make a PR to your fork before creating the one that will run against the base repo? Or you exclusively rely on the CI to run on every push, not only when you are ready for it to get pushed?

Depending on the results of these questions (especially the second one), I can choose one of two options:
1. The simple one: Limit workflows that run on pushes of branches to `master` and `release/*`. Thus, `dependabot/*` and `backport-(PR)-to-release/*` would not be run uselessly. This has the effect of also applying this to the forks, thus forks needing to create PRs (to the master branch of their forks, for example) for their new feature branches to run CI.
2. A bit more complicated: If we want the same behaviour, but only when it is the base repo (https://github.com/OSGeo/gdal), since the `on:` event triggers don't support filtering by repo, and that we want fewer restrictions on forks than in the base repo, I would need to write a long `if: ` condition to each job (not workflow, jobs inside workflows), that reimplements the pattern wanted (restrictions on pushes to branches when it is the base repo, same restrictions as before when not OSGeo/gdal repo). It wouldn't be as nice and clear, but should work. They will still cause an entry in the actions tab, with an id assigned, but will show up as skipped, since all jobs would have been skipped at the job level.

Currently, on debugging another CI improvement I want to file a PR for CodeQL, since I have a PR to my fork, I have most workflows do duplicated jobs, and use up all the runners available only for one commit (even the workflows for PRs don't manage to run without being queued a long time).

Otherwise, we could discuss which workflows need to run or not on pushes to branches in all repos (the base one and forks), and apply solution 1 to some workflows, and solution 2 to only specific ones, if it is needed.

### PR DESCRIPTION
**Pull request by echoix**
## What does this PR do?

Adds `dependabot**` to push's branches-ignore for workflows with a `push` event trigger.
For CodeQL's workflow, it was also missing the branches-ignore for the `backport**` branches, it got also added.

## What are related issues/pull requests?
Closes #9851

## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Updated Python API documentation (swig/include/python/docs/)
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by echoix** [comment]
The failing tests are unexpected here, as it's impossible that the lines I changed affect anything else that if a workflow is run on push or not.

**Comment by rouault** [comment]
yes we have regular flakes mostly due to using network resources

**Comment by echoix** [comment]
> yes we have regular flakes mostly due to using network resources

I see

**Comment by echoix** [comment]
Is there a chance that the changes from this PR (or at least the first commit) be applied to some of the active release branches? The problem it solves isn’t respected yet, until newer release branches are made. Some duplicated runs of 1h+ each have happened multiple times in the last week.

**Comment by rouault** [comment]
I've just cherry-picked those 2 commits into release/3.9. BTW, I'm wondering how you notice a duplicated run in the noise of all CI jobs...

**Comment by echoix** [comment]
I looked in the Actions tab, then looking at only CodeQL. I wanted to estimate how much my other PR had an effect after all. And saw multiple backport PRs that had two runs one after the other, with a queue+runtime in the 1h30m range. One for push of commit, another for pull_request.

I only take time to analyze CI here when the CI I launch for in grass are queued and none of ours are in progress.

There's also a couple of runs here that are in progress for a year, but it's "impossible", and I don't think it counts in the available runners though. These jammed runs have been showing up since at least January (that I'm aware of).

**Pull request merged**
