### PR TITLE
Compile with cmake(test)

### PR DESCRIPTION
**Pull request by miurahr**

### CODE REVIEW

**Comment by miurahr** [comment]
sorry I make mistake...

**Comment by BishopGIS** [comment]
The improved version of CMake4GDAL (now named Borsch) is here: https://github.com/nextgis-borsch/lib_gdal

1. Ability to create all-in-one library (static/dynamic)
2. Mac OS X, android, iOS build support
3. Dependency resolution
4. Driver dependency checking
5. Packaging via nsis, deb, rpm etc.
6. Right install paths (tested on Windows, Linux, Mac OS) and version/soversion etc.

**Comment by miurahr** [comment]
Thank you for up-to-date information. @BishopGIS I'm wandering why the borsch project does not merge here.

**Comment by BishopGIS** [comment]
It's not ready yet - see the drivers ready table in readme.md (https://github.com/nextgis-borsch/lib_gdal/blob/master/README.md). The star marked drivers are required. 
Also, there are some opened tickets, that need to be fixed (https://github.com/nextgis-borsch/lib_gdal/issues).

**Pull request closed without merging**
