### PR TITLE
Add OGR_G_GeodesicArea() and ST_Area(geom, use_ellipsoid)

### PR DESCRIPTION
**Pull request by rouault**
- Add OGR_G_GeodesicArea() / OGRSurface::get_GeodesicArea()
- SQLite SQL dialect: implement ST_Area(geom, use_ellipsoid)
- GPKG: implement ST_Area(geom, use_ellipsoid)

### CODE REVIEW

**Comment by jratike80** [comment]
Does the method return similar areas than for example Proj and PostGIS? See https://github.com/qgis/QGIS/issues/40888.

**Comment by rouault** [comment]
> Does the method return similar areas than for example Proj and PostGIS?

yes, it uses PROJ's geodesic.c functionality, which comes from GeographicLib. Using your QGIS example:
```python
from osgeo import ogr, osr
g = ogr.CreateGeometryFromWkt('POLYGON ((20.13293641   59.95688345,26.94617837   60.47397663, 29.74782155   62.56499443, 27.45254202   68.70650340, 23.75771765   68.24937206,25.42698984   65.27444593,21.51545237   63.10353609, 21.40562760   61.12318104,19.41123592   60.40477513,20.13293641   59.95688345))')
srs = osr.SpatialReference()
srs.ImportFromEPSG(4326)
srs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
g.AssignSpatialReference(srs)
print(g.AreaOnEllipsoid())
```
returns 251199344354.43042 as PostGIS
```
autotest=# select st_area(st_setsrid('POLYGON ((20.13293641   59.95688345,26.94617837   60.47397663, 29.74782155   62.56499443, 27.45254202   68.70650340, 23.75771765   68.24937206,25.42698984   65.27444593,21.51545237   63.10353609, 21.40562760   61.12318104,19.41123592   60.40477513,20.13293641   59.95688345))'::geography, 4326), true);
      st_area      
-------------------
 251199344354.4303
```

**Comment by rouault** [comment]
Interestingly, Spatialite's ST_Area() implementation doesn't give the same results. Diagnosis in https://groups.google.com/g/spatialite-users/c/mxTQKYLP8HM . With this pull request however, GDAL will install its ST_Area() implementation on top of Spatialite one, so in a GDAL context, results returned by ST_Area() on a Spatialite or GeoPackage DB, will be the expected ones (that is the ones from PROJ / GeographicLib)

**Comment by rouault** [comment]
Functions renamed to OGR_G_GeodesicArea() / OGRSurface::get_GeodesicArea()

**Pull request merged**
