### PR TITLE
Add RFC 48: Geographical networks support implementation

### PR DESCRIPTION
**Pull request by BishopGIS**
This is the results of integration of GSoC2014 work on geographical networks support in  GDAL

### CODE REVIEW

**Comment by rouault** [comment]
There are a few Pyflakes errors that stops the build. See https://travis-ci.org/OSGeo/gdal/builds/70382152

**Comment by rouault** [comment]
Following patch needed to fix compilation:

```
diff --git a/gdal/gnm/gnmnetwork.cpp b/gdal/gnm/gnmnetwork.cpp
index 5625f02..bb929f8 100644
--- a/gdal/gnm/gnmnetwork.cpp
+++ b/gdal/gnm/gnmnetwork.cpp
@@ -85,7 +85,7 @@ OGRFeatureH CPL_DLL GNMGetFeatureByGlobalFID (GNMNetworkH hNet, GNMGFID nGFID)
 {
     VALIDATE_POINTER1( hNet, "GNMGetFeatureByGlobalFID", NULL );
 
-    return ((GNMNetwork*)hNet)->GetFeatureByGlobalFID(nGFID);
+    return (OGRFeatureH) ((GNMNetwork*)hNet)->GetFeatureByGlobalFID(nGFID);
 }
 
 OGRLayerH CPL_DLL GNMGetPath (GNMNetworkH hNet, GNMGFID nStartFID,
@@ -94,6 +94,6 @@ OGRLayerH CPL_DLL GNMGetPath (GNMNetworkH hNet, GNMGFID nStartFID,
 {
     VALIDATE_POINTER1( hNet, "GNMGetPath", NULL );
 
-    return ((GNMNetwork*)hNet)->GetPath(nStartFID, nEndFID, eAlgorithm,
+    return (OGRLayerH) ((GNMNetwork*)hNet)->GetPath(nStartFID, nEndFID, eAlgorithm,
                                         papszOptions);
 }
```

**Comment by rouault** [comment]
The following is needed to compile the python bindings

```
diff --git a/gdal/swig/python/setup.py b/gdal/swig/python/setup.py
index 5332196..c50dcc4 100644
--- a/gdal/swig/python/setup.py
+++ b/gdal/swig/python/setup.py
@@ -28,7 +28,7 @@ BUILD_FOR_CHEESESHOP = False
 # (may be overriden with setup.cfg or command line switches).
 # ---------------------------------------------------------------------------
 
-include_dirs = ['../../port', '../../gcore', '../../alg', '../../ogr/', '../../gnm']
+include_dirs = ['../../port', '../../gcore', '../../alg', '../../ogr/', '../../ogr/ogrsf_frmts', '../../gnm']
 library_dirs = ['../../.libs', '../../']
 libraries = ['gdal']
```

**Comment by rouault** [comment]
When running  valgrind --leak-check=full python gnm_test.py, a few leaks are reported

```
==4211== 
==4211== 1,646 (48 direct, 1,598 indirect) bytes in 1 blocks are definitely lost in loss record 2,512 of 2,637
==4211==    at 0x4C27CC1: operator new(unsigned long) (vg_replace_malloc.c:261)
==4211==    by 0x8074BE9: __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<long long const, long long> > >::allocate(unsigned long, void const*) (new_allocator.h:89)
==4211==    by 0x80747CD: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_get_node() (stl_tree.h:359)
==4211==    by 0x8073EF2: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_create_node(std::pair<long long const, long long> const&) (stl_tree.h:369)
==4211==    by 0x8072C9C: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_insert_(std::_Rb_tree_node_base const*, std::_Rb_tree_node_base const*, std::pair<long long const, long long> const&) (stl_tree.h:881)
==4211==    by 0x807058D: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_insert_unique_(std::_Rb_tree_const_iterator<std::pair<long long const, long long> >, std::pair<long long const, long long> const&) (stl_tree.h:1215)
==4211==    by 0x806C751: std::map<long long, long long, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::insert(std::_Rb_tree_iterator<std::pair<long long const, long long> >, std::pair<long long const, long long> const&) (stl_map.h:540)
==4211==    by 0x8069E4C: std::map<long long, long long, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::operator[](long long const&) (stl_map.h:450)
==4211==    by 0x8075DB2: GNMGenericLayer::GetNextFeature() (gnmlayer.cpp:219)
==4211==    by 0x8075F5F: GNMGenericLayer::GetFeature(long long) (gnmlayer.cpp:243)
==4211==    by 0x805BE79: GNMGenericNetwork::GetFeatureByGlobalFID(long long) (gnmgenericnetwork.cpp:425)
==4211==    by 0x805E06C: GNMGenericNetwork::FillResultLayer(OGRGNMWrappedResultLayer*, std::vector<std::pair<long long, long long>, std::allocator<std::pair<long long, long long> > > const&, int, bool, bool) (gnmgenericnetwork.cpp:987)
==4211== 
==4211== 1,742 (48 direct, 1,694 indirect) bytes in 1 blocks are definitely lost in loss record 2,515 of 2,637
==4211==    at 0x4C27CC1: operator new(unsigned long) (vg_replace_malloc.c:261)
==4211==    by 0x8074BE9: __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<long long const, long long> > >::allocate(unsigned long, void const*) (new_allocator.h:89)
==4211==    by 0x80747CD: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_get_node() (stl_tree.h:359)
==4211==    by 0x8073EF2: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_create_node(std::pair<long long const, long long> const&) (stl_tree.h:369)
==4211==    by 0x8072C9C: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_insert_(std::_Rb_tree_node_base const*, std::_Rb_tree_node_base const*, std::pair<long long const, long long> const&) (stl_tree.h:881)
==4211==    by 0x8072E1B: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_insert_unique(std::pair<long long const, long long> const&) (stl_tree.h:1177)
==4211==    by 0x80705A5: std::_Rb_tree<long long, std::pair<long long const, long long>, std::_Select1st<std::pair<long long const, long long> >, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::_M_insert_unique_(std::_Rb_tree_const_iterator<std::pair<long long const, long long> >, std::pair<long long const, long long> const&) (stl_tree.h:1217)
==4211==    by 0x806C751: std::map<long long, long long, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::insert(std::_Rb_tree_iterator<std::pair<long long const, long long> >, std::pair<long long const, long long> const&) (stl_map.h:540)
==4211==    by 0x8069E4C: std::map<long long, long long, std::less<long long>, std::allocator<std::pair<long long const, long long> > >::operator[](long long const&) (stl_map.h:450)
==4211==    by 0x8075DB2: GNMGenericLayer::GetNextFeature() (gnmlayer.cpp:219)
==4211==    by 0x8075F5F: GNMGenericLayer::GetFeature(long long) (gnmlayer.cpp:243)
==4211==    by 0x805BE79: GNMGenericNetwork::GetFeatureByGlobalFID(long long) (gnmgenericnetwork.cpp:425)
==4211== 

==4211== 6,062 (48 direct, 6,014 indirect) bytes in 1 blocks are definitely lost in loss record 2,593 of 2,637
==4211==    at 0x4C27CC1: operator new(unsigned long) (vg_replace_malloc.c:261)
==4211==    by 0x8065947: __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<long long const, CPLString> > >::allocate(unsigned long, void const*) (new_allocator.h:89)
==4211==    by 0x80655F5: std::_Rb_tree<long long, std::pair<long long const, CPLString>, std::_Select1st<std::pair<long long const, CPLString> >, std::less<long long>, std::allocator<std::pair<long long const, CPLString> > >::_M_get_node() (stl_tree.h:359)
==4211==    by 0x80651E6: std::_Rb_tree<long long, std::pair<long long const, CPLString>, std::_Select1st<std::pair<long long const, CPLString> >, std::less<long long>, std::allocator<std::pair<long long const, CPLString> > >::_M_create_node(std::pair<long long const, CPLString> const&) (stl_tree.h:369)
==4211==    by 0x806459A: std::_Rb_tree<long long, std::pair<long long const, CPLString>, std::_Select1st<std::pair<long long const, CPLString> >, std::less<long long>, std::allocator<std::pair<long long const, CPLString> > >::_M_insert_(std::_Rb_tree_node_base const*, std::_Rb_tree_node_base const*, std::pair<long long const, CPLString> const&) (stl_tree.h:881)
==4211==    by 0x8063443: std::_Rb_tree<long long, std::pair<long long const, CPLString>, std::_Select1st<std::pair<long long const, CPLString> >, std::less<long long>, std::allocator<std::pair<long long const, CPLString> > >::_M_insert_unique_(std::_Rb_tree_const_iterator<std::pair<long long const, CPLString> >, std::pair<long long const, CPLString> const&) (stl_tree.h:1215)
==4211==    by 0x8062367: std::map<long long, CPLString, std::less<long long>, std::allocator<std::pair<long long const, CPLString> > >::insert(std::_Rb_tree_iterator<std::pair<long long const, CPLString> >, std::pair<long long const, CPLString> const&) (stl_map.h:540)
==4211==    by 0x806149A: std::map<long long, CPLString, std::less<long long>, std::allocator<std::pair<long long const, CPLString> > >::operator[](long long const&) (stl_map.h:450)
==4211==    by 0x805F7C3: GNMGenericNetwork::LoadFeaturesLayer(GDALDataset*) (gnmgenericnetwork.cpp:1346)
==4211==    by 0x807BD62: GNMFileNetwork::Open(GDALOpenInfo*) (gnmfilenetwork.cpp:123)
==4211==    by 0x807B0AA: GNMFileDriverDelete(char const*) (gnmfiledriver.cpp:119)
==4211==    by 0x79FE6E3: GDALDriver::Delete(char const*) (gdaldriver.cpp:942)


==4211== 10,452 (1,344 direct, 9,108 indirect) bytes in 6 blocks are definitely lost in loss record 2,609 of 2,637
==4211==    at 0x4C27CC1: operator new(unsigned long) (vg_replace_malloc.c:261)
==4211==    by 0x807CCE6: GNMFileNetwork::LoadNetworkLayer(char const*) (gnmfilenetwork.cpp:410)
==4211==    by 0x805F7FE: GNMGenericNetwork::LoadFeaturesLayer(GDALDataset*) (gnmgenericnetwork.cpp:1349)
==4211==    by 0x807BD62: GNMFileNetwork::Open(GDALOpenInfo*) (gnmfilenetwork.cpp:123)
==4211==    by 0x807AEE2: GNMFileDriverOpen(GDALOpenInfo*) (gnmfiledriver.cpp:82)
==4211==    by 0x79EE8EB: GDALOpenEx (gdaldataset.cpp:2569)
==4211==    by 0x6A6E3A1: OpenEx(char const*, unsigned int, char**, char**, char**) (gdal_wrap.cpp:5770)
==4211==    by 0x6A70B74: _wrap_OpenEx (gdal_wrap.cpp:24178)
==4211==    by 0x4A79BD: PyEval_EvalFrameEx (in /usr/bin/python2.6)
==4211==    by 0x4A82AF: PyEval_EvalFrameEx (in /usr/bin/python2.6)
==4211==    by 0x4A82AF: PyEval_EvalFrameEx (in /usr/bin/python2.6)
==4211==    by 0x4A82AF: PyEval_EvalFrameEx (in /usr/bin/python2.6)
==4211== 

```

**Comment by BishopGIS** [comment]
Is still any blocking issues to merge this?

**Comment by rouault** [comment]
@BishopGIS According to Travis, it breaks the building of the Java bindings

**Comment by BishopGIS** [comment]
Travis build passed

**Comment by rouault** [comment]
Before merging, I think it would be appropriate if you raise a formal motion to approve RFC 48 (I didn't check if the RFC text needs updates w.r.t to your recent changes ?)

**Comment by rouault** [comment]
Was merged into trunk

**Pull request closed without merging**
