### PR TITLE
Update mitab_spatialref.cpp

### PR DESCRIPTION
**Pull request by JamesRamm**
Adds the authority code for irish national grid. 
Without this, all SRS info is lost when converting to MITAB from e.g. shapefile

### CODE REVIEW

**Comment by rouault** [comment]
Committed in r35270

**Comment by JamesRamm** [comment]
I also get a slight offset with the transform params. in `spatialref.cpp` they are reported as:

    { 0,    42, "Ireland_1965",                13,506,  -122, 611, 0, 0, 0, 0, 0},

Looking at epsg.io (http://epsg.io/29902), the params should be:

            TOWGS84[482.5,-130.6,564.6,-1.042,-0.214,-0.631,8.15],

So now I'm wondering, should `Ireland_1965` in MITAB be updated with the correct params, or is `Ireland_1965` intentionally different to `TM65_Irish_Grid` and it warrants a new line?

I doubt that there would be 2 SRS defintions for Ireland dating from 1965, so I think just updating with the correct params is the correct way forward?

**Comment by rouault** [comment]
Yeah, I just noticed the same. As there seems to be only one possible datum shift to WGS84 (we're lucky!), it would probably make sense to update the table in spatialref.cpp. 
That said, the values of the array are written in the .map file, so I think it would be best to first check if MapInfo still recognizes the datum even if we change the parameters.

**Comment by JamesRamm** [comment]
Ok
I will need to wait until our 1 mapinfo license is available for use!

**Comment by JamesRamm** [comment]
Ok, that line does need updating and MapInfo will be fine with the update. My colleague will probably update this in a different PR

**Pull request closed without merging**
