### PR TITLE
FlatGeobuf: Filtering fixes

### PR DESCRIPTION
**Pull request by bjornharrtell**
Early adopters has found potential problems when doing spatial filtering but I cannot reproduce yet. This basic test does not hurt though.

### CODE REVIEW

**Comment by rouault** [comment]
Seems this breaks on most platforms, and those have GEOS enabled. So I'd suspect your local build doesn't have GEOS enabled. You might different case in the test depending on if GEOS is enabled or not

**Comment by rouault** [comment]
I also notice a `flatbuffers/flatbuffers.h:2101:27: runtime error: unsigned integer overflow: 1260 - 18446744073709551592 cannot be represented in type 'unsigned long'`
The code is probably fine. The method might be qualified with CPL_NOSANITIZE_UNSIGNED_INT_OVERFLOW to avoid it

**Comment by bjornharrtell** [comment]
Will see if I can reproduce issues with GEOS enabled.

PS. I've seen the overflow before and it makes me a bit uneasy, especially considering the "Early adopters has found potential problems" thing.

**Comment by rouault** [comment]
> I've seen the overflow before and it makes me a bit uneasy, especially considering the "Early adopters has found potential problems" thing.

unsigned integer overflow is a well defined behaviour in C, and from the comment in the code, it seems intended here. It is just that most of the time it is not that intended, hence I've enabled it in the sanitize target, so that we are sure to use it when we really need it. Most of the time it can be avoided, or if not practical tagged with this CPL_NOSANITIZE_UNSIGNED_INT_OVERFLOW macro

**Comment by bjornharrtell** [comment]
@rouault you are right, I can reproduce the failures if I compile with GEOS... however, I find it very strange that the GEOS secondary filter is eliminating all candidates where it definitely should not. Suspected axis order issues but doesn't seem so.

**Comment by bjornharrtell** [comment]
I think I found the issue. Filtering was actually not working as it should at all and I believe a bug crept in it in one of the last refactorings I made for GetNextFeature(), so this PR is both now a bugfix and added test.

**Pull request merged**
