### PR TITLE
Improve ogr dxf driver spline entity reading (ticket #6436)

### PR DESCRIPTION
**Pull request by perob**
Changed source code and added tests with data.

Read full definition of spline entity (degree, control points, weights and knots) from dxf files and create spline. If only degree and control points found in dxf file then recalculate knots. Weights are always 1 if not present in dxf file.

### CODE REVIEW

**Comment by rouault** [comment]
The Travis build errors with :
```
  TEST: ogr_dxf_30 ... OGRFeature(entities):1
  Layer (String) = 0
  SubClasses (String) = AcDbEntity:AcDbSpline
  ExtendedEntity (String) = (null)
  Linetype (String) = (null)
  EntityHandle (String) = 24C
  Text (String) = (null)
  LINESTRING (0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,0 0,14 2)

fail
    line 123: Error in vertex 0, off by 14.
```

**Comment by perob** [comment]
Ah, thanks.
I created test files manually and obviously made some mistakes which passed through sanity checks.

I will add some more sanity checks.

**Comment by perob** [comment]
That is it. Ready for commit.

**Comment by rouault** [comment]
Merged in r33888. Thanks

**Pull request closed without merging**
