### PR TITLE
configure.ac: optimize the jni_lib compatibility.

### LINKED ISSUE #2313: Build fails on MacOS with java and hdfs support
## Expected behavior and actual behavior.

Build success.
Supporting `libjvm.dylib` to build.

## Steps to reproduce the problem.

```bash
./configure --prefix=/usr/local/Cellar/gdal/2.4.0 --with-java=$JAVA_HOME --with-hdfs=$HADOOP_HOME
```
output:
```bash
checking GDAL version information from gdal_version.h.in: 2.4.0
checking for Mac OS X Framework build... disabled
checking for perl bindings... disabled
checking for python bindings... disabled
checking whether we should include Java support... yes
configure: error: Unable to find libjvm.so.
```
image
In above image, i only have libjvm.dylib instead of libjvm.so. And i check the `configure.ac` file, it doesn't consider of `libjvm.dylib`. [related link in configure.ac](https://github.com/OSGeo/gdal/blob/9d4d488a492510fdf3b20d8b74aba06ebeb5ba76/gdal/configure.ac#L5387)
## Operating system

Mac OSX 10.15.3

## GDAL version and provenance

2.4.0

### PR DESCRIPTION
**Pull request by esmeetu**
fixes #2313

### CODE REVIEW

**Comment by rouault** [comment]
thanks, can you run "autoconf" to regenerate the "configure" file as well, and commit it ?

**Comment by esmeetu** [comment]
yes, after `autoconf`, `configure` runs well.

**Comment by rouault** [comment]
> yes, after `autoconf`, `configure` runs well.

Cool. But my point is that you need to "git commit" & "git push" the updated configure, because it is under version control (I know this is unusual)

**Comment by esmeetu** [comment]
i don't know why the unexpected `runstatedir` things in the `configure` file was added. 
Should i remove those manually?

**Comment by rouault** [comment]
> Should i add those manually?

no, that's fine. There are some small variations in the output of autoconf, depending on the actual version. I've seen those a few times, and I think they are fine

**Comment by esmeetu** [comment]
ok. Perhaps my `autoconf` is 2.69, and that option is supported in 2.70.
Thanks. :)

**Pull request merged**
