### PR TITLE
Override $OPT when running python setup.py

### PR DESCRIPTION
**Pull request by bje-**
## What does this PR do?

Silences warnings produced by `python setup.py build` when building the Python C++ extensions. We can't control the autogenerated code (except for getting SWIG improved to produce cleaner code). The `setup.py` infrastructure also doesn't provide the ability to easily control the C++ compiler flags (see https://bugs.python.org/issue1222585). Overriding $OPT with a set of sensible flags is the most appropriate workaround in the meantime.

### CODE REVIEW

**Comment by rouault** [comment]
The  -Wno-unused-function thing should no longer be necessary since 647a198a06fde669c4cac664b6fbe4a966be5127
And I'm not enthusiastic about the -Wno-write-strings since it could hide issues in the GDAL specific code.

**Comment by rouault** [comment]
Wondering if a workaround couldn't be to make sure that the SWIG generate code does something like
```
#undef  PyMapping_Items
 #define PyMapping_Items(O) PyObject_CallMethod(O, const_cast<char*>("items"),NULL)
```
but only in the Python 2.X case

**Comment by bje-** [comment]
Thanks. Your change 647a198a06fde669c4cac664b6fbe4a966be5127 snuck in while I was working on a week old branch. :-) I have removed `-Wno-unused-function` and will consider a better approach to `-Wno-write-strings`.

**Comment by bje-** [comment]
Where do you propose to put that redefinition of the `PyMapping_Items` macro? I tried outting it in a `.i` file right below `#include <Python.h>` to no avail. I don't understand SWIG very well.

**Comment by rouault** [comment]
Fixed differently per https://github.com/OSGeo/gdal/commit/f7c9e1790b33db930745bd72a4a211e506ac8f78

**Pull request closed without merging**
