### PR TITLE
ogrinfo: make it available as a library function, and add JSON output

### PR DESCRIPTION
**Pull request by rouault**
Example of JSON output with ``ogrinfo autotest/ogr/data/poly.shp -json``

```json
{
  "description":"autotest/ogr/data/poly.shp",
  "driverShortName":"ESRI Shapefile",
  "driverLongName":"ESRI Shapefile",
  "layers":[
    {
      "name":"poly",
      "metadata":{
        "":{
          "DBF_DATE_LAST_UPDATE":"2018-08-02"
        },
        "SHAPEFILE":{
          "SOURCE_ENCODING":""
        }
      },
      "geometryFields":[
        {
          "name":"",
          "type":"Polygon",
          "nullable":true,
          "extent":[
            478315.53125,
            4762880.5,
            481645.3125,
            4765610.5
          ],
          "coordinateSystem":{
            "wkt":"PROJCRS[\"OSGB36 / British National Grid\",BASEGEOGCRS[\"OSGB36\",DATUM[\"Ordnance Survey of Great Britain 1936\",ELLIPSOID[\"Airy 1830\",6377563.396,299.3249646,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],ID[\"EPSG\",4277]],CONVERSION[\"British National Grid\",METHOD[\"Transverse Mercator\",ID[\"EPSG\",9807]],PARAMETER[\"Latitude of natural origin\",49,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8801]],PARAMETER[\"Longitude of natural origin\",-2,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8802]],PARAMETER[\"Scale factor at natural origin\",0.9996012717,SCALEUNIT[\"unity\",1],ID[\"EPSG\",8805]],PARAMETER[\"False easting\",400000,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8806]],PARAMETER[\"False northing\",-100000,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8807]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1]],USAGE[SCOPE[\"Engineering survey, topographic mapping.\"],AREA[\"United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.\"],BBOX[49.75,-9,61.01,2.01]],ID[\"EPSG\",27700]]",
            "projjson":{
              "$schema":"https://proj.org/schemas/v0.6/projjson.schema.json",
              "type":"ProjectedCRS",
              "name":"OSGB36 / British National Grid",
              "base_crs":{
                "name":"OSGB36",
                "datum":{
                  "type":"GeodeticReferenceFrame",
                  "name":"Ordnance Survey of Great Britain 1936",
                  "ellipsoid":{
                    "name":"Airy 1830",
                    "semi_major_axis":6377563.396,
                    "inverse_flattening":299.3249646
                  }
                },
                "coordinate_system":{
                  "subtype":"ellipsoidal",
                  "axis":[
                    {
                      "name":"Geodetic latitude",
                      "abbreviation":"Lat",
                      "direction":"north",
                      "unit":"degree"
                    },
                    {
                      "name":"Geodetic longitude",
                      "abbreviation":"Lon",
                      "direction":"east",
                      "unit":"degree"
                    }
                  ]
                },
                "id":{
                  "authority":"EPSG",
                  "code":4277
                }
              },
              "conversion":{
                "name":"British National Grid",
                "method":{
                  "name":"Transverse Mercator",
                  "id":{
                    "authority":"EPSG",
                    "code":9807
                  }
                },
                "parameters":[
                  {
                    "name":"Latitude of natural origin",
                    "value":49,
                    "unit":"degree",
                    "id":{
                      "authority":"EPSG",
                      "code":8801
                    }
                  },
                  {
                    "name":"Longitude of natural origin",
                    "value":-2,
                    "unit":"degree",
                    "id":{
                      "authority":"EPSG",
                      "code":8802
                    }
                  },
                  {
                    "name":"Scale factor at natural origin",
                    "value":0.9996012717,
                    "unit":"unity",
                    "id":{
                      "authority":"EPSG",
                      "code":8805
                    }
                  },
                  {
                    "name":"False easting",
                    "value":400000,
                    "unit":"metre",
                    "id":{
                      "authority":"EPSG",
                      "code":8806
                    }
                  },
                  {
                    "name":"False northing",
                    "value":-100000,
                    "unit":"metre",
                    "id":{
                      "authority":"EPSG",
                      "code":8807
                    }
                  }
                ]
              },
              "coordinate_system":{
                "subtype":"Cartesian",
                "axis":[
                  {
                    "name":"Easting",
                    "abbreviation":"E",
                    "direction":"east",
                    "unit":"metre"
                  },
                  {
                    "name":"Northing",
                    "abbreviation":"N",
                    "direction":"north",
                    "unit":"metre"
                  }
                ]
              },
              "scope":"Engineering survey, topographic mapping.",
              "area":"United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.",
              "bbox":{
                "south_latitude":49.75,
                "west_longitude":-9,
                "north_latitude":61.01,
                "east_longitude":2.01
              },
              "id":{
                "authority":"EPSG",
                "code":27700
              }
            },
            "dataAxisToSRSAxisMapping":[
              1,
              2
            ]
          }
        }
      ],
      "featureCount":10,
      "fields":[
        {
          "name":"AREA",
          "type":"Real",
          "width":12,
          "precision":3,
          "nullable":true,
          "uniqueConstraint":false
        },
        {
          "name":"EAS_ID",
          "type":"Integer64",
          "width":11,
          "nullable":true,
          "uniqueConstraint":false
        },
        {
          "name":"PRFEDEA",
          "type":"String",
          "width":16,
          "nullable":true,
          "uniqueConstraint":false
        }
      ]
    }
  ],
  "metadata":{
  },
  "domains":{
  }
}
```

Example of JSON output with ``ogrinfo autotest/ogr/data/poly.shp -json -features -where "fid=1"`` to dump features as well

```json
{
  "description":"autotest/ogr/data/poly.shp",
  "driverShortName":"ESRI Shapefile",
  "driverLongName":"ESRI Shapefile",
  "layers":[
    {
      "name":"poly",
      "metadata":{
        "":{
          "DBF_DATE_LAST_UPDATE":"2018-08-02"
        },
        "SHAPEFILE":{
          "SOURCE_ENCODING":""
        }
      },
      "geometryFields":[
        {
          "name":"",
          "type":"Polygon",
          "nullable":true,
          "extent":[
            478315.53125,
            4762880.5,
            481645.3125,
            4765610.5
          ],
          "coordinateSystem":{
            "wkt":"PROJCRS[\"OSGB36 / British National Grid\",BASEGEOGCRS[\"OSGB36\",DATUM[\"Ordnance Survey of Great Britain 1936\",ELLIPSOID[\"Airy 1830\",6377563.396,299.3249646,LENGTHUNIT[\"metre\",1]]],PRIMEM[\"Greenwich\",0,ANGLEUNIT[\"degree\",0.0174532925199433]],ID[\"EPSG\",4277]],CONVERSION[\"British National Grid\",METHOD[\"Transverse Mercator\",ID[\"EPSG\",9807]],PARAMETER[\"Latitude of natural origin\",49,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8801]],PARAMETER[\"Longitude of natural origin\",-2,ANGLEUNIT[\"degree\",0.0174532925199433],ID[\"EPSG\",8802]],PARAMETER[\"Scale factor at natural origin\",0.9996012717,SCALEUNIT[\"unity\",1],ID[\"EPSG\",8805]],PARAMETER[\"False easting\",400000,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8806]],PARAMETER[\"False northing\",-100000,LENGTHUNIT[\"metre\",1],ID[\"EPSG\",8807]]],CS[Cartesian,2],AXIS[\"(E)\",east,ORDER[1],LENGTHUNIT[\"metre\",1]],AXIS[\"(N)\",north,ORDER[2],LENGTHUNIT[\"metre\",1]],USAGE[SCOPE[\"Engineering survey, topographic mapping.\"],AREA[\"United Kingdom (UK) - offshore to boundary of UKCS within 49°45'N to 61°N and 9°W to 2°E; onshore Great Britain (England, Wales and Scotland). Isle of Man onshore.\"],BBOX[49.75,-9,61.01,2.01]],ID[\"EPSG\",27700]]",
            "projjson":  "...snip..." ,
            "dataAxisToSRSAxisMapping":[
              1,
              2
            ]
          }
        }
      ],
      "featureCount":1,
      "fields":[
        {
          "name":"AREA",
          "type":"Real",
          "width":12,
          "precision":3,
          "nullable":true,
          "uniqueConstraint":false
        },
        {
          "name":"EAS_ID",
          "type":"Integer64",
          "width":11,
          "nullable":true,
          "uniqueConstraint":false
        },
        {
          "name":"PRFEDEA",
          "type":"String",
          "width":16,
          "nullable":true,
          "uniqueConstraint":false
        }
      ],
      "features":[
        {
          "type":"Feature",
          "properties":{
            "AREA":247328.172,
            "EAS_ID":179,
            "PRFEDEA":"35043423"
          },
          "fid":1,
          "geometry":{
            "type":"Polygon",
            "coordinates":[
              [
                [
                  480035.34375,
                  4765558.5
                ],
                [
                  480039.03125,
                  4765539.5
                ],
                [
                  479730.375,
                  4765400.5
                ],
                [
                  479647.0,
                  4765369.5
                ],
                [
                  479690.1875,
                  4765259.5
                ],
                [
                  479819.84375,
                  4765180.5
                ],
                [
                  479779.84375,
                  4765109.5
                ],
                [
                  479681.78125,
                  4764940.0
                ],
                [
                  479468.0,
                  4764942.5
                ],
                [
                  479411.4375,
                  4764940.5
                ],
                [
                  479353.0,
                  4764939.5
                ],
                [
                  479208.65625,
                  4764882.5
                ],
                [
                  479196.8125,
                  4764879.0
                ],
                [
                  479123.28125,
                  4765015.0
                ],
                [
                  479046.53125,
                  4765117.0
                ],
                [
                  479029.71875,
                  4765110.5
                ],
                [
                  479014.9375,
                  4765147.5
                ],
                [
                  479149.9375,
                  4765200.5
                ],
                [
                  479639.625,
                  4765399.5
                ],
                [
                  480035.34375,
                  4765558.5
                ]
              ]
            ]
          }
        }
      ]
    }
  ],
  "metadata":{
  },
  "domains":{
  }
}
```

### CODE REVIEW

**Comment by elpaso** [comment]
Nice! 

I noticed that in the examples there is an empty key `""` in the `metadata` dictionary, is that expected?

Also, I noticed a mix of underscore and camel case, I don't know if that comes from a pre-existing JSON schema and cannot be changed.

**Comment by rouault** [comment]
> I noticed that in the examples there is an empty key `""` in the `metadata` dictionary, is that expected?

yes, that's for the default metadata domain which has an empty name. We do the same for gdalinfo -json.

> Also, I noticed a mix of underscore and camel case

yes, camelCase is used in general, consistently with gdalinfo -json output.  under_score convention is used for the PROJJSON output, which follows an independent schema.

**Comment by sgillies** [comment]
@rouault maybe reconsider having ogrinfo dump out features? Then there would two different ways to get GeoJSON features: ogr2ogr and ogrinfo.

**Comment by rouault** [comment]
> maybe reconsider having ogrinfo dump out features?

@sgillies not sure to understand what you mean. Do you mean:
- removing the existing capability of ogrinfo in non-json mode to dump features ?  That would break backward compatibility, and the text dump mode is a bit more capable that GeoJSON as it supports non-GeoJSON compatible geometries, and multiple geometry fields per feature.
- or removing the proposed addition of this PR of dumping features in json mode with the new  -features switch ?  I was a bit hesitating about that. I did it for feature parity with text mode, but wouldn't mind removing. However I know @hobu asked me if that was GeoJSON features output, so it didn't look like he found this to be useless. That said, given how it is implemented, the dump of JSON features with ogrinfo -json -features wouldn't work with a arbitrarily large number of features given that a non-streaming JSON writer is used.

**Comment by sgillies** [comment]
@rouault my only concern was about adding a redundant capability. As ogrinfo already dumps features, I don't have any real grounds to object.

**Comment by landryb** [comment]
Wow,  i'll be able to replace all my `ogrinfo | egrep '^(Geometry|Layer name|Feature Count)'` calls by `ogrinfo | jq` ... much welcomed, thanks @rouault !

**Comment by rouault** [comment]
Just added a JSON schema for the output of ogrinfo -json: https://github.com/rouault/gdal/blob/ogrinfo_lib/data/ogrinfo_output.schema.json

**Comment by tomkralidis** [comment]
cc @pvgenuchten @kalxas 

sorry to be late to this discussion.  Is there any value to aligning the top level structure with STAC / GeoJSON as well here (for both `ogrinfo` and `gdalinfo` JSON output)?  Or course, one person's STAC item is another person's dataset, so we would need to clarify granularity.  Not sure if this has been discussed yet, but standing up a tree of geospatial data files and getting STAC/GeoJSON "out of the box" would be a powerful approach to a common use case.

**Comment by rouault** [comment]
gdalinfo -json since GDAL 3.6.0 outputs a "stac" node with content following the projection extension (https://github.com/stac-extensions/projection): cf example at https://github.com/OSGeo/gdal/pull/6849/files

For ogrinfo, it is less if/how vector datasets fit into STAC.

**Pull request merged**
