### PR TITLE
gfs: add XML schema

### PR DESCRIPTION
**Pull request by jechterhoff**
## What does this PR do?

It adds an XML Schema file for the gfs XML format.

## What are related issues/pull requests?

_none_

## Tasklist

 - [ ] Clarify all TBDs in the documentation annotations contained in the XML schema file
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

_irrelevant for this PR_

### CODE REVIEW

**Comment by jechterhoff** [comment]
@rouault Here is the PR, as discussed by email.

Your review of the XSD as well as the documentation annotations (including the TBDs and questions contained therein) would be much appreciated.

Questions / comments:

* Are the decisions regarding sequences and choices correct?
* Are the multiplicities, i.e., minOccurs and maxOccurs, correct?
* Are the chosen element types correct?
* Documentation annotations:
  * Please check the parts marked with 'TBD', and the questions written there.
  * Please check for other parts that the documentation is correct.

**Comment by rouault** [comment]
@jechterhoff Please look at https://github.com/jechterhoff/gdal/pull/1 against your fork and merge it and push again

**Comment by jechterhoff** [comment]
@rouault Done.

**Comment by rouault** [comment]
Thanks @jechterhoff !

**Comment by jechterhoff** [comment]
Thanks, @rouault, for all the clarifications and corrections in the gfs.xsd! 

That it is also possible to define a GMLFeatureClass without actual geometry field - presumably using `<GeometryType>None<GeometryType>` - is quite interesting, since it supports the provision of auxiliary, non-geometric feature data in a GML file. That, to me, is a very important nugget of information.

Some follow-up questions: 

* In the XSD you wrote that different GMLFeatureClass elements should have a different name. What happens if two GMLFeatureClass elements have the same name (and different ElementPaths)? Will such features then be loaded from different places in the data, and added to the same layer internally?
* A single Curve or Surface is not allowed as geometry type? Should LineString or Polygon be used as alternatives, then? Or would these cases have to be encoded in the GML data as MultiCurve and MultiSurface with just a single member?
* If the `Type` within a PropertyDefn is `Complex`, you wrote that it indicates that the value of the element is not a simple type. I wonder what the use cases are: Would the property value then have to be a feature object, which is declared as a GMLFeatureClass? Or does this even allow complex datatype values (without identity, having multiple sub-elements which represent attributes of that complex datatype)? That would be quite interesting to know.

**Comment by rouault** [comment]
> * What happens if two GMLFeatureClass elements have the same name (and different ElementPaths)? Will such features then be loaded from different places in the data, and added to the same layer internally?

I didn't try but probably that 2 layers of the same names will be created which will likely cause issues later if you use ogr2ogr for example to convert the GML to other format

> A single Curve or Surface is not allowed as geometry type? 

hum I might have been too quick on this. I've re-added that in the .xsd per commit 2a8182f8c4ce667e6d9ef6c39cf12e8fbcfa245d

> If the Type within a PropertyDefn is Complex, you wrote that it indicates that the value of the element is not a simple type. I wonder what the use cases are: Would the property value then have to be a feature object, which is declared as a GMLFeatureClass? Or does this even allow complex datatype values (without identity, having multiple sub-elements which represent attributes of that complex datatype)?

I'm not sure... I've never used that. I assume this was for things like ``<some_property><nested_content>foo</nested_content><nested_content2>bar</nested_content2></some_complex_property>``, but I'm not sure what the driver does. It might have been something anticipated that was never implemented. I let you experiment

**Comment by jechterhoff** [comment]
Thanks, @rouault. I performed some tests with the following files (conclusions and results are given at the end of this - now rather long - comment):

data.gml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ogr:FeatureCollection xmlns:ogr="http://ogr.maptools.org/" xmlns:gml="http://www.opengis.net/gml">
  <gml:featureMember>
    <ogr:FeatureA fid="FA1">
      <ogr:name>Feature A 1</ogr:name>
      <ogr:dt>
        <ogr:dtatt1>1</ogr:dtatt1>
        <ogr:dtatt2>2</ogr:dtatt2>
      </ogr:dt>
    </ogr:FeatureA>
  </gml:featureMember>
  <gml:featureMember>
    <ogr:FeatureB fid="FB1">
      <ogr:name>Feature B 1</ogr:name>
    </ogr:FeatureB>
  </gml:featureMember>
  <ogr:additionalObjects>
    <gml:featureMember>
      <ogr:FeatureA fid="FA2">
        <ogr:name>Feature A 2</ogr:name>
        <ogr:role>
          <ogr:FeatureB fid="FB2">
            <ogr:name>Feature B 2</ogr:name>
          </ogr:FeatureB>
        </ogr:role>
      </ogr:FeatureA>
    </gml:featureMember>
    <gml:featureMember>
      <ogr:FeatureB fid="FB3">
        <ogr:name>Feature B 3</ogr:name>
      </ogr:FeatureB>
    </gml:featureMember>
  </ogr:additionalObjects>
</ogr:FeatureCollection>
```

data.gfs:

```xml
<GMLFeatureClassList>
  <GMLFeatureClass>
    <Name>Feature Type A</Name>
    <ElementPath>FeatureA</ElementPath>
    <GeometryType>None</GeometryType>
    <PropertyDefn>
      <Name>name</Name>
      <ElementPath>name</ElementPath>
      <Type>String</Type>
    </PropertyDefn>
    <PropertyDefn>
      <Name>role</Name>
      <ElementPath>role</ElementPath>
      <Type>FeatureProperty</Type>
    </PropertyDefn>
    <PropertyDefn>
      <Name>datatype attribute</Name>
      <ElementPath>dt</ElementPath>
      <Type>Complex</Type>
    </PropertyDefn>
<!--    <PropertyDefn>
      <Name>datatype attribute 1</Name>
      <ElementPath>dt|dtatt1</ElementPath>
      <Type>Integer</Type>
    </PropertyDefn>
    <PropertyDefn>
      <Name>datatype attribute 2</Name>
      <ElementPath>dt|dtatt2</ElementPath>
      <Type>Integer</Type>
    </PropertyDefn>-->
  </GMLFeatureClass>
  <GMLFeatureClass>
    <Name>Feature Type B</Name>
    <ElementPath>FeatureB</ElementPath>
    <GeometryType>None</GeometryType>
    <PropertyDefn>
      <Name>name</Name>
      <ElementPath>name</ElementPath>
      <Type>String</Type>
    </PropertyDefn>
  </GMLFeatureClass>
  <!-- Duplicate GMLFeatureClass/Name will result in two layers with the same name - which is to be avoided. -->
  <!--<GMLFeatureClass>
    <Name>Feature Type B</Name>
    <ElementPath>role|FeatureB</ElementPath>
    <GeometryType>None</GeometryType>
    <PropertyDefn>
      <Name>name</Name>
      <ElementPath>name</ElementPath>
      <Type>String</Type>
    </PropertyDefn>
  </GMLFeatureClass>-->
</GMLFeatureClassList>
```

The result of `ogrinfo data.gml -ro -al` (run with GDAL 3.5.2, released 2022/09/02) is:

```
Layer name: Feature Type A
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
fid: String (0.0) NOT NULL
name: String (0.0)
role: String (0.0)
datatype attribute: String (0.0)
OGRFeature(Feature Type A):1
  fid (String) = FA1
  name (String) = Feature A 1

OGRFeature(Feature Type A):2
  fid (String) = FA2
  name (String) = Feature A 2
  role (String) = #FB2


Layer name: Feature Type B
Geometry: None
Feature Count: 3
Layer SRS WKT:
(unknown)
fid: String (0.0) NOT NULL
name: String (0.0)
OGRFeature(Feature Type B):1
  fid (String) = FB1
  name (String) = Feature B 1

OGRFeature(Feature Type B):2
  fid (String) = FB2
  name (String) = Feature B 2

OGRFeature(Feature Type B):3
  fid (String) = FB3
  name (String) = Feature B 3
```

Conclusions / results:

* `PropertyDefn/Type = Complex`: has no effect, at least as far as I can see - with or without the nested `dtatt1` and `dtatt2` elements.
* `PropertyDefn/Type = FeatureProperty` appears to work and be significant (same for `FeaturePropertyList`)! Using it in the definition of `FeatureTypeA/role`, the inline encoded `FeatureTypeB` element was recognized as another instance of FeatureTypeB, plus the object appears to be shown in the output as a reference value for property `role`: `role (String) = #FB2`. We should add `FeatureProperty` back as allowed value of `PropertyDefn/Type`, should we not? I tested with an additional FeatureTypeB object within `role`, and when the `PropertyDefn/Type` for `role` is set to `FeaturePropertyList`, the value for `role` appears to be a list of the references to both objects: `role (StringList) = (2:#FB2,#FB4)`. 
* Declaring two `GMLFeatureClass`es with same `Name` results in two layers with that name, and thus duplication - which should be avoided, I guess. We can check that `GMLFeatureClass/Name` values are unique with a unique constraint in the gfs.xsd, like so:

```xml
  <xs:element name="GMLFeatureClassList">
    <!-- ... original content of the GMLFeatureClassList schema omitted in this example ... -->
    <xs:unique name="uniqueGMLFeatureClassNames">
      <xs:selector xpath="GMLFeatureClass"/>
      <xs:field xpath="Name"/>
    </xs:unique>
  <xs:element>
```

Would you like me to create another PR for the addition of `FeatureType` and `FeatureTypeList` to `PropertyDefn/Type`, as well as the unique constraint to ensure that `GMLFeatureClass/Name` values are unique within the `GMLFeatureClassList`?

**Comment by rouault** [comment]
> Would you like me to create another PR for the addition of `FeatureType` and `FeatureTypeList` to `PropertyDefn/Type`, as well as the unique constraint to ensure that `GMLFeatureClass/Name` values are unique within the `GMLFeatureClassList`?

Yes, please.
It would probably great to enhance autotest/ogr/ogr_gml_read.py with tests for FeatureType/FeatureTypeList

**Comment by jechterhoff** [comment]
@rouault - Done - the new PR is #6695.

Unfortunately, I am not skilled enough in Python programming to enhance `autotest/ogr/ogr_gml_read.py` myself. However, I did review that file. `test_ogr_gml_56` seems to be related to `FeatureProperty` and `FeaturePropertyList`. That test refers to file `data/gml/ogr_gml_56.gfs`, which does not exist. I guess that it is generated on-the-fly from the `ogr_gml_56_schema.xsd`. For what it's worth, I also looked for any test that refers to `Complex`, but did not find anything related to it.

By the way: At the end of my previous comment I incorrectly referred to `FeatureProperty` and `FeaturePropertyList` as `FeatureType` and `FeatureTypeList`. I have edited my comment to fix that.

**Pull request merged**
