### PR TITLE
configure: add tirpc include path when available when building with OGDI support (fixes https://github.com/libogdi/ogdi/issues/20)

### PR DESCRIPTION
**Pull request by rouault**
@sebastic  what about that ?

### CODE REVIEW

**Comment by sebastic** [comment]
This works. But shouldn't `-I/usr/include/tirpc -ltirpc` be set in `ogdi-config` when it's built with TI RPC?

**Comment by rouault** [comment]
> But shouldn't -I/usr/include/tirpc -ltirpc be set in ogdi-config when it's built with TI RPC?

could be appropriate indeed but GDAL's configure doesn't use it

**Comment by sebastic** [comment]
GDAL's configure does use pkg-config, which contains the tirpc flags:
```
# cat /usr/share/pkgconfig/ogdi.pc 
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=${prefix}/include

Name: ogdi
Description: Open Geographic Datastore Interface
Version: 4.1.0
Cflags: -I${includedir}/ogdi -I/usr/include/tirpc
Libs: -L${libdir} -logdi
Libs.private: -lexpat -lz -ltirpc

```

**Comment by rouault** [comment]
> GDAL's configure does use pkg-config, which contains the tirpc flags:

ah indeed, so why doesn't that work ? That should be set in OGDI_INCLUDE in GDALmake.opt

**Comment by rouault** [comment]
> ah indeed, so why doesn't that work ? That should be set in OGDI_INCLUDE in GDALmake.opt

in a debian:unstable Docker image, I've just successfully (manually) built gdal-3.3.2RC1 against the packaged ogdi. The generated GDALmake.opt contains
OGDI_INCLUDE    =       -I/usr/include/ogdi -I/usr/include/tirpc
and this is passed when building the driver

**Comment by sebastic** [comment]
> in a debian:unstable Docker image, I've just successfully (manually) built gdal-3.3.2RC1 against the packaged ogdi.

That must be without the DODS driver because libdap is currently broken due to the RPC change in glibc too ([Debian Bug #993016](https://bugs.debian.org/993016)).

The CFLAGS for OGDI aren't used, the `C compiler` & `C++ compiler` flags don't include them unlike they do with the changes from this issue.

Full buildlog: [gdal_3.3.2~rc1+dfsg-1_amd64.txt](https://github.com/OSGeo/gdal/files/7081245/gdal_3.3.2.rc1%2Bdfsg-1_amd64.txt)

**Pull request closed without merging**
