### PR TITLE
Python code: Remove more bare exceptions

### PR DESCRIPTION
**Pull request by bje-**
## What does this PR do?

Remove more bare exceptions triggered Pylint warnings.

### CODE REVIEW

**Comment by rouault** [comment]
```
  TEST: pdf_1 ... fail (blowup)
Traceback (most recent call last):
  File "pymod/gdaltest_python2.py", line 43, in run_func
    result = func()
  File "./pdf.py", line 251, in pdf_1
    if pdf_checksum_available():
  File "./pdf.py", line 92, in pdf_checksum_available
    ret = gdaltest.pdf_is_checksum_available
AttributeError: 'module' object has no attribute 'pdf_is_checksum_available'
```

**Comment by rouault** [comment]
```
  TEST: ogr_rfc41_5 ... fail (blowup)
Traceback (most recent call last):
  File "pymod/gdaltest_python2.py", line 43, in run_func
    result = func()
  File "./ogr_rfc41.py", line 552, in ogr_rfc41_5
    f['nonexistent_field']
  File "/usr/lib/python2.7/dist-packages/osgeo/ogr.py", line 4695, in __getitem__
    raise ValueError("Illegal field requested in GetField()")
ValueError: Illegal field requested in GetField()
```

**Comment by bje-** [comment]
This is an interesting one. I wrote the change to the test assuming typical Python behaviour without looking at the source code. I think the test case is now correct and the code should be changed. The correct exception to raise is `KeyError`:

```
exception KeyError
    Raised when a mapping (dictionary) key is not found in the set of existing keys.
```

**Comment by rouault** [comment]
> I think the test case is now correct and the code should be changed. The correct exception to raise is KeyError:

Would makes sense indeed

**Comment by rouault** [comment]
```
TEST: virtualmem_1 ... fail (blowup)
Traceback (most recent call last):
  File "pymod\gdaltest_python2.py", line 43, in run_func
    result = func()
  File ".\virtualmem.py", line 54, in virtualmem_1
    ar = ds.ReadAsArray(0, 0, bufxsize, bufysize)
  File "Z:\home\travis\build\OSGeo\gdal\gdal\swig\python\build\lib.win-amd64-2.7\osgeo\gdal.py", line 2086, in ReadAsArray
    import gdalnumeric
  File "Z:\home\travis\build\OSGeo\gdal\gdal\swig\python\build\lib.win-amd64-2.7\osgeo\gdalnumeric.py", line 1, in <module>
    from numpy import *
ImportError: No module named numpy
```

```
  TEST: test_gdal_edit_py_5 ... fail (blowup)
Traceback (most recent call last):
  File "pymod\gdaltest_python2.py", line 43, in run_func
    result = func()
  File ".\test_gdal_edit.py", line 233, in test_gdal_edit_py_5
    array = band.ReadAsArray()
  File "Z:\home\travis\build\OSGeo\gdal\gdal\swig\python\build\lib.win-amd64-2.7\osgeo\gdal.py", line 2609, in ReadAsArray
    import gdalnumeric
  File "Z:\home\travis\build\OSGeo\gdal\gdal\swig\python\build\lib.win-amd64-2.7\osgeo\gdalnumeric.py", line 1, in <module>
    from numpy import *
ImportError: No module named numpy
```

**Pull request merged**
