### PR TITLE
GTiff: add minimum support for reading CRS from ESRI's .xml side car file (fixes #7187)

### LINKED ISSUE #7187: GDAL: coordinate info from  XML file not read which is delivered with TIFF/TFW
## Expected behavior and actual behavior.

We are trying to read digital orthophotos (DOP) provided by a federal state in Germany (open data license):
https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/

They have been published as ZIP'ed single tiles in TIFF/TFW-format.

The coordinate info is stored in respective XML files, apparently generated with ESRI ArcGIS 10.6.1.9270.

Problem: GDAL cannot read the CRS from the separate XML file. Not sure if this is supported at all.

## Steps to reproduce the problem.

```
gdalinfo /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
Driver: GTiff/GeoTIFF
Files: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
       /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tfw
Size is 5000, 5000
Origin = (250000.000009999988833,5887000.000000000000000)
Pixel Size = (0.200000000000000,-0.200000000000000)
Metadata:
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=635
  TIFFTAG_YRESOLUTION=635
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  250000.000, 5887000.000) 
Lower Left  (  250000.000, 5886000.000) 
Upper Right (  251000.000, 5887000.000) 
Lower Right (  251000.000, 5886000.000) 
Center      (  250500.000, 5886500.000) 
Band 1 Block=5000x1 Type=Byte, ColorInterp=Red
  Min=1.000 Max=237.000 
  Minimum=1.000, Maximum=237.000, Mean=86.330, StdDev=23.171
  Metadata:
    RepresentationType=ATHEMATIC
    STATISTICS_COVARIANCES=536.9047928211847,453.7981343585695,380.0063190303403,343.0145780252351
    STATISTICS_MAXIMUM=237
    STATISTICS_MEAN=86.330236120004
    STATISTICS_MINIMUM=1
    STATISTICS_SKIPFACTORX=1
    STATISTICS_SKIPFACTORY=1
    STATISTICS_STDDEV=23.171206114943
[...]
Band 4 Block=5000x1 Type=Byte, ColorInterp=Undefined
  Min=1.000 Max=235.000 
  Minimum=1.000, Maximum=235.000, Mean=128.333, StdDev=22.885
  Metadata:
    RepresentationType=ATHEMATIC
    STATISTICS_COVARIANCES=343.0145780252351,415.7474584563636,240.3456451711015,523.702186838615
    STATISTICS_MAXIMUM=235
    STATISTICS_MEAN=128.33311599999
    STATISTICS_MINIMUM=1
    STATISTICS_SKIPFACTORX=1
    STATISTICS_SKIPFACTORY=1
    STATISTICS_STDDEV=22.884540345801
```

I did not find any related issue.

## Operating system

Fedora 37

## GDAL version and provenance

GDAL which is shipped with Fedora 37 (RPM).

```
gdal-config --version
3.5.2
```

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by JHalbauer** [comment]
I tried reading the CRS from the .xml file. If the archive is already unzipped it works well. But when I tried reading the CRS from the .xml file within a remote and compressed archive with e.g. `gdalinfo /vsizip/vsicurl/path/to/remote/archive.zip/file_with_crs.tif` it does not work. Is there a problem with unzipping the .xml file or with `vsicurl`? How to solve this problem? Thanks in advance.

**Comment by rouault** [comment]
"gdalinfo /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif" finds the .xml file and the CRS.
@JHalbauer Which exact URL does not work for you?

**Comment by JHalbauer** [comment]
This one for example: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif

**Comment by rouault** [comment]
> This one for example: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif

That works for me:
```
$ gdalinfo  /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
Driver: GTiff/GeoTIFF
Files: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
       /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tfw
       /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.xml
Size is 5000, 5000
Coordinate System is:
PROJCRS["ETRS89 / UTM zone 33N",
    BASEGEOGCRS["ETRS89",
        ENSEMBLE["European Terrestrial Reference System 1989 ensemble",
            MEMBER["European Terrestrial Reference Frame 1989"],
            MEMBER["European Terrestrial Reference Frame 1990"],
            MEMBER["European Terrestrial Reference Frame 1991"],
            MEMBER["European Terrestrial Reference Frame 1992"],
            MEMBER["European Terrestrial Reference Frame 1993"],
            MEMBER["European Terrestrial Reference Frame 1994"],
            MEMBER["European Terrestrial Reference Frame 1996"],
            MEMBER["European Terrestrial Reference Frame 1997"],
            MEMBER["European Terrestrial Reference Frame 2000"],
            MEMBER["European Terrestrial Reference Frame 2005"],
            MEMBER["European Terrestrial Reference Frame 2014"],
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[0.1]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 33N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",15,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Europe between 12°E and 18°E: Austria; Denmark - offshore and offshore; Germany - onshore and offshore; Norway including Svalbard - onshore and offshore."],
        BBOX[46.4,12,84.42,18.01]],
    ID["EPSG",25833]]
[...snip....]
```

**Comment by msmitherdc** [comment]
more detail:HTTP: libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 libssh2/1.10.0 nghttp2/1.51.0VSICURL: GetFileSize(https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)=85136729  response_code=200VSICURL: Downloading 85131264-85136728 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206VSICURL: Downloading 85114880-85131263 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206VSICURL: Downloading 85098496-85114879 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206VSICURL: Downloading 85082112-85098495 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206VSICURL: Downloading 85065728-85082111 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206VSICURL: Downloading 0-16383 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206VSICURL: Downloading 16384-81919 (https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip)...VSICURL: Got response_code=206GDAL: GDALOpen(/vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif, this=0x55cf8641d670) succeeds as GTiff.Driver: GTiff/GeoTIFFGDAL: GDALDefaultOverviews::OverviewScan()MDReaderDigitalGlobe: XML Filename: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.xmlMDReaderResursDK1: XML Filename: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.xmlFiles: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif       /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tfw….Michael SmithOn Feb 7, 2023, at 6:48 AM, Even Rouault ***@***.***> wrote:﻿

This one for example: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif

That works for me:
$ gdalinfo  /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
Driver: GTiff/GeoTIFF
Files: /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
       /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tfw
       /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.xml
Size is 5000, 5000
Coordinate System is:
PROJCRS["ETRS89 / UTM zone 33N",
    BASEGEOGCRS["ETRS89",
        ENSEMBLE["European Terrestrial Reference System 1989 ensemble",
            MEMBER["European Terrestrial Reference Frame 1989"],
            MEMBER["European Terrestrial Reference Frame 1990"],
            MEMBER["European Terrestrial Reference Frame 1991"],
            MEMBER["European Terrestrial Reference Frame 1992"],
            MEMBER["European Terrestrial Reference Frame 1993"],
            MEMBER["European Terrestrial Reference Frame 1994"],
            MEMBER["European Terrestrial Reference Frame 1996"],
            MEMBER["European Terrestrial Reference Frame 1997"],
            MEMBER["European Terrestrial Reference Frame 2000"],
            MEMBER["European Terrestrial Reference Frame 2005"],
            MEMBER["European Terrestrial Reference Frame 2014"],
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[0.1]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 33N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",15,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Europe between 12°E and 18°E: Austria; Denmark - offshore and offshore; Germany - onshore and offshore; Norway including Svalbard - onshore and offshore."],
        BBOX[46.4,12,84.42,18.01]],
    ID["EPSG",25833]]
[...snip....]

**Comment by neteler** [comment]
@JHalbauer and I have tested it (patched GDAL 3.6.2 locally), it works. Thanks for this improvement, @rouault!

**Comment by JHalbauer** [comment]
Unfortunately it does not work for every URL. When I use
/vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33250-5886.zip/dop_33250-5886.tif
everything works fine and the CRS can be read.
But using
/vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33279-5879.zip/dop_33279-5879.tif
leads to the following error instead of the CRS within the output.
```
ERROR 1: cpl_unzOpenCurrentFile() failed
ERROR 4: CSLLoad2("/vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33279-5879.zip/dop_33279-5879.tfw") failed: unable to open file.
ERROR 1: cpl_unzOpenCurrentFile() failed
ERROR 1: cpl_unzOpenCurrentFile() failed
ERROR 1: cpl_unzOpenCurrentFile() failed
ERROR 3: Cannot open file '/vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33279-5879.zip/dop_33279-5879.xml'
```

**Comment by rouault** [comment]
> But using
> /vsizip/vsicurl/https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33279-5879.zip/dop_33279-5879.tif
> leads to the following error instead of the CRS within the output.

That's a server side issue. Nothing we can do about. Apparently Trent Micro InterScan Web security rejects some HTTP Range requests:
```
$ curl -v https://data.geobasis-bb.de/geobasis/daten/dop/rgbi_tif/dop_33279-5879.zip -H "Range: bytes=82575360-82591743"
*   Trying 194.76.232.112:443...
* TCP_NODELAY set
* Connected to data.geobasis-bb.de (194.76.232.112) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; ST=Brandenburg; L=Frankfurt (Oder); O=Landesvermessung und Geobasisinformation Brandenburg; CN=bereitstellungsportal.geobasis-bb.de
*  start date: Aug 17 00:00:00 2022 GMT
*  expire date: May 12 23:59:59 2023 GMT
*  subjectAltName: host "data.geobasis-bb.de" matched cert's "data.geobasis-bb.de"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust TLS RSA CA G1
*  SSL certificate verify ok.
> GET /geobasis/daten/dop/rgbi_tif/dop_33279-5879.zip HTTP/1.1
> Host: data.geobasis-bb.de
> User-Agent: curl/7.68.0
> Accept: */*
> Range: bytes=82575360-82591743
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Tue, 07 Feb, 2023 13:55:25 GMT
< Cache-Control: no-cache
< Content-Type: text/html; charset=UTF-8
< Server: IWSVA 6.5-SP3_Build_Linux_3257 $Date: 09/09/2021 12:39:38 PM$
< Content-Length: 5807
< X-Cache: MISS from _
< X-Cache-Lookup: MISS from _:80
< Via: 1.1 _ (squid)
< Connection: keep-alive
< 
<html><head><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/><title>Trend Micro InterScan Web Security Event</title></head><body><script> ....
```

**Comment by neteler** [comment]
Thanks for investigating - then we need to download those files.

**Comment by neteler** [comment]
> That's a server side issue. Nothing we can do about.

I have contacted data.geobasis-bb.de, hopefully they'll fix the HTTP range request server problem.

**Pull request merged**
