### PR TITLE
OSR_Panorama: Fix TM zone for projections with negative central meridian, fix import from invalid codes

### PR DESCRIPTION
**Pull request by drons**

### CODE REVIEW

**Comment by drons** [comment]
@BishopGIS Take a look, please

**Comment by BishopGIS** [comment]
@drons everything looks fine.

**Comment by rouault** [comment]
Merged. I've attempted a cherry-pick of the 2 fix commits to 3.6 but it fails with conflicts. If that's needed, I let it to you to create a backport pull request

**Comment by drons** [comment]
>  I've attempted a cherry-pick of the 2 fix commits to 3.6 but it fails with conflicts.

This PR is based on 23062fd1682eaec048e66591bd44139246dc76ff, but it have changes in `OGRSpatialReference`. I think backport to 3.6 is not possible due to ABI break.

@BishopGIS, @rouault Thanks!

**Pull request merged**
