### PR TITLE
Check for null before accessing img nodata values

### PR DESCRIPTION
**Pull request by jwittner**
Gdal documentation says, "The "nodata" value imaginary component - may be NULL even if real component is provided. "

I found a couple null derefs due to providing a real component with no imaginary.

http://www.gdal.org/structGDALWarpOptions.html#a1848d03a0deb1194a31e75a5b102a662

### CODE REVIEW

**Comment by jwittner** [comment]
The documentation also says this about the `padfSrcNoDataImag`, but the warp options `Validate` call has:

```
if( psOptions->padfSrcNoDataReal != NULL
        && psOptions->padfSrcNoDataImag == NULL )
    {
        CPLError( CE_Failure, CPLE_IllegalArg,
                  "GDALWarpOptions.Validate(): "
                  "padfSrcNoDataReal set, but padfSrcNoDataImag not set." );
        return FALSE;
    }
```

**Comment by rouault** [comment]
We can possibly relax the validate check if we ensure that all sites that use padfSrcNoDataImag do it in a safe way then

**Comment by jwittner** [comment]
Excellent. I can do that, but can it be a different PR?

**Comment by rouault** [comment]
Same PR is fine. This is closely related topics

**Comment by jwittner** [comment]
Will do! Coming soon. =)

**Comment by rouault** [comment]
I'd love that we have a test case for that. The easiest would probably to patch apps/gdalwarp_lib.cpp so that useless allocations of the imag arrays are removed. Like in https://github.com/OSGeo/gdal/blob/trunk/gdal/apps/gdalwarp_lib.cpp#L1408 , possibly others, but must be checked on a case by case basis.

**Comment by jwittner** [comment]
I want to run the tests locally, but am having a hard time finding documentation on how to do that. I found autotest/run_all.py. Can I just run that? What version of python should I use?

**Comment by rouault** [comment]
> I want to run the tests locally, but am having a hard time finding documentation on how to do that. I found autotest/run_all.py. Can I just run that? 

Yes.

> What version of python should I use?

 The python bindings work with Python 2.X or 3.X.

Need to be built with:
cd swig/python
make
(sudo make install)
and/or possibly point PYTHONPATH to where the bindings are built / installed.

**Comment by jwittner** [comment]
I'm on windows so I did:

cd swig\python
python setup.py build
python setup.py install
cd autotest
python run_all.py

I get some 85 failures, but I see the same ones with and without my changes.

**Comment by rouault** [comment]
Thanks. Committed in trunk in r38095. I didn't feel like it was critical to be backported in 2.2 or earlier branches.

**Comment by jwittner** [comment]
Totally reasonable not to backport it.

 I do have proj.4 installed and I moved the proj.dll next to the gdal202.dll, but probably that wasn't the right location because I still got the load failure messages.

**Pull request closed without merging**
