### PR TITLE
MiraMonVector: fix Issue 369216702

### PR DESCRIPTION
**Pull request by AbelPau**
MiraMonVector: fix Issue 369216702

## What does this PR do?
Fixes Issue 369216702

## What are related issues/pull requests?
https://issues.oss-fuzz.com/issues/369216702

## Tasklist

 - [x] Make sure code is correctly formatted (cf [pre-commit configuration](https://gdal.org/development/dev_practices.html#commit-hooks))
 - [ ] All CI builds and checks have passed

### CODE REVIEW

**Comment by AbelPau** [comment]
@rouault thanks for the comment. I've adopted your code.

**Comment by AbelPau** [comment]
@rouault may I concern about these bad pack header failing checks??

**Comment by rouault** [comment]
> may I concern about these bad pack header failing checks??

no, github networking issues. I've restarted the jobs

**Comment by AbelPau** [comment]
> > may I concern about these bad pack header failing checks??
> 
> no, github networking issues. I've restarted the jobs

Some check (linux) has failed again :(

**Comment by rouault** [comment]
> Some check (linux) has failed again :(

same issue, but I had to wait for the whole group to complete to restart

**Pull request merged**
