### PR TITLE
#4161 LVBAG Driver: add field definition for "gerelateerdewoonplaats"

### PR DESCRIPTION
**Pull request by justb4**
## What does this PR do?
The LVBAG driver currently ignores the Field 'gerelateerdewoonplaats' (related City) for 'nummeraanduiding' feature type. This PR adds the definition. Read all details in issue #4161.

NB it appears that the XML Element is similarly structured as `openbareruimteRef`, e.g.

```
                    <Objecten:documentnummer>2009-BB01570</Objecten:documentnummer>
                    <Objecten:ligtIn>
                        <Objecten-ref:WoonplaatsRef domein="NL.IMBAG.Woonplaats">1050</Objecten-ref:WoonplaatsRef>
                    </Objecten:ligtIn>
                    <Objecten:voorkomen>
.
.
                    <Objecten:ligtAan>
                        <Objecten-ref:OpenbareRuimteRef domein="NL.IMBAG.Openbareruimte">0106300000002560</Objecten-ref:OpenbareRuimteRef>
                    </Objecten:ligtAan>

```

Advantage is that uses the existing parsing and prepending for `domein` attribute. Hence the Field will be named
`woonplaatsRef` with typical value like `NL.IMBAG.Woonplaats.1050`. This will be added to the test-data and cases.

## What are related issues/pull requests?
Issue #4161

## Tasklist
(Existing testcases can be used).

 - [x] Review
 - [x] Adjust for comments
 - [x] Add testcases
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS: any
* Compiler: any

### CODE REVIEW

**Comment by rouault** [comment]
```
    def test_ogr_lvbag_dataset_num():

    
        ds = ogr.Open('data/lvbag/num.xml')
        assert ds is not None, 'cannot open dataset'
        assert ds.GetLayerCount() == 1, 'bad layer count'
        assert ds.GetLayer(1) is None
 

        lyr = ds.GetLayer(0)

        assert lyr.GetName() == 'Nummeraanduiding', 'bad layer name'
    
        assert lyr.GetGeomType() == ogr.wkbUnknown, 'bad layer geometry type'
        assert lyr.GetSpatialRef() is None, 'bad spatial ref'
        assert lyr.GetFeatureCount() == 3

        # This next line is not a duplicate. When the features are counted the SRS could have changed
        assert lyr.GetSpatialRef() is None, 'bad spatial ref'
        assert lyr.TestCapability(ogr.OLCStringsAsUTF8) == 1
   

>       assert lyr.GetLayerDefn().GetFieldCount() == 21
E       assert 22 == 21
E         +22
E         -21
```

**Comment by justb4** [comment]
Thanks @rouault ! Yes, the extra Field increments the field count. I also edited the issue id: should be #4161 . 
Need more to complete this PR?

**Comment by rouault** [comment]
> Need more to complete this PR?

@yorickdewid will tell

**Comment by yorickdewid** [comment]
Maybe add a testcase for this specific case? Just so we know existing logic won't be broken

**Comment by justb4** [comment]
Yes will add testcase(s) in https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_lvbag.py. Also need to adapt the data input to cover the case where `num` testdata has the field `gerelateerdewoonplaats` populated.

**Comment by justb4** [comment]
AFAICS made changes to complete this PR:

- Field definition (Field name appeared different: `woonplaatsRef`, structure similar to `openbareruimteRef`
- adapted test data for `num.xml` (second element has a `woonplaatsRef`) 
- added 2 test cases: for presence or non-presence of the Field

Did all work via branch in GitHub. Appears each edit is a commit, that triggers  GH Workflows. Sorry for that. 
Maybe we can somehow squash the commits?

**Comment by rouault** [comment]
> Maybe we can somehow squash the commits?

The 'Squash and merge" github button will do that :-)

**Comment by justb4** [comment]
> > Maybe we can somehow squash the commits?
> 
> The 'Squash and merge" github button will do that :-)
Ok, yes, That button reviewers are the controller of :-). To do this from my end in GH, have not seen. 
But I see builds passing here, fingers crossed...

**Comment by rouault** [comment]
> To do this from my end in GH, have not seen.

you can do that locally with git. See https://github.com/OSGeo/gdal/blob/master/CONTRIBUTING.md#working-with-a-feature-branch

**Comment by justb4** [comment]
> > To do this from my end in GH, have not seen.
> 
> you can do that locally with git. See https://github.com/OSGeo/gdal/blob/master/CONTRIBUTING.md#working-with-a-feature-branch

Yes, off course :-). Should I do the commit-squash then?

**Comment by rouault** [comment]
> Should I do the commit-squash then?

no I'll do it. That'll save a few CI CPU cycles

**Comment by justb4** [comment]
> > Should I do the commit-squash then?
> 
> no I'll do it. That'll save a few CI CPU cycles

Ok, thanks @rouault !

**Comment by justb4** [comment]
And I now see in the Travis build output that all new tests (with and without the newly added Field) passed! 
`ogr/ogr_lvbag.py::test_ogr_lvbag_dataset_num PASSED`. So let's see the AppVeyor outcome next.

**Pull request merged**
