### PR TITLE
update ECW variables hint in nmake.opt

### PR DESCRIPTION
**Pull request by chacha21**
## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by rouault** [comment]
do we really need that ? MSVC_VER is set to 1900 at line 42

**Comment by chacha21** [comment]
> 
> 
> do we really need that ? MSVC_VER is set to 1900 at line 42

This is for the case that ECW_* definitions are deported to nmake.local
Since nmake.local is "included" before the default definition of MSVC_VER, it would prevent a syntax error

**Comment by rouault** [comment]
could you rebase your change on top of latest master ?

**Comment by chacha21** [comment]
Unfortunately I am not sure to know what it means, git is so much a mystery.
I use GitHub Desktop, and the "Branch  > Rebase current branch" won't let me "Start rebase" after selecting "master".

**Comment by rouault** [comment]
Or just update your fork to latest upstream master and recreate a new clean branch

**Comment by chacha21** [comment]
done #2768

**Pull request merged**
