### PR TITLE
CSharp: Switch default platform target to AnyCPU #1368

### PR DESCRIPTION
**Pull request by szekerest**
## Tasklist

 - [ ] ADD YOUR TASKS HERE
 - [ ] Add test case(s)
 - [ ] Add documentation
 - [ ] Review
 - [ ] Adjust for comments
 - [ ] All CI builds and checks have passed

## Environment

Provide environment details, if relevant:

* OS:
* Compiler:

### CODE REVIEW

**Comment by rouault** [comment]
Is it appropriate for backport to 3.4 ?

**Comment by szekerest** [comment]
> Is it appropriate for backport to 3.4 ?

Yes, that would be cool

**Comment by runette** [comment]
Note that this change will not be reflected in the CMake builds - since they use a different template file. I will submit a very small PR that reflects this in the CMake script

**Comment by szekerest** [comment]
@runette Thank you for your contribution the current makefile based approach still used by the gisinternals builds. 
I haven't tested this cmake version so far, but I think specifying the runtime identifier when compiling the gdal assemblies will invalidate the anycpu setting. Also we should target netstandard2.x by default instead of netcore 5.0. in order to keep supporting netframework 4.6.1 or above with that single build.

**Pull request merged**
