### PR TITLE
Fix HDF4 Plugin build for Visual C++

### PR DESCRIPTION
**Pull request by mpdaly**
## What does this PR do?

Fixes the incomplete HD4 Plugin build for Visual C++

## What are related issues/pull requests?

None

## Environment

* OS: Windows
* Compiler: VS 2017 15.7.1, CL 19.14.26428.1

### CODE REVIEW

**Comment by IvanLucena** [comment]
Hi there,

Building HDF4 and HDF5 as a plugin both on Windows and Linux I noticed something strange.

Once you build the plugins it creates the files gdal_HDF{4,5}.{dll, so} and the driver.

That's fine. You can see HDF{4,5} when running "gdalinfo --formats".

But the HDF4Image and HDF5Image drivers are not listed and that is not the same behavior as when building those drivers into the GDAL library (not plugin).

And that causes problems when dealing with HDF-EOS datasets. Like, you can list the subdatsdets with but you cannot access them individually.

There is a trick to solve that problem but I am wondering if we could come up with a better solution.

Here is the trick and if you know the GDAL plugin machanism you know how it works.

Just copy the plugins files:

C:/> cd $GDAL_DRIVER_PATH
C:/PATH> copy gdal_HDF4.dll gdal_HDF4Image.dll

$ cd $GDAL_DRIVER_PATH
$ cp gdal_HDF4.so gdal_HDF4Image.so

Regards,

Ivan
________________________________

**Comment by rouault** [comment]
> But the HDF4Image and HDF5Image drivers are not listed

If HDF4_PLUGIN is defined in nmake.opt/.local, then -DHDF4_PLUGIN is passed to the compiler and GDALRegister_HDF4() should then call GDALRegister_HDF4Image()

**Comment by IvanLucena** [comment]
Hi Even,

Yes, you are right. The function GDALRegister_HDF4/5 will call GDALRegister_HDF4/5Image if HDF_PLUGIN is defined.

But on Linux and OSX the solution would be to add "CPPFLAGS='-DHDF_PLUGIN' to ./configure. I suppose.

I tried that and found a problem on frmts/hdf4/GNUmakefile.

This makefile calls frmts/hdf4/hdd-eos/GNUMakefile that build the EOS API. But the ".o" files are placed on frtms/o. If the intentions was to build a plugins, they shouldn't be put there.

Maybe we should fix this GNUmakefile first but I found a workaround by changing only frmts/hdf4/GNUmakefile.

As long as people knows that they should run "make clean" before building the GDAL base library it shouldn't be a problem.

For example, here is my building script for OSX and Linux:


#!/bin/sh


PREFIX=${PWD}/dist


SO_EXT=so


if [[ "$OSTYPE" == "darwin"* ]]; then

    SO_EXT=dylib

fi


rm -rf $PREFIX

./configure --prefix=$PREFIX \

  --without-libtool

make clean

make

make install


./configure --prefix=$PREFIX \

  --without-libtool \

  --with-hdf4=/Users/ilucena/Dev/hdf-4.2.13/dist \

  CPPFLAGS='-DHDF4_PLUGIN'

cd frmts/hdf4

make clean

make

make plugin

mv gdal_HDF4.$SO_EXT $PREFIX/lib/gdalplugins

make clean

cd ../..

Note that it runs ./configure twice. I believe that only the PDF plugins can be build at once, at the same time we build GDAL base library and tools. D'accord?

Here is my workaround for frtms/hdf4/GNUmakefile:


@@ -18,10 +18,12 @@ lib-hdfeos:



 install-obj:   $(SUBLIBS) $(O_OBJ:.o=.$(OBJ_EXT))



+EOS_SO          = ../o/EHapi.o ../o/GDapi.o ../o/SWapi.o ../o/gctp_wrap.o

+

 PLUGIN_SO       = gdal_HDF4.$(SO_EXT)



 plugin: $(PLUGIN_SO)



 $(PLUGIN_SO):   $(OBJ)

-       $(LD_SHARED) $(LNK_FLAGS) $(OBJ) $(CONFIG_LIBS_INS) $(LIBS) \

+       $(LD_SHARED) $(LNK_FLAGS) $(OBJ) $(EOS_SO) $(CONFIG_LIBS_INS) $(LIBS) \

                -o $(PLUGIN_SO)

If that is an acceptable solution I could merge it.

Regards,

Ivan

________________________________

**Comment by rouault** [comment]
@IvanLucena Your patch to GNUmakefile looks plausible to me (untested on my side though). Yes you found that on Unix you need to non-libtool builds so that the plugins can be built. I actually tried the other day to fix the GNUmakefile of frmts/pdf to work in libtool  and non-libtool mode for building the plugin, but failed.

**Pull request merged**
