### PR TITLE
AmigoCloud OGR Driver

### PR DESCRIPTION
**Pull request by rburhum**
Support for insert/delete/update of AmigoCloud data

### CODE REVIEW

**Comment by rouault** [comment]
As we now have turned all a lot of warning flags and -Werror, there are a few things to fix : https://travis-ci.org/OSGeo/gdal/builds/89528955

**Comment by rburhum** [comment]
Sounds good. We'll take care of those warnings. 

Are these "warnings as errors" turned on by default (i.e. if we compile with configure+make will we run into the same errors)? Or do we need to pass some extra flags to achieve this?

cc @vchernetsky

**Comment by vchernetsky** [comment]
I found it in the Travis build:

make USER_DEFS="-Wextra -Werror" -j3

**Comment by vchernetsky** [comment]
What do I do with this one:

ogramigocloudlayer.cpp:111:34: error: 'json_object_object_get' is deprecated [-Werror,-Wdeprecated-declarations]
            json_object* poVal = json_object_object_get(poRowObj, osFIDColName);

**Comment by rouault** [comment]
> ogramigocloudlayer.cpp:111:34: error: 'json_object_object_get' is deprecated [-Werror,-Wdeprecated-declarations]

You shouldn't get this on Travis which uses internal libjson-c (libjson-c 0.11). That's a separate issue that should fixed in the whole tree, but you can ignore that one.

**Comment by rburhum** [comment]
OK, committing through SVN...

**Comment by rburhum** [comment]
Committed through SVN

**Pull request closed without merging**
