### PR TITLE
Make GMLAS and NAS drivers robust to XML billion laugh attack

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
The backport to `release/3.9` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply e8182bb117... NAS: make it robust to XML billion laugh attack
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
hint: Disable this message with "git config advice.mergeConflict false"

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging autotest/ogr/ogr_gml.py
[backport-10806-to-release/3.9 ef86211477] Test that GML driver is robust to XML billion laugh attack
 Author: Even Rouault <even.rouault@spatialys.com>
 Date: Sun Sep 15 22:47:35 2024 +0200
 3 files changed, 109 insertions(+)
 create mode 100644 autotest/ogr/data/gml/billionlaugh.gml
 create mode 100644 autotest/ogr/data/gml/billionlaugh.xsd
Auto-merging autotest/ogr/ogr_nas.py
CONFLICT (content): Merge conflict in autotest/ogr/ogr_nas.py

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release/3.9 release/3.9
# Navigate to the new working tree
cd .worktrees/backport-release/3.9
# Create a new branch
git switch --create backport-10806-to-release/3.9
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 640dafca4f90fa315819d6cfc5595ab7c99914b8,e8182bb1170b832405b5fb05189b34ad3873aa93,29d44e663ddcb59594b37932c12fe911eb2054c4
# Push it to GitHub
git push --set-upstream origin backport-10806-to-release/3.9
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release/3.9
```
Then, create a pull request where the `base` branch is `release/3.9` and the `compare`/`head` branch is `backport-10806-to-release/3.9`.

**Comment by rouault** [comment]
backported to 3.9 per ea46b20544557cf4dbc73d97ac0502dffb65bc2a , 1cbd74dd6bd22fea001ae48fb254f2a01fb99873 and 13097553e3df504f2e12168cfe5ff5a64de5b37a

**Comment by imincik** [comment]
My weekly master build is failing now on `test_ogr_gmlas_billion_laugh`. It looks related to this PR. 

```
       > =========================== short test summary info ============================
       > FAILED ogr/ogr_gmlas.py::test_ogr_gmlas_billion_laugh - AssertionError: Regex pattern did not match.
       >  Regex: 'File probably corrupted'
       >  Input: "data/gml/billionlaugh.xsd:37:87 namespace 'http://www.opengis.net/gml/3.2' is referenced without import declaration\nMay be caused by: data/gml/billionlaugh.xsd:40:50 namespace 'http://www.opengis.net/gml/3.2' is referenced without import declaration\nMay be caused by: data/gml/billionlaugh.xsd:17:112 namespace 'http://www.opengis.net/gml/3.2' is referenced without import declaration\nMay be caused by: data/gml/billionlaugh.xsd:20:50 namespace 'http://www.opengis.net/gml/3.2' is referenced without"
```

**Comment by rouault** [comment]
@imincik What is the version of your Xerces-C library?

**Comment by imincik** [comment]
> @imincik What is the version of your Xerces-C library?

3.2.5

**Comment by rouault** [comment]
> 3.2.5

hum, ok, as our Alpine CI builds (https://github.com/OSGeo/gdal/actions/runs/10874207420/job/30171230680) which pass fine. No idea why you get a different error (in any case this is probably just an issue with the test itself)

**Comment by imincik** [comment]
Thank you for investigation.

**Pull request merged**
