### PR TITLE
Add comments on how to fix System.AccessViolationException

### PR DESCRIPTION
**Pull request by czielin**
Add comments on how to fix System.AccessViolationException on some larger images. Related to issue #3289

### CODE REVIEW

**Comment by rouault** [comment]
I'm not super enthusiastic about adding such comment without the root cause having been identified. Would you possibly read more than 2 GB at once ? (wondering if it might be a 32-bit integer overflow somewhere)

**Comment by czielin** [comment]
The NTF source images that are causing a problem are in the 200MB to 400MB range on disk. Not sure how that translates to working memory. I'll run another test when I have a chance and keep on eye on memory utilization.

**Comment by rouault** [comment]
> when running as 32-bit.

eh, still people running 32 bit code those days !?!!

> The Dataset.ReadRaster() version only uses about a third of the memory (and also takes about a third of the time).

That doesn't make sense to me. If you read the same quantity of information with Dataset.ReadRaster() or Band.ReadRaster(), you should have similar memory consumption

Closing this PR as I don't think it is relevant.

**Comment by czielin** [comment]
> eh, still people running 32 bit code those days !?!!

Indeed. In this case it stemmed from our unit tests being configured to run as 32-bit. Though it appears we're not the only ones. The code sample provided in GDALReadDirect.cs uses 32-bit integers and it throws an Arithmetic exception when I run the test application as 64-bit. When I change the calls to ToInt64() it works.

image

> That doesn't make sense to me. If you read the same quantity of information with Dataset.ReadRaster() or Band.ReadRaster(), you should have similar memory consumption

I initially assumed the same, but this is not what we are observing when plugging the same file into the two sets of sample code provided in the repo. I do not know enough about how the ReadRaster method works to know if the problem is in the method itself, or the way the sample code is written.

I still think there is some value for future consumers in mentioning that the approach in these samples will not perform optimally. It certainly would have saved us a good amount of time. 

Happy to create another PR with the ToInt64() fix and/or updated commenting if you think it is valuable.

**Comment by rouault** [comment]
> I initially assumed the same, but this is not what we are observing when plugging the same file into the two sets of sample code provided in the repo

The swig/csharp/apps/GDALReadDirect.cs reads into a RGBA pixel-interleave buffer, whereas swig/csharp/apps/GDALRead.cs reads in separate per-band buffers. Those are 2 valid use cases depending on the needs. You perhaps overallocate things when you use the Band.RasterIO() call

> Happy to create another PR with the ToInt64() fix

would be welcome

**Pull request closed without merging**
