### PR TITLE
Revert merge of pull request #1906

### PR DESCRIPTION
**Pull request by rouault**
Revert initial commits and follow-up commits

### CODE REVIEW

**Comment by jef-n** [comment]
@rouault Oh, I just noticed that `gdal_viewshed.exe` target was referenced as `viewshed.exe` in `makefile.vc` and was going to commit a fix (still building…).

**Comment by rouault** [comment]
@jef-n PR #1906 wasn't ready to be merged, so please do not commit your fix into master, but maybe push it to some branch and mentions the commit in https://github.com/OSGeo/gdal/pull/1906

**Comment by mloskot** [comment]
@rouault FYI, Accidental merges can be prevented by requiring at least one approving review

image

**Comment by rouault** [comment]
> Accidental merges can be prevented by requiring at least one approving review

yes, but can I self-approve my own PR :-) ? I also saw some options to prevent merging when one of the CI bot fails, but they aren't 100% reliable so I was a bit hesitant

**Comment by mloskot** [comment]
> > Accidental merges can be prevented by requiring at least one approving review
> 
> yes, but can I self-approve my own PR :-) ?

No, you can not, I'm afraid.

> I also saw some options to prevent merging when one of the CI bot fails, but they aren't 100% reliable so I was a bit hesitant

Yes, that is also why I am not suggesting to enable those. On the other hand, there is a way to select particular CI checks, e.g. the reliable ones :-)

image

**Comment by rouault** [comment]
>  the reliable ones :-)

None of Travis-CI or AppVeyor are 100% reliable as there is always network activity involved. That said most of the time, it is a matter of restarting the failed job, but only people with appropriate rights  (push rights) can do that

**Comment by hobu** [comment]
Sorry about this. I had four remotes and thought I renamed it, but the tracking branch was set otherwise. git is so fun...

**Comment by rouault** [comment]
@hobu If you think you can fix quickly the issues that make Travis & AppVeyor to fail, we don't need to apply this revert. Addressing other review comments can be done later

**Comment by mloskot** [comment]
I'm not trying to make fuss about it, just briefly brainstormed way to protect ourselves as I near-collision merges almost happened to me in the past.

**Comment by rouault** [comment]
No longer needed since urgent fixes have been applied to master to make CI happy

**Pull request closed without merging**
