### PR TITLE
Viewshed adjustments /documentation fixes/ (#1917)

### PR DESCRIPTION
**Pull request by szekerest**

### CODE REVIEW

**Comment by rouault** [comment]
Seems there's an issue in the PDF generation

**Comment by szekerest** [comment]
Not sure why. I'm not an expert in rst

**Comment by rouault** [comment]
> Not sure why. I'm not an expert in rst

I finally figured it. See https://github.com/OSGeo/gdal/pull/2029/commits/24fb88699926514460550323ebf04b820fca9103 that I've added to your branch

**Comment by szekerest** [comment]
> I finally figured it. See [24fb886](https://github.com/OSGeo/gdal/commit/24fb88699926514460550323ebf04b820fca9103) that I've added to your branch

Great, thank you!

**Pull request merged**
