### PR TITLE
Python code: Remove blank lines at EOF

### PR DESCRIPTION
**Pull request by bje-**
## What does this PR do?

Remove blank lines at the end of file. Silences diagnostic W391.

### CODE REVIEW

**Comment by mloskot** [comment]
Just to clarify, W391 is warning about two consecutive `\n\n` at end of file, not one `\n` correct?

**Comment by bje-** [comment]
It warns about a blank line, regardless of the line termination characters for the system you're looking at it on.

**Comment by mloskot** [comment]
I mean, a blank line at EOF is kosher as per "w292 no newline at end of file". Or how W391 is different. No?

**Comment by bje-** [comment]
W292 is no line termination character(s) at the end of file. W291 is more than one set of char(s).

**Comment by mloskot** [comment]
Ok, thanks for clarification

**Comment by rouault** [comment]
should be updated when nitf_75 issue of https://github.com/OSGeo/gdal/pull/386 is fixed

**Pull request merged**
