### PR TITLE
Add leaflet template to gdal2tiles.py

### PR DESCRIPTION
**Pull request by jnth**
Hi,

This PR add Leaflet template (HTML) to the gdal2tiles.py script.

### CODE REVIEW

**Comment by rouault** [comment]
Who is "Live System User" the author of the commit ?

**Comment by rouault** [comment]
apps/gdal_utilities.dox would also need to be updated

**Comment by jnth** [comment]
I used a linux live usb to alter and test the script from a clean environnement. I forgot to configure git...

Ok, I update apps/gdal_utilities.dox

**Comment by rouault** [comment]
Committed in r30962

**Pull request closed without merging**
